In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Santiago Silva
*Métodos computacionales*

---

#1
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [3]:
np.random.seed(0)
A = np.random.randint(1, 10, size=(3, 3)) #Matriz A
B = np.random.randint(1, 10, size=(3, 3)) #Matriz B
C = np.random.randint(1, 10, size=(3, 3)) #Matriz C

print("Matriz A:\n", A)
print("Matriz B:\n", B)
print("Matriz C:\n", C)

# 1. AB ≠ BA
AB = A @ B #A * B
BA = B @ A # B * A
print("\n1. ¿AB ≠ BA?:", not np.allclose(AB, BA)) #compara si las matrices son diferentes

# 2. (AB)C = A(BC)
ABC1 = (A @ B) @ C
ABC2 = A @ (B @ C)
print("\n2. (AB)C = A(BC):", np.allclose(ABC1, ABC2))

# 3. A(B + C) = AB + AC
left = A @ (B + C)
right = A @ B + A @ C
print("\n3. A(B + C) = AB + AC:", np.allclose(left, right))

# 4. (A + B)C = AC + BC
left = (A + B) @ C
right = A @ C + B @ C
print("\n4. (A + B)C = AC + BC:", np.allclose(left, right))

# 5. (AB)ᵀ = BᵀAᵀ
left = (A @ B).T
right = B.T @ A.T
print("\n5. (AB)ᵀ = BᵀAᵀ:", np.allclose(left, right))

# 6. det(AB) = det(A) * det(B)
det_AB = la.det(A @ B)
det_A_det_B = la.det(A) * la.det(B)
print("\n6. det(AB) = det(A) * det(B):", np.allclose(det_AB, det_A_det_B))

# 7. (Aᵀ)ᵀ = A
print("\n7. (Aᵀ)ᵀ = A:", np.allclose((A.T).T, A))

# 8. (cA)ᵀ = cAᵀ
c = 5 #cualquier escalar arbitrario
left = (c * A).T
right = c * A.T
print("\n8. (cA)ᵀ = cAᵀ:", np.allclose(left, right))

# 9. (A + B)ᵀ = Aᵀ + Bᵀ
left = (A + B).T
right = A.T + B.T
print("\n9. (A + B)ᵀ = Aᵀ + Bᵀ:", np.allclose(left, right))


Matriz A:
 [[6 1 4]
 [4 8 4]
 [6 3 5]]
Matriz B:
 [[8 7 9]
 [9 2 7]
 [8 8 9]]
Matriz C:
 [[2 6 9]
 [5 4 1]
 [4 6 1]]

1. ¿AB ≠ BA?: True

2. (AB)C = A(BC): True

3. A(B + C) = AB + AC: True

4. (A + B)C = AC + BC: True

5. (AB)ᵀ = BᵀAᵀ: True

6. det(AB) = det(A) * det(B): True

7. (Aᵀ)ᵀ = A: True

8. (cA)ᵀ = cAᵀ: True

9. (A + B)ᵀ = Aᵀ + Bᵀ: True


#2

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [8]:
def determinante_laplace(matrix):

    if matrix.shape == (1, 1): #si la matriz es 1x1, su determinante es el único elemento
        return matrix[0, 0]

    if matrix.shape == (2, 2): #Si la matriz es 2x2, se usa det(A) = a11*a22 - a12*a21
        return matrix[0, 0]*matrix[1, 1] - matrix[0, 1]*matrix[1, 0]

    #para matriz de orden > 2
    det = 0  #inicializa el determinante

    for j in range(matrix.shape[1]):  #recorre las columnas de la primera fila
        submatrix = np.delete(np.delete(matrix, 0, axis=0), j, axis=1)  #calcula el menor M1j eliminando la primera fila y la columna j
        sign = (-1) ** j #signo del cofactor
        cofactor = sign * matrix[0, j] * determinante_laplace(submatrix)
        det += cofactor #suma el cofactor al det

    return det

In [9]:
np.random.seed(1)
A = np.random.randint(1, 10, size=(3, 3))
print("Matriz A:\n", A)

det_laplace = determinante_laplace(A)
det_numpy = np.linalg.det(A)

print("\nDeterminante (Laplace recursivo):", det_laplace)
print("Determinante (numpy.linalg.det):", det_numpy)

Matriz A:
 [[6 9 6]
 [1 1 2]
 [8 7 3]]

Determinante (Laplace recursivo): 45
Determinante (numpy.linalg.det): 44.99999999999999


#3 Método de Gauss - Seidel

Sea \$A\in\mathbb{R}^{n\times n}\$ no singular y sea \$b\in\mathbb{R}^n\$.
Descomponga \$A\$ como

$$
A \;=\; D \;+\; L \;+\; U,
$$

donde

* \$D\$ es la matriz diagonal de \$A\$,
* \$L\$ es la parte estrictamente triangular inferior,
* \$U\$ es la parte estrictamente triangular superior.

El algoritmo de Gauss - Seidel reorganiza el sistema \$Ax=b\$ como

$$
x \;=\; (D+L)^{-1}\bigl(b \;-\; Ux\bigr),
$$

y genera la sucesión

$$
x_i^{(k+1)}
= \frac{1}{a_{ii}}
\Bigl(b_i - \sum_{j<i} a_{ij}\,x_j^{(k+1)} - \sum_{j>i} a_{ij}\,x_j^{(k)}\Bigr),
\qquad i=1,\dots,n.
$$

Implemente una función `gauss_seidel(A, b, tol=1e-7, max_iter=100)` que:
   * Realice las iteraciones hasta que
     $\lVert x^{(k+1)}-x^{(k)}\rVert_\infty<\text{tol}$
     o se alcance `max_iter`;
   * devuelva el vector solución aproximado \$x\$, el número de iteraciones realizadas y la norma del último residuo.

Incluya una documentación clara.

Luego,

   * Genere una matriz aleatoria \$5\times5\$ (por ejemplo, con `np.random.rand`) y un vector \$b\$ aleatorio.
   * Resuelva \$Ax=b\$ con su función; calcule el error relativo frente a `numpy.linalg.solve`.
   * Estime igualmente el error respecto a la solución obtenida mediante \$x=A^{-1}b\$ (usando `numpy.linalg.inv`).
   * Presente las normas de los residuos y los errores relativos.

In [12]:
def gauss_seidel(A, b, tol=1e-7, max_iter=100):
    """
    Parámetros:
    A: matriz cuadrada no singular (numpy array)
    b: vector de términos independientes
    tol: tolerancia para la norma del cambio en x (criterio de parada)
    max_iter: número máximo de iteraciones permitidas

    Retorna:
    x: solución aproximada
    num_iter: número de iteraciones realizadas
    res_norm: norma infinita del último residuo
    """
    n = len(b)
    x = np.zeros_like(b)
    x_old = x.copy()

    for k in range(max_iter):
        x_old = x.copy()  #guarda la solución anterior

        #iteramos sobre cada ecuación
        for i in range(n):
            sum1 = np.dot(A[i, :i], x[:i]) #suma de elementos anteriores ya actualizados
            sum2 = np.dot(A[i, i+1:], x_old[i+1:]) #suma de elementos posteriores
            x[i] = (b[i] - sum1 - sum2) / A[i, i] #form de actualizacion

        diff_norm = np.linalg.norm(x - x_old, ord=np.inf) #calculo de la norma infinita del cambio
        if diff_norm < tol:
            break #convergió

    res = A @ x - b #residuo final (Ax - b)
    res_norm = np.linalg.norm(res, ord=np.inf)

    return x, k+1, res_norm

np.random.seed(0)
A = np.random.rand(5, 5) * 10 #matriz 5x5 aleatoria
b = np.random.rand(5) * 10 #vector b aleatorio

#nos aseguramos que A sea estrictamente diagonalmente dominante (para garantizar convergencia)
for i in range(5):
    A[i,i] += sum(np.abs(A[i]))  #se suma el total de la fila a la diagonal

#Gauss-Seidel
x_gs, iteraciones, residuo = gauss_seidel(A, b)

#numpy.linalg.solve
x_solve = np.linalg.solve(A, b)

#matriz inversa
x_inv = np.linalg.inv(A) @ b

#errores relativos
error_solve = np.linalg.norm(x_gs - x_solve, ord=np.inf) / np.linalg.norm(x_solve, ord=np.inf)
error_inv = np.linalg.norm(x_gs - x_inv, ord=np.inf) / np.linalg.norm(x_inv, ord=np.inf)

print("\nMatriz A:\n", A)
print("\nVector b:\n", b)
print("\nSolución Gauss-Seidel:\n", x_gs)
print("Iteraciones realizadas:", iteraciones)
print("Norma del último residuo:", residuo)
print("\nError relativo vs np.linalg.solve:", error_solve)
print("Error relativo vs np.linalg.inv:", error_inv)



Matriz A:
 [[33.84117733  7.15189366  6.02763376  5.44883183  4.23654799]
 [ 6.45894113 37.59945816  8.91773001  9.63662761  3.83441519]
 [ 7.91725038  5.2889492  34.53341777  9.25596638  0.71036058]
 [ 0.871293    0.20218397  8.32619846 33.66293193  8.70012148]
 [ 9.78618342  7.99158564  4.61479362  7.80529176 32.56334297]]

Vector b:
 [6.39921021 1.43353287 9.44668917 5.21848322 4.1466194 ]

Solución Gauss-Seidel:
 [ 0.14320825 -0.06666852  0.22772673  0.0828462   0.04853291]
Iteraciones realizadas: 11
Norma del último residuo: 5.058993390871791e-07

Error relativo vs np.linalg.solve: 4.947351627370065e-08
Error relativo vs np.linalg.inv: 4.947351621276012e-08


#4 Método de potencias para el valor propio dominante

Sea \$A\in\mathbb{R}^{n\times n}\$ diagonalizable con valor propio dominante \$\lambda\_{\max}\$ (en magnitud) y vector propio asociado \$v\_{\max}\$.

El método de potencias genera, a partir de un vector inicial \$q^{(0)}\neq 0\$, la sucesión

$$
q^{(k+1)} \;=\; \frac{A\,q^{(k)}}{\lVert A\,q^{(k)}\rVert_2},
\qquad
\lambda^{(k+1)} \;=\; (q^{(k+1)})^{\!\top} A\, q^{(k+1)},
$$

que converge a \$v\_{\max}/\lVert v\_{\max}\rVert\_2\$ y a \$\lambda\_{\max}\$ respectivamente, bajo hipótesis estándar.

Implemente `power_method(A, tol=1e-7, max_iter=1000)` que:

   * Acepte matrices reales cuadradas,
   * Devuelva \$\lambda\_{\max}\$, el vector propio normalizado \$v\_{\max}\$, el número de iteraciones y la última variación relativa de \$\lambda\$,
   * detenga la iteración cuando
     $\bigl|\lambda^{(k+1)}-\lambda^{(k)}\bigr|<\text{tol}\,|\lambda^{(k+1)}|$
     o se alcance `max_iter`.

Luego,
   * Genere una matriz simétrica aleatoria \$6\times6\$ (por ejemplo, \$A = (M+M^\top)/2\$ con \$M\$ aleatoria).
   * Aplique su `power_method` y compare \$\lambda\_{\max}\$ y \$v\_{\max}\$ con los resultados de `numpy.linalg.eig`.

In [13]:
def power_method(A, tol=1e-7, max_iter=1000):
    """
    Parámetros:
    A: matriz cuadrada
    tol: tolerancia para la variación relativa de λ
    max_iter: número máximo de iteraciones permitidas

    Retorna:
    lambda_max : valor propio dominante aproximado
    v_max : vector propio asociado normalizado
    iteraciones : número de iteraciones realizadas
    delta : última variación relativa de λ
    """
    n = A.shape[0]
    q = np.random.rand(n) #vector inicial aleatorio
    q = q / la.norm(q, 2) #normaliza q

    lambda_old = 0

    for k in range(max_iter):
        z = A @ q #A * q
        q = z / la.norm(z, 2) #Normaliza z para obtener nuevo q
        lambda_new = q.T @ A @ q #aproximación de λ

        #calcula la variación relativa
        delta = np.abs(lambda_new - lambda_old) / (np.abs(lambda_new) + 1e-10)

        if delta < tol:
            break

        lambda_old = lambda_new

    return lambda_new, q, k+1, delta


np.random.seed(0)
M = np.random.randint(1, 10, size=(6, 6))
A = (M + M.T) / 2 #A es simétrica (garantiza diagonalización)

#método de potencias
lambda_max, v_max, iteraciones, delta = power_method(A)

#numpy.linalg.eig
eigvals, eigvecs = np.linalg.eig(A)
idx = np.argmax(np.abs(eigvals)) #indice del mayor valor propio en magnitud
lambda_np = eigvals[idx]
v_np = eigvecs[:, idx]

#normalizar vector propio de numpy
v_np = v_np / la.norm(v_np, 2)


print("\nMatriz A:\n", A)
print("\nResultado método de potencias:")
print("Valor propio dominante:", lambda_max)
print("Vector propio asociado:\n", v_max)
print("Iteraciones realizadas:", iteraciones)
print("Última variación relativa:", delta)

print("\nResultado numpy.linalg.eig:")
print("Valor propio dominante (numpy):", lambda_np)
print("Vector propio asociado (numpy):\n", v_np)



Matriz A:
 [[6.  3.5 6.5 3.  6.  3. ]
 [3.5 3.  3.5 7.  6.5 6.5]
 [6.5 3.5 7.  8.5 4.5 6.5]
 [3.  7.  8.5 5.  3.5 2.5]
 [6.  6.5 4.5 3.5 4.  8.5]
 [3.  6.5 6.5 2.5 8.5 1. ]]

Resultado método de potencias:
Valor propio dominante: 31.100431538922415
Vector propio asociado:
 [0.37236436 0.39032799 0.4781093  0.39637494 0.4250701  0.37762767]
Iteraciones realizadas: 7
Última variación relativa: 1.514374872335219e-08

Resultado numpy.linalg.eig:
Valor propio dominante (numpy): 31.1004315741679
Vector propio asociado (numpy):
 [-0.37235877 -0.39033903 -0.47812097 -0.39636415 -0.42507958 -0.37760765]


#5

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [16]:
#matrices de Pauli e identidad
sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)
sigma_z = np.array([[1, 0], [0, -1]], dtype=complex)
I = np.eye(2, dtype=complex)

#matriz hermitiana cualquiera
p = 3
q = -2
r = 1.5
s = 4

#construimos la matriz hermitiana
L = np.array([[p, q + 1j*r],
              [q - 1j*r, s]], dtype=complex)

print("Matriz hermitiana original L:")
print(L)

#Calcular los coeficientes a, b, c, d
a = q
b = r
c = (p - s) / 2
d = (p + s) / 2

print("\nCoeficientes encontrados:")
print(f"a = {a}, b = {b}, c = {c}, d = {d}")

#Reconstruir L usando la combinación lineal
L_reconstruida = a * sigma_x + b * sigma_y + c * sigma_z + d * I

print("\nMatriz reconstruida a partir de las matrices de Pauli:")
print(L_reconstruida)

# Verificar que ambas matrices sean iguales (dentro de tolerancia numérica)
if np.allclose(L, L_reconstruida):
    print("\nVerificación exitosa: La descomposición es correcta.")
else:
    print("\nError: La descomposición no es correcta.")

Matriz hermitiana original L:
[[ 3.+0.j  -2.+1.5j]
 [-2.-1.5j  4.+0.j ]]

Coeficientes encontrados:
a = -2, b = 1.5, c = -0.5, d = 3.5

Matriz reconstruida a partir de las matrices de Pauli:
[[ 3.+0.j  -2.-1.5j]
 [-2.+1.5j  4.+0.j ]]

Error: La descomposición no es correcta.


# 6

Haga un breve resumen en Markdown de las funciones y métodos más relevantes para algebra lineal usando Python. Emplee ejemplos.

In [18]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Suma y resta
C = A + B
D = A - B

print("Matriz A:\n", A)
print("Matriz B:\n", B)
print("Suma A + B:\n", C)
print("Resta A - B:\n", D)

# Multiplicación de matrices
E = np.dot(A, B)
print("Multiplicación A * B:\n", E)

# Transpuesta
F = A.T
print("Transpuesta de A:\n", F)

# Determinante y traza
det_A = np.linalg.det(A)
trace_A = np.trace(A)
print("Determinante de A:", det_A)
print("Traza de A:", trace_A)

# Inversa
inv_A = np.linalg.inv(A)
print("Inversa de A:\n", inv_A)

# Solución Ax = b
b = np.array([5, 11])
x = np.linalg.solve(A, b)
print("Solución de A * x = b donde b = [5,11]:\n", x)

# Eigenvalores y eigenvectores
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalores de A:\n", eigvals)
print("Eigenvectores de A:\n", eigvecs)

# Producto vectorial y escalar
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

dot = np.dot(v, w)
cross = np.cross(v, w)

print("Producto escalar de v y w:", dot)
print("Producto vectorial de v y w:\n", cross)



Matriz A:
 [[1 2]
 [3 4]]
Matriz B:
 [[5 6]
 [7 8]]
Suma A + B:
 [[ 6  8]
 [10 12]]
Resta A - B:
 [[-4 -4]
 [-4 -4]]
Multiplicación A * B:
 [[19 22]
 [43 50]]
Transpuesta de A:
 [[1 3]
 [2 4]]
Determinante de A: -2.0000000000000004
Traza de A: 5
Inversa de A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Solución de A * x = b donde b = [5,11]:
 [1. 2.]
Eigenvalores de A:
 [-0.37228132  5.37228132]
Eigenvectores de A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Producto escalar de v y w: 32
Producto vectorial de v y w:
 [-3  6 -3]
