In [9]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Juan Jose Bustamante Guiral
*Métodos computacionales*

---

#1
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [9]:
A = np.array([[4, 5, 2],
              [6, 7, 3],
              [5, 6, 5]])

B = np.array([[2, 7, 4],
              [2, 6, 5],
              [1, 3, 8]])

C = np.array([[6, 0, 8],
              [8, 9, 5],
              [6, 2, 2]])

c = 8
AB = A @ B
BA = B @ A
print('AB ≠ BA:')
print(f'Son iguales: {np.array_equal(AB, BA)}')


# (AB)C = A(BC)
ABC1 = (A @ B) @ C
ABC2 = A @ (B @ C)
print(f'(AB)C = A(BC): {np.allclose(ABC1, ABC2)}')


# A(B + C) = AB + AC
izq = A @ (B + C)
der = A @ B + A @ C
print(f'A(B + C) = AB + AC: {np.allclose(izq, der)}')


# (A + B)C = AC + BC
izq = (A + B) @ C
der = A @ C + B @ C
print(f'(A + B)C = AC + BC {np.allclose(izq, der)}')


# (AB)^T = B^T A^T
izq = (A @ B).T
der = B.T @ A.T
print(f'(AB)^T = B^T A^T: {np.allclose(izq, der)}')


# det(AB) = det(A) * det(B)
det_AB = np.linalg.det(A @ B)
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
print(f'det(AB) = det(A) * det(B): {np.isclose(det_AB, det_A * det_B)}')


# (A^T)^T = A
print(f'(A^T)^T = A: {np.allclose(A.T.T, A)}')


# (cA)^T = cA^T
print(f'(cA)^T = cA^T: {np.allclose((c * A).T, c * A.T)}')


# (A + B)^T = A^T + B^T
print(f'(A + B)^T = A^T + B^T: {np.allclose((A + B).T, A.T + B.T)}')

AB ≠ BA:
Son iguales: False
(AB)C = A(BC): True
A(B + C) = AB + AC: True
(A + B)C = AC + BC True
(AB)^T = B^T A^T: True
det(AB) = det(A) * det(B): True
(A^T)^T = A: True
(cA)^T = cA^T: True
(A + B)^T = A^T + B^T: True


#2

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [7]:
def determinante_laplace(matriz):
    matriz = np.array(matriz)

    if matriz.shape[0] != matriz.shape[1]:
        raise ValueError('La matriz debe ser cuadrada')

    n = matriz.shape[0]

    if n == 1:
        return matriz[0, 0]


    if n == 2:
        return matriz[0, 0]*matriz[1, 1] - matriz[0, 1]*matriz[1, 0]


    det = 0
    for j in range(n):
        signo = (-1) ** (1 + (j + 1))
        submatriz = np.delete(np.delete(matriz, 0, axis=0), j, axis=1)
        cofactor = signo * matriz[0, j] * determinante_laplace(submatriz)
        det += cofactor

    return det

In [10]:
L = ([[4, 5, 2],
    [6, 7, 3],
    [5, 6, 5]])

determinante_laplace(L)


np.int64(-5)

In [16]:
det_L = np.linalg.det(L)
det_L

np.float64(-5.000000000000008)

#3 Método de Gauss - Seidel

Sea \$A\in\mathbb{R}^{n\times n}\$ no singular y sea \$b\in\mathbb{R}^n\$.
Descomponga \$A\$ como

$$
A \;=\; D \;+\; L \;+\; U,
$$

donde

* \$D\$ es la matriz diagonal de \$A\$,
* \$L\$ es la parte estrictamente triangular inferior,
* \$U\$ es la parte estrictamente triangular superior.

El algoritmo de Gauss - Seidel reorganiza el sistema \$Ax=b\$ como

$$
x \;=\; (D+L)^{-1}\bigl(b \;-\; Ux\bigr),
$$

y genera la sucesión

$$
x_i^{(k+1)}
= \frac{1}{a_{ii}}
\Bigl(b_i - \sum_{j<i} a_{ij}\,x_j^{(k+1)} - \sum_{j>i} a_{ij}\,x_j^{(k)}\Bigr),
\qquad i=1,\dots,n.
$$

Implemente una función `gauss_seidel(A, b, tol=1e-7, max_iter=100)` que:
   * Realice las iteraciones hasta que
     $\lVert x^{(k+1)}-x^{(k)}\rVert_\infty<\text{tol}$
     o se alcance `max_iter`;
   * devuelva el vector solución aproximado \$x\$, el número de iteraciones realizadas y la norma del último residuo.

Incluya una documentación clara.

Luego,

   * Genere una matriz aleatoria \$5\times5\$ (por ejemplo, con `np.random.rand`) y un vector \$b\$ aleatorio.
   * Resuelva \$Ax=b\$ con su función; calcule el error relativo frente a `numpy.linalg.solve`.
   * Estime igualmente el error respecto a la solución obtenida mediante \$x=A^{-1}b\$ (usando `numpy.linalg.inv`).
   * Presente las normas de los residuos y los errores relativos.

In [4]:
def gauss_seidel(A, b, tol=1e-7, max_iter=100):
    '''
    Resuelve el sistema Ax = b mediante el método de Gauss-Seidel.

    Entrada:
        A: matriz cuadrada no singular de tamaño n x n
        b: vector columna de tamaño n

  Retorna:
        x: solución
        iteraciones (int): número de iteraciones realizadas
        residuo (float): norma infinito del último residuo
    '''
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float).flatten()
    n = A.shape[0]
    x = np.zeros_like(b)
    x_copia = np.copy(x)

    for k in range(max_iter):
        for i in range(n):
            suma1 = sum(A[i, j] * x_copia[j] for j in range(i))
            suma2 = sum(A[i, j] * x[j] for j in range(i + 1, n))
            x_copia[i] = (1 / A[i, i]) * (b[i] - suma1 - suma2)

        if np.linalg.norm(x_copia - x, ord=np.inf) < tol:
            break
        x = np.copy(x_copia)

    residuo = np.linalg.norm(b - A @ x_copia, ord=np.inf)
    return x_copia, k + 1, residuo

#4 Método de potencias para el valor propio dominante

Sea \$A\in\mathbb{R}^{n\times n}\$ diagonalizable con valor propio dominante \$\lambda\_{\max}\$ (en magnitud) y vector propio asociado \$v\_{\max}\$.

El método de potencias genera, a partir de un vector inicial \$q^{(0)}\neq 0\$, la sucesión

$$
q^{(k+1)} \;=\; \frac{A\,q^{(k)}}{\lVert A\,q^{(k)}\rVert_2},
\qquad
\lambda^{(k+1)} \;=\; (q^{(k+1)})^{\!\top} A\, q^{(k+1)},
$$

que converge a \$v\_{\max}/\lVert v\_{\max}\rVert\_2\$ y a \$\lambda\_{\max}\$ respectivamente, bajo hipótesis estándar.

Implemente `power_method(A, tol=1e-7, max_iter=1000)` que:

   * Acepte matrices reales cuadradas,
   * Devuelva \$\lambda\_{\max}\$, el vector propio normalizado \$v\_{\max}\$, el número de iteraciones y la última variación relativa de \$\lambda\$,
   * detenga la iteración cuando
     $\bigl|\lambda^{(k+1)}-\lambda^{(k)}\bigr|<\text{tol}\,|\lambda^{(k+1)}|$
     o se alcance `max_iter`.

Luego,
   * Genere una matriz simétrica aleatoria \$6\times6\$ (por ejemplo, \$A = (M+M^\top)/2\$ con \$M\$ aleatoria).
   * Aplique su `power_method` y compare \$\lambda\_{\max}\$ y \$v\_{\max}\$ con los resultados de `numpy.linalg.eig`.

In [5]:
def power_method(A, tol=1e-7, max_iter=1000):
    '''
    Método de potencias

    Entrada:
        A: matriz cuadrada real (n x n)

    Retorna:
        lambda_max: valor propio
        v_max: vector propio normalizado
    '''
    A = np.array(A, dtype=float)
    n = A.shape[0]

    q = np.random.rand(n)
    q = q / np.linalg.norm(q)

    lambda_0 = 0

    for k in range(1, max_iter + 1):
        z = A @ q
        q = z / np.linalg.norm(z)
        lambda_nuevo = q @ A @ q

        # Criterio de convergencia
        rel_diff = abs(lambda_nuevo - lambda_0) / abs(lambda_nuevo)

        if rel_diff < tol:
            break

        lambda_0 = lambda_nuevo

    return lambda_nuevo, q, k, rel_diff

In [11]:
power_method(L)

(np.float64(14.216775863506818),
 array([0.43407369, 0.62898917, 0.64494392]),
 8,
 np.float64(2.4122989324317236e-08))

#5

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [17]:
sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)
sigma_z = np.array([[1, 0], [0, -1]], dtype=complex)
I = np.eye(2, dtype=complex)



p, q = np.random.rand(2)
u, v = np.random.rand(2)
L = np.array([[p, u + 1j*v],
              [u - 1j*v, q]], dtype=complex)


a = 0.5 * np.trace(L @ sigma_x).real
b = 0.5 * np.trace(L @ sigma_y).real
c = 0.5 * np.trace(L @ sigma_z).real
d = 0.5 * np.trace(L @ I).real


L_nueva = a*sigma_x + b*sigma_y + c*sigma_z + d*I


print('Matriz original L:')
print(np.round(L, 4))

print('Coeficientes:')
print(f'a = {a:.4f}, b = {b:.4f}, c = {c:.4f}, d = {d:.4f}')

print('Matriz Nueva L')
print(np.round(L_nueva, 4))


diff_norm = np.linalg.norm(L - L_nueva)
print(f'Error absoluto: {diff_norm:.2e}')


Matriz original L:
[[0.9158+0.j     0.1061+0.6268j]
 [0.1061-0.6268j 0.6399+0.j    ]]
Coeficientes:
a = 0.1061, b = -0.6268, c = 0.1380, d = 0.7778
Matriz Nueva L
[[0.9158+0.j     0.1061+0.6268j]
 [0.1061-0.6268j 0.6399+0.j    ]]
Error absoluto: 0.00e+00


# 6

Haga un breve resumen en Markdown de las funciones y métodos más relevantes para algebra lineal usando Python. Emplee ejemplos.

In [21]:
print('1. Crear vectores y matrices')
v = np.array([1, 2, 3])         # Vector fila
A = np.array([[1, 2], [3, 4]])  # Matriz 2x2
print(f'Vector v: {v}')
print(f'Matriz A:\n {A}')

print('\n2. Suma y resta de matrices')
B = np.array([[5, 6], [7, 8]])
print(f'Matriz B:\n {B}')
print(f'A + B =\n {A + B}')
print(f'A - B =\n {A - B}')

print('\n3. Multiplicación de matrices')
C = np.dot(A, B)  # o A @ B
print(f'A * B =\ {C}')

print('\n4. Producto matriz por vector')
v2 = np.array([1, 2])
resultado = np.dot(A, v2)
print(f'A * v2 = {resultado}')

print('\n 5. Transpuesta de una matriz')
print(f'A^T =\n {A.T}')

print('\n6. Inversa de una matriz')
A_inv = np.linalg.inv(A)
print(f'A = {A}\n A⁻¹ = {A_inv}')

print('\n 7. Determinante de una matriz')
det_A = np.linalg.det(A)
print(f'det(A) = {det_A:3f}')

print('\n8. Autovalores y autovectores')
valores, vectores = np.linalg.eig(A)
print(f'Autovalores: {valores}')
print(f'Autovectores (columnas):\n {vectores}')

print('\n 9. Resolver sistema de ecuaciones Ax = b')
A_ejem = np.array([[2, 1], [1, 3]])
b = np.array([8, 13])
x = np.linalg.solve(A_ejem, b)
print(f'Solución x: {x}')

print('\n10. Norma de un vector')
vec = np.array([3, 4])
norma = np.linalg.norm(vec)
print(f'Norma de [3, 4] = {norma}')


1. Crear vectores y matrices
Vector v: [1 2 3]
Matriz A:
 [[1 2]
 [3 4]]

2. Suma y resta de matrices
Matriz B:
 [[5 6]
 [7 8]]
A + B =
 [[ 6  8]
 [10 12]]
A - B =
 [[-4 -4]
 [-4 -4]]

3. Multiplicación de matrices
A * B =\ [[19 22]
 [43 50]]

4. Producto matriz por vector
A * v2 = [ 5 11]

 5. Transpuesta de una matriz
A^T =
 [[1 3]
 [2 4]]

6. Inversa de una matriz
A = [[1 2]
 [3 4]]
 A⁻¹ = [[-2.   1. ]
 [ 1.5 -0.5]]

 7. Determinante de una matriz
det(A) = -2.000000

8. Autovalores y autovectores
Autovalores: [-0.37228132  5.37228132]
Autovectores (columnas):
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

 9. Resolver sistema de ecuaciones Ax = b
Solución x: [2.2 3.6]

10. Norma de un vector
Norma de [3, 4] = 5.0
