In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Laura Sofía Sierra Sánchez
*Métodos computacionales*

---

#1
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [47]:
# Tres matrices aleatorias de 3x3
A = np.random.randint(0, 10, (3, 3))
B = np.random.randint(0, 10, (3, 3))
C = np.random.randint(0, 10, (3, 3))

# Para mostrar las matrices
print("Matriz A:")
print(A)
print("\nMatriz B:")
print(B)
print("\nMatriz C:")
print(C)

Matriz A:
[[0 7 0]
 [0 1 1]
 [5 6 4]]

Matriz B:
[[0 0 2]
 [1 4 9]
 [5 6 3]]

Matriz C:
[[6 7 0]
 [5 7 4]
 [3 1 5]]


In [48]:
# Demostración 1:
AB = A @ B
BA = B @ A
print("\n1. AB es diferente a BA (en general):")
print("AB =")
print(AB)
print("\nBA =")
print(BA)
print("\n¿AB == BA?", np.array_equal(AB, BA))
print("Se demuestra que AB es diferente que BA.")


1. AB es diferente a BA (en general):
AB =
[[ 7 28 63]
 [ 6 10 12]
 [26 48 76]]

BA =
[[10 12  8]
 [45 65 40]
 [15 59 18]]

¿AB == BA? False
Se demuestra que AB es diferente que BA.


In [49]:
# Demostración 2:
AB_C = (A @ B) @ C
A_BC = A @ (B @ C)
print("\n2. (AB)C = A(BC):")
print("(AB)C =")
print(AB_C)
print("\nA(BC) =")
print(A_BC)
print("\n¿(AB)C == A(BC)?", np.array_equal(AB_C, A_BC))
print("Se demuestra que (AB)C es igual a A(BC).")


2. (AB)C = A(BC):
(AB)C =
[[371 308 427]
 [122 124 100]
 [624 594 572]]

A(BC) =
[[371 308 427]
 [122 124 100]
 [624 594 572]]

¿(AB)C == A(BC)? True
Se demuestra que (AB)C es igual a A(BC).


In [50]:
# Demostración 3:
A_BmasC = A @ (B + C)
AB_mas_AC = (A @ B) + (A @ C)
print("\n3. A(B + C) = AB + AC:")
print("A(B + C) =")
print(A_BmasC)
print("\nAB + AC =")
print(AB_mas_AC)
print("\n¿A(B + C) == AB + AC?", np.array_equal(A_BmasC, AB_mas_AC))
print("Se demuestra que A(B + C) = AB + AC")


3. A(B + C) = AB + AC:
A(B + C) =
[[ 42  77  91]
 [ 14  18  21]
 [ 98 129 120]]

AB + AC =
[[ 42  77  91]
 [ 14  18  21]
 [ 98 129 120]]

¿A(B + C) == AB + AC? True
Se demuestra que A(B + C) = AB + AC


In [51]:
# Demostración 4:
AmasB_C = (A + B) @ C
AC_mas_BC = (A @ C) + (B @ C)
print("\n4. (A + B)C = AC + BC:")
print("(A + B)C =")
print(AmasB_C)
print("\nAC + BC =")
print(AC_mas_BC)
print("\n¿(A + B)C == AC + BC?", np.array_equal(AmasB_C, AC_mas_BC))
print("Se demuestra que (A + B)C = AC + BC.")


4. (A + B)C = AC + BC:
(A + B)C =
[[ 41  51  38]
 [ 61  52  70]
 [141 161  83]]

AC + BC =
[[ 41  51  38]
 [ 61  52  70]
 [141 161  83]]

¿(A + B)C == AC + BC? True
Se demuestra que (A + B)C = AC + BC.


In [52]:
# Demostración 5:
AB_transp = (A @ B).T
B_transp_A_transp = B.T @ A.T
print("\n5. (AB)ᵀ = BᵀAᵀ:")
print("(AB)ᵀ =")
print(AB_transp)
print("\nBᵀAᵀ =")
print(B_transp_A_transp)
print("\n¿(AB)ᵀ == BᵀAᵀ?", np.array_equal(AB_transp, B_transp_A_transp))
print("Se demuestra que (AB)ᵀ = BᵀAᵀ.")


5. (AB)ᵀ = BᵀAᵀ:
(AB)ᵀ =
[[ 7  6 26]
 [28 10 48]
 [63 12 76]]

BᵀAᵀ =
[[ 7  6 26]
 [28 10 48]
 [63 12 76]]

¿(AB)ᵀ == BᵀAᵀ? True
Se demuestra que (AB)ᵀ = BᵀAᵀ.


In [53]:
# Demostración 6:
det_A = la.det(A)
det_B = la.det(B)
det_AB = la.det(A @ B)
print("\n6. det(AB) = det(A)det(B):")
print(f"det(A) = {det_A}")
print(f"det(B) = {det_B:}")
print(f"det(AB) = {det_AB}")
print(f"det(A)*det(B) = {det_A * det_B}")
print("\n¿det(AB) == det(A)det(B)?", np.isclose(det_AB, det_A * det_B))
print("Se demuestra que det(AB) = det(A)det(B).")


6. det(AB) = det(A)det(B):
det(A) = 35.0
det(B) = -28.0
det(AB) = -980.0000000000007
det(A)*det(B) = -980.0

¿det(AB) == det(A)det(B)? True
Se demuestra que det(AB) = det(A)det(B).


In [54]:
# Demostración 7:
A_transp_transp = A.T.T
print("\n7. (Aᵀ)ᵀ = A:")
print("(Aᵀ)ᵀ =")
print(A_transp_transp)
print("\nA =")
print(A)
print("\n¿(Aᵀ)ᵀ == A?", np.array_equal(A_transp_transp, A))
print("Se demuestra que (Aᵀ)ᵀ = A.")


7. (Aᵀ)ᵀ = A:
(Aᵀ)ᵀ =
[[0 7 0]
 [0 1 1]
 [5 6 4]]

A =
[[0 7 0]
 [0 1 1]
 [5 6 4]]

¿(Aᵀ)ᵀ == A? True
Se demuestra que (Aᵀ)ᵀ = A.


In [55]:
# Demostración 8:
c = np.random.randint(1, 10)
cA_transp = (c * A).T
c_A_transp = c * A.T
print(f"\n8. (cA)ᵀ = cAᵀ (con c = {c}):")
print("(cA)ᵀ =")
print(cA_transp)
print("\ncAᵀ =")
print(c_A_transp)
print("\n¿(cA)ᵀ == cAᵀ?", np.array_equal(cA_transp, c_A_transp))
print("Se demuestra que (cA)ᵀ = cAᵀ.")


8. (cA)ᵀ = cAᵀ (con c = 6):
(cA)ᵀ =
[[ 0  0 30]
 [42  6 36]
 [ 0  6 24]]

cAᵀ =
[[ 0  0 30]
 [42  6 36]
 [ 0  6 24]]

¿(cA)ᵀ == cAᵀ? True
Se demuestra que (cA)ᵀ = cAᵀ.


In [56]:
# Demostración 9:
AmasB_transp = (A + B).T
A_transp_mas_B_transp = A.T + B.T
print("\n9. (A + B)ᵀ = Aᵀ + Bᵀ:")
print("(A + B)ᵀ =")
print(AmasB_transp)
print("\nAᵀ + Bᵀ =")
print(A_transp_mas_B_transp)
print("\n¿(A + B)ᵀ == Aᵀ + Bᵀ?", np.array_equal(AmasB_transp, A_transp_mas_B_transp))
print("Se demuestra que (A + B)ᵀ = Aᵀ + Bᵀ.")


9. (A + B)ᵀ = Aᵀ + Bᵀ:
(A + B)ᵀ =
[[ 0  1 10]
 [ 7  5 12]
 [ 2 10  7]]

Aᵀ + Bᵀ =
[[ 0  1 10]
 [ 7  5 12]
 [ 2 10  7]]

¿(A + B)ᵀ == Aᵀ + Bᵀ? True
Se demuestra que (A + B)ᵀ = Aᵀ + Bᵀ.


#2

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [58]:
def determinante_laplace(A):
  '''
  Calcula el determinante de una matriz cuadrada A usando el Teorema de Laplace.

  Entradas:
  - A : matriz cuadrada de tamaño nxn -> ndarray

  Retorna:
  - det: determinante de la matriz A -> float
  '''
  n = A.shape[0]

  # Si la matriz es de 1x1, el determinante es el único elemento.
  if n == 1:
      return A[0, 0]

  # Si es 2x2, usar la fórmula directa
  if n == 2:
      return A[0, 0]*A[1, 1] - A[0, 1]*A[1, 0]

  # Para matrices de orden mayor, usar Laplace en la primera fila
  det = 0
  for j in range(n):  # recorrer columnas de la primera fila
      signo = (-1) ** (0 + j)  # calcular el signo del cofactor
      # Crear la submatriz (menor)
      submatriz = np.delete(np.delete(A, 0, axis=0), j, axis=1)  # se elimina la fila 0 y columna j-ésima
      det += signo * A[0, j] * determinante_laplace(submatriz)  # aplicar función
  return det

# Ejemplo
A = np.random.randint(1, 10, (3, 3))
print("Matriz A:\n", A)
print("Determinante -> Laplace:", determinante_laplace(A))
print("Determinante -> NumPy:", np.linalg.det(A))


Matriz A:
 [[4 7 4]
 [9 1 8]
 [7 2 8]]
Determinante -> Laplace: -100
Determinante -> NumPy: -100.00000000000004


#3 Método de Gauss - Seidel

Sea \$A\in\mathbb{R}^{n\times n}\$ no singular y sea \$b\in\mathbb{R}^n\$.
Descomponga \$A\$ como

$$
A \;=\; D \;+\; L \;+\; U,
$$

donde

* \$D\$ es la matriz diagonal de \$A\$,
* \$L\$ es la parte estrictamente triangular inferior,
* \$U\$ es la parte estrictamente triangular superior.

El algoritmo de Gauss - Seidel reorganiza el sistema \$Ax=b\$ como

$$
x \;=\; (D+L)^{-1}\bigl(b \;-\; Ux\bigr),
$$

y genera la sucesión

$$
x_i^{(k+1)}
= \frac{1}{a_{ii}}
\Bigl(b_i - \sum_{j<i} a_{ij}\,x_j^{(k+1)} - \sum_{j>i} a_{ij}\,x_j^{(k)}\Bigr),
\qquad i=1,\dots,n.
$$

Implemente una función `gauss_seidel(A, b, tol=1e-7, max_iter=100)` que:
   * Realice las iteraciones hasta que
     $\lVert x^{(k+1)}-x^{(k)}\rVert_\infty<\text{tol}$
     o se alcance `max_iter`;
   * devuelva el vector solución aproximado \$x\$, el número de iteraciones realizadas y la norma del último residuo.

Incluya una documentación clara.

Luego,

   * Genere una matriz aleatoria \$5\times5\$ (por ejemplo, con `np.random.rand`) y un vector \$b\$ aleatorio.
   * Resuelva \$Ax=b\$ con su función; calcule el error relativo frente a `numpy.linalg.solve`.
   * Estime igualmente el error respecto a la solución obtenida mediante \$x=A^{-1}b\$ (usando `numpy.linalg.inv`).
   * Presente las normas de los residuos y los errores relativos.

In [60]:
def gauss_seidel(A, b, tol=1e-7, max_iter=1000):
  '''
  Resuelve el sistema Ax = b usando el método de Gauss-Seidel.

  Entradas:
  - A : matriz cuadrada de tamaño nxn -> ndarray
  - b : vector columna de la matruz A -> ndarray
  - tol : tolerancia para la convergencia.
  - max_iter : número máximo de iteraciones.

  Retorna:
  - x : vector solución aprox. -> ndarray
  - iter : número de iteraciones realizadas.
  - residuo : norma infinita del residuo final.
  '''
  n = len(b)
  x = np.zeros_like(b, dtype=float) # Inicializar con ceros

  for iter in range(1, max_iter + 1):
      x_old = x.copy() # Guardar una copia de la solución actual

      # Calcular el nuevo valor de x[i] usando la fórmula de Gauss-Seidel
      for i in range(n):
          x[i] = (b[i] - np.dot(A[i, :i], x[:i]) - np.dot(A[i, i+1:], x_old[i+1:])) / A[i, i]

      if np.linalg.norm(x - x_old, ord=np.inf) < tol:
          break # Si alcanza la convergencia, se rompe el bucle

  residuo = np.linalg.norm(A @ x - b, ord=np.inf) # Calcular el residuo final
  return x, iter, residuo

# Generar matriz 5x5
A = np.random.rand(5, 5)
b = np.random.rand(5)

# Hacer la matriz diagonal dominante para garantizar convergencia
A = A + np.diag(np.sum(np.abs(A), axis=1) * 1.1)

print("Matriz A (5x5):")
print(np.around(A, 4))
print("\nVector b:")
print(np.around(b, 4))

# Resolver con Gauss-Seidel
x_gs, it_gs, res_gs = gauss_seidel(A, b)

# Resolver con numpy.linalg.solve (referencia)
x_ref = np.linalg.solve(A, b)

# Resolver con inversa (A^{-1}b)
x_inv = np.linalg.inv(A) @ b

# Cálculo de errores
error_gs = np.linalg.norm(x_gs - x_ref) / np.linalg.norm(x_ref)
error_inv = np.linalg.norm(x_inv - x_ref) / np.linalg.norm(x_ref)

# Cálculo de residuos
res_inv = np.linalg.norm(A @ x_inv - b, ord=np.inf)
res_ref = np.linalg.norm(A @ x_ref - b, ord=np.inf)

# Resultados
print("\nResultados:")
print(f"Número de iteraciones en Gauss-Seidel (para convergencia): {it_gs}")
print(f"Residuo (GS): {res_gs:.4e}")
print(f"Residuo (inv): {res_inv:.4e}")
print(f"Residuo (ref): {res_ref:.4e}")
print(f"\nError relativo GS vs. referencia: {error_gs:.4e}")
print(f"Error relativo inv vs. referencia: {error_inv:.4e}")

# Comparación de soluciones
print("\nSolución Gauss-Seidel:")
print(np.around(x_gs, 6))
print("\nSolución referencia (np.linalg.solve):")
print(np.around(x_ref, 6))
print("\nSolución con inversa (np.linalg.inv):")
print(np.around(x_inv, 6))

Matriz A (5x5):
[[2.6662 0.5487 0.6919 0.652  0.2243]
 [0.7122 3.1753 0.3254 0.7465 0.6496]
 [0.8492 0.6576 3.3585 0.0937 0.3677]
 [0.2652 0.244  0.973  3.4372 0.892 ]
 [0.6311 0.7948 0.5026 0.5769 3.7903]]

Vector b:
[0.1952 0.7225 0.2808 0.0243 0.6455]

Resultados:
Número de iteraciones en Gauss-Seidel (para convergencia): 10
Residuo (GS): 1.1493e-08
Residuo (inv): 1.1102e-16
Residuo (ref): 2.2204e-16

Error relativo GS vs. referencia: 2.2293e-08
Error relativo inv vs. referencia: 3.6489e-16

Solución Gauss-Seidel:
[ 0.026148  0.204734  0.024341 -0.049405  0.127301]

Solución referencia (np.linalg.solve):
[ 0.026148  0.204734  0.024341 -0.049405  0.127301]

Solución con inversa (np.linalg.inv):
[ 0.026148  0.204734  0.024341 -0.049405  0.127301]


#4 Método de potencias para el valor propio dominante

Sea \$A\in\mathbb{R}^{n\times n}\$ diagonalizable con valor propio dominante \$\lambda\_{\max}\$ (en magnitud) y vector propio asociado \$v\_{\max}\$.

El método de potencias genera, a partir de un vector inicial \$q^{(0)}\neq 0\$, la sucesión

$$
q^{(k+1)} \;=\; \frac{A\,q^{(k)}}{\lVert A\,q^{(k)}\rVert_2},
\qquad
\lambda^{(k+1)} \;=\; (q^{(k+1)})^{\!\top} A\, q^{(k+1)},
$$

que converge a \$v\_{\max}/\lVert v\_{\max}\rVert\_2\$ y a \$\lambda\_{\max}\$ respectivamente, bajo hipótesis estándar.

Implemente `power_method(A, tol=1e-7, max_iter=1000)` que:

   * Acepte matrices reales cuadradas,
   * Devuelva \$\lambda\_{\max}\$, el vector propio normalizado \$v\_{\max}\$, el número de iteraciones y la última variación relativa de \$\lambda\$,
   * detenga la iteración cuando
     $\bigl|\lambda^{(k+1)}-\lambda^{(k)}\bigr|<\text{tol}\,|\lambda^{(k+1)}|$
     o se alcance `max_iter`.

Luego,
   * Genere una matriz simétrica aleatoria \$6\times6\$ (por ejemplo, \$A = (M+M^\top)/2\$ con \$M\$ aleatoria).
   * Aplique su `power_method` y compare \$\lambda\_{\max}\$ y \$v\_{\max}\$ con los resultados de `numpy.linalg.eig`.

In [61]:
import numpy as np

def power_method(A, tol=1e-7, max_iter=1000):
  '''
  Método de potencias para encontrar el valor propio dominante y su vector propio asociado.

  Entradas:
  - A : matriz cuadrada de tamaño nxn -> ndarray
  - tol : tolerancia para la convergencia
  - max_iter : número máximo de iteraciones

  Retorna:
  - lambda_new : valor propio dominante estimado.
  - q : vector propio normalizado asociado al valor dominante.
  - max_iter : número de iteraciones realizadas (convergencia)
  - rel_error: variación relativa final entre los dos últimos valores propios.
  '''
  n = A.shape[0]
  if A.shape != (n, n):
      raise ValueError("La matriz debe ser cuadrada")
  # Vector propio inicial
  q = np.random.rand(n)
  q = q / np.linalg.norm(q)

  lambda_old = 0

  for k in range(1, max_iter + 1):
    z = A @ q # Obtener el nuevo vector z
    q = z / np.linalg.norm(z) # Normalizar el vector z
    lambda_new = q.T @ A @ q # Estimar el valor propio dominante
    rel_error = abs(lambda_new - lambda_old) / abs(lambda_new) # Variación relativa

    # Comprobar convergencia
    if rel_error < tol:
      return lambda_new, q, k, rel_error

    # Actualizar el valor propio
    lambda_old = lambda_new

  return lambda_new, q, max_iter, rel_error


# Matriz aleatoria 6x6
M = np.random.rand(6, 6)
A = (M + M.T) / 2  # Matriz simétrica

# Aplicar power_method
lambda_max_pm, v_max_pm, num_iter, rel_err = power_method(A)

# Comparar con valores propios reales
eigvals, eigvecs = np.linalg.eig(A)
idx_max = np.argmax(np.abs(eigvals))
lambda_max_np = eigvals[idx_max]
v_max_np = eigvecs[:, idx_max]
v_max_np = v_max_np / np.linalg.norm(v_max_np)

# Alinear el signo para que sean comparables
if np.dot(v_max_pm, v_max_np) < 0:
    v_max_np *= -1

# Resultados
print("Matriz simétrica A:\n", A)
print("\nMétodo de Potencias:")
print("Valor propio dominante:", lambda_max_pm)
print("Vector propio asociado:", v_max_pm)
print("Iteraciones:", num_iter)
print("Error relativo final:", rel_err)

print("\n Con NumPy:")
print("Valor propio dominante (real):", lambda_max_np)
print("Vector propio asociado:", v_max_np)

# Comparaciones
error_valprop = abs(lambda_max_pm - lambda_max_np)
error_vec = np.linalg.norm(v_max_pm - v_max_np)

print("\nComparación:")
print("Error absoluto en lambda_max:", error_valprop)
print("Distancia euclídea entre vectores propios:", error_vec)


Matriz simétrica A:
 [[0.17711068 0.93438857 0.66951315 0.80544709 0.44424418 0.15452423]
 [0.93438857 0.42818415 0.90889575 0.76684057 0.86519126 0.55190502]
 [0.66951315 0.90889575 0.31692201 0.13333462 0.64878494 0.87313408]
 [0.80544709 0.76684057 0.13333462 0.61500723 0.8435348  0.50357817]
 [0.44424418 0.86519126 0.64878494 0.8435348  0.70248408 0.63636585]
 [0.15452423 0.55190502 0.87313408 0.50357817 0.63636585 0.5113424 ]]

Método de Potencias:
Valor propio dominante: 3.756801811259077
Vector propio asociado: [0.3591081  0.47620321 0.38692748 0.40346917 0.45446844 0.35387861]
Iteraciones: 5
Error relativo final: 1.9663697936612574e-08

 Con NumPy:
Valor propio dominante (real): 3.7568018156578953
Vector propio asociado: [0.35912295 0.47621022 0.38690362 0.40346089 0.45447206 0.35388498]

Comparación:
Error absoluto en lambda_max: 4.3988181985810115e-09
Distancia euclídea entre vectores propios: 3.1004901413333885e-05


#5

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [63]:
# Matrices de Pauli
sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)
sigma_z = np.array([[1, 0], [0, -1]], dtype=complex)
I = np.eye(2, dtype=complex)

# Generar una matriz hermitiana aleatoria 2x2
alpha = np.random.rand()
delta = np.random.rand()
beta_real = np.random.rand()
beta_imag = np.random.rand()
beta = beta_real + 1j * beta_imag

L = np.array([[alpha, beta], [np.conj(beta), delta]], dtype=complex)

# Calcular los coeficientes reales correctos
a = 0.5 * (L[0, 1] + L[1, 0]).real      # parte real simétrica
b = -0.5 * (L[0, 1] - L[1, 0]).imag     # parte imaginaria antisimétrica
c = 0.5 * (L[0, 0] - L[1, 1]).real
d = 0.5 * (L[0, 0] + L[1, 1]).real

# Reconstruir L
L_reconstructed = a * sigma_x + b * sigma_y + c * sigma_z + d * I

# Verificar
print("Matriz hermitiana L original:\n", L)
print("\nCoeficientes reales:")
print("a =", a)
print("b =", b)
print("c =", c)
print("d =", d)

print("\nL reconstruida:\n", L_reconstructed)
print("\n¿Son iguales L y la reconstrucción?:", np.allclose(L, L_reconstructed))


Matriz hermitiana L original:
 [[0.4236548 +0.j       0.43758721+0.891773j]
 [0.43758721-0.891773j 0.64589411+0.j      ]]

Coeficientes reales:
a = 0.4375872112626925
b = -0.8917730007820798
c = -0.1111196568638757
d = 0.5347744562027804

L reconstruida:
 [[0.4236548 +0.j       0.43758721+0.891773j]
 [0.43758721-0.891773j 0.64589411+0.j      ]]

¿Son iguales L y la reconstrucción?: True


# 6

Haga un breve resumen en Markdown de las funciones y métodos más relevantes para algebra lineal usando Python. Emplee ejemplos.

En primer lugar, empezamos con lo más básico que es la creación de matrices con Numpy:

In [95]:
A = np.array([[3, 9], [2, 4],], dtype=float)
B = np.array([[1, 6], [8, 5]], dtype=float)
b = np.array([ 2, 3], dtype=float)

Para hacer el producto entre dos matrices, existen dos maneras de hacerlo:

In [96]:
f1 = np.dot(A, B)
f2 = A @ B
print("Forma 1:\n", f1)
print("------------")
print("Forma 2:\n", f2)

Forma 1:
 [[75. 63.]
 [34. 32.]]
------------
Forma 2:
 [[75. 63.]
 [34. 32.]]


Para hallar la transpuesta y la transpuesta conjugada de una matriz:

In [97]:
transp = A.T
conjugada = A.conj().T
print("Transpuesta:\n", transp)
print("------------")
print("Conjugada:\n", conjugada)

Transpuesta:
 [[3. 2.]
 [9. 4.]]
------------
Conjugada:
 [[3. 2.]
 [9. 4.]]


Para la identidad, ceros, y unos de una matriz:

In [98]:
np.eye(3)         # Matriz identidad 3x3
np.zeros((2, 3))  # Matriz de ceros 2x3
np.ones((2, 2))   # Matriz de unos 2x2

array([[1., 1.],
       [1., 1.]])

Normas de un vector:

In [99]:
z = np.linalg.norm(b)
print("Norma 2 de b:", z)

Norma 2 de b: 3.605551275463989


Para la colución rápida de sistemas de ecuaciones, se tiene:

In [100]:
x = la.solve(A, b)         # Resuelve Ax = b
print("Solución de Ax = b:\n", x)

Solución de Ax = b:
 [ 3.16666667 -0.83333333]


Para hallar el determinante de una matriz n x n:

In [101]:
la.det(A)

np.float64(-6.000000000000001)

Para hallar la inversa de una matriz:

In [102]:
la.inv(A)

array([[-0.66666667,  1.5       ],
       [ 0.33333333, -0.5       ]])

## Métodos

Funciones para resolver sistemas de ecuacuiones lineales:

### Regla de Cramer:

In [103]:
def Cramer(A, b):
  '''
  Resuelve un sistema de ecuaciones lineales Ax = b usando el método de Cramer.
  Parámetros:
  A : ndarray
      Matriz de coeficientes del sistema.
  b : ndarray
      Vector de términos independientes.
  Retorna:
  x : ndarray
      Vector de soluciones del sistema.
  '''
  # Calcular el determinante de A
  det_A = la.det(A)

  # Verificar si el determinante es cero o si las dimensiones no coinciden
  if np.isclose(det_A, 0):
      raise ValueError("El sistema no tiene solución única (determinante es cero).")
  if A.shape[0] != b.shape[0]:
      raise ValueError("Las dimensiones de A y b no coinciden.")
  # Calcular las soluciones usando el método de Cramer
  n = A.shape[1]
  # Inicializar el vector de soluciones
  x = np.zeros(n)
  for i in range(n):
      # Crear una copia de A y reemplazar la columna i por b
      Ai = A.copy()
      Ai[:, i] = b
      # Calcular la solución para la variable i
      x[i] = la.det(Ai) / det_A
  return x #  Retornar el vector de soluciones


sol = Cramer(A, b)
sol

array([ 3.16666667, -0.83333333])

### Eliminación de Guss simple

In [104]:
def Eliminacion_Gauss(A, b):
  '''
  Resuelve un sistema de ecuaciones lineales Ax = b usando eliminación de Gauss.
  Parámetros:
  A : ndarray
      Matriz de coeficientes del sistema.
  b : ndarray
      Vector de términos independientes.
  Retorna:
  x : ndarray
      Vector de soluciones del sistema.
  A_aumentada : ndarray
      Matriz aumentada después de aplicar eliminación de Gauss.
  '''
  # Crear la matriz aumentada
  A_aumentada = np.column_stack((A, b))

  # Aplicar eliminación de Gauss
  n = A.shape[0]

  for i in range(n):
      # Hacer el pivote en la fila i
      for j in range(i + 1, n):
          if A_aumentada[j, i] != 0:
              # Calcular el factor de eliminación
              factor = A_aumentada[j, i] / A_aumentada[i, i]
              # Restar la fila i multiplicada por el factor de eliminación de la fila j
              A_aumentada[j, :] -= factor * A_aumentada[i, :]

  # Sustitución hacia atrás para encontrar las soluciones
  x = np.zeros(n)
  for i in range(n - 1, -1, -1):
      x[i] = (A_aumentada[i, -1] - np.dot(A_aumentada[i, i + 1:n], x[i + 1:n])) / A_aumentada[i, i]
  return x, A_aumentada  # Retornar el vector de soluciones y la matriz aumentada con eliminación de Gauss


sol, matriz = Eliminacion_Gauss(A, b)
print(f'La solución es: {sol}')
print(f'La matriz aumentada es: \n{matriz}')

La solución es: [ 3.16666667 -0.83333333]
La matriz aumentada es: 
[[ 3.          9.          2.        ]
 [ 0.         -2.          1.66666667]]


### Método de pivoteo parcial por eliminación Gaussiana

In [105]:
def Eliminacion_Gauss_Pivote_Simple(A, b):
  '''
  Resuelve un sistema de ecuaciones lineales Ax = b usando eliminación de Gauss con un único pivoteo inicial.

  Parámetros:
  A : ndarray
      Matriz de coeficientes del sistema.
  b : ndarray
      Vector de términos independientes.

  Retorna:
  x : ndarray
      Vector de soluciones del sistema.
  A_aumentada : ndarray
      Matriz aumentada después de aplicar eliminación de Gauss con pivoteo inicial.
  '''
  # Crear la matriz aumentada
  A_aumentada = np.column_stack((A, b))

  n = A.shape[0]

  # Encontrar el índice del máximo en la primera columna (columna 0)
  max_index = np.argmax(np.abs(A_aumentada[0:n, 0]))

  if max_index != 0:
      # Intercambiar la fila 0 con la fila que tiene el elemento más grande
      A_aumentada[[0, max_index], :] = A_aumentada[[max_index, 0], :]

  # Fase de Eliminación hacia adelante
  for i in range(n):
      # Hacer ceros debajo del pivote
      for j in range(i + 1, n):
          if A_aumentada[j, i] != 0: # Solo si el elemento a eliminar no es ya cero
              factor = A_aumentada[j, i] / A_aumentada[i, i]
              A_aumentada[j, :] -= factor * A_aumentada[i, :]

  # Sustitución hacia atrás para encontrar las soluciones
  x = np.zeros(n)
  for i in range(n - 1, -1, -1):
      # Asegurarse de que el pivote diagonal no sea cero para la división
      if A_aumentada[i, i] == 0:
          raise ValueError(f"El elemento pivote diagonal A[{i},{i}] es cero durante la sustitución hacia atrás. El sistema puede no tener solución única.")

      x[i] = (A_aumentada[i, -1] - np.dot(A_aumentada[i, i + 1:n], x[i + 1:n])) / A_aumentada[i, i]

  return x, A_aumentada


sol, matriz_pivote = Eliminacion_Gauss_Pivote_Simple(A, b)
print("Solución usando Eliminación de Gauss con Pivoteo Simple:", sol)
print("Matriz aumentada después de la eliminación de Gauss con pivoteo:")
print(matriz_pivote)

Solución usando Eliminación de Gauss con Pivoteo Simple: [ 3.16666667 -0.83333333]
Matriz aumentada después de la eliminación de Gauss con pivoteo:
[[ 3.          9.          2.        ]
 [ 0.         -2.          1.66666667]]
