In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Ana Sofia Del Rio
*Métodos computacionales*

---

#1
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [2]:
np.random.seed(0)
A = np.random.rand(3,3)
B = np.random.rand(3,3)
C = np.random.rand(3,3)
c = np.random.rand()
#Punto 1
print('-AB≠BA')
AB =np.dot(A,B)
BA =np.dot(B,A)

if np.isclose(AB,BA).all():
  print('False')
else:
  print('True')

#Punto 2
print('-(AB)C = A(BC)')
ABxC = np.dot(np.dot(A,B),C)
AxBC = np.dot(A,np.dot(B,C))

print(np.isclose(ABxC,AxBC).all())

# Punto 3
print('- A(B + C) = AB + AC')
AxBplusC = np.dot(A, B + C)
AxBplusAxC = np.dot(A, B) + np.dot(A, C)
print(np.isclose(AxBplusC , AxBplusAxC).all())

# Punto 4
print('- (A + B)C = AC + BC')
AplusBxC = np.dot(A + B, C)
AxCplusBxC = np.dot(A, C) + np.dot(B, C)
print(np.isclose(AplusBxC, AxCplusBxC).all())

# Punto 5
print('- (AB)^T = B^T A^T')
AB_T = np.transpose(np.dot(A, B))
B_TxA_T = np.dot(np.transpose(B), np.transpose(A))
print(np.isclose(AB_T, B_TxA_T).all())

# Punto 6
print('- det(AB) = det(A) * det(B)')
det_AB = np.linalg.det(np.dot(A, B))
det_A_x_det_B = np.linalg.det(A) * np.linalg.det(B)
print(np.isclose(det_AB, det_A_x_det_B))

# Punto 7
print('- (A^T)^T = A')
print(np.isclose(np.transpose(np.transpose(A)), A).all())

# Punto 8
print('- (cA)^T = cA^T')
cA_T = np.transpose(c * A)
c_AT = c * np.transpose(A)
print(np.isclose(cA_T, c_AT).all())

# Punto 9
print('- (A + B)^T = A^T + B^T')
AplusB_T = np.transpose(A + B)
AT_plus_BT = np.transpose(A) + np.transpose(B)
print(np.isclose(AplusB_T, AT_plus_BT).all())

-AB≠BA
True
-(AB)C = A(BC)
True
- A(B + C) = AB + AC
True
- (A + B)C = AC + BC
True
- (AB)^T = B^T A^T
True
- det(AB) = det(A) * det(B)
True
- (A^T)^T = A
True
- (cA)^T = cA^T
True
- (A + B)^T = A^T + B^T
True


#2

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [3]:
def det(A):
    n = A.shape[0]
    #Si A es una matriz 1x1
    if n == 1:
        return A[0, 0]
    #Si A es 2x2
    if n == 2:
        return A[0,0]*A[1,1] - A[0,1]*A[1,0]

    determinante = 0
    for j in range(n):
        #Creamos otra matriz menor (eliminando fila 0 y columna j)
        B= np.delete(np.delete(A, 0, axis=0), j, axis=1)
        cofactor = (-1) ** (1 + (j + 1))  #porque filas y columnas comienzan desde 1
        determinante += cofactor * A[0, j] * det(B)
    return determinante


np.random.seed(0)
M = np.random.rand(3, 3)
print('Matriz:')
print(M)

print(f'Determinante por Laplace:, {det(M)}')
print(f'Determinante con numpy:, {(np.linalg.det(M))}')

Matriz:
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]
Determinante por Laplace:, -0.08430330697685007
Determinante con numpy:, -0.08430330697685008


#3 Método de Gauss - Seidel

Sea \$A\in\mathbb{R}^{n\times n}\$ no singular y sea \$b\in\mathbb{R}^n\$.
Descomponga \$A\$ como

$$
A \;=\; D \;+\; L \;+\; U,
$$

donde

* \$D\$ es la matriz diagonal de \$A\$,
* \$L\$ es la parte estrictamente triangular inferior,
* \$U\$ es la parte estrictamente triangular superior.

El algoritmo de Gauss - Seidel reorganiza el sistema \$Ax=b\$ como

$$
x \;=\; (D+L)^{-1}\bigl(b \;-\; Ux\bigr),
$$

y genera la sucesión

$$
x_i^{(k+1)}
= \frac{1}{a_{ii}}
\Bigl(b_i - \sum_{j<i} a_{ij}\,x_j^{(k+1)} - \sum_{j>i} a_{ij}\,x_j^{(k)}\Bigr),
\qquad i=1,\dots,n.
$$

Implemente una función `gauss_seidel(A, b, tol=1e-7, max_iter=100)` que:
   * Realice las iteraciones hasta que
     $\lVert x^{(k+1)}-x^{(k)}\rVert_\infty<\text{tol}$
     o se alcance `max_iter`;
   * devuelva el vector solución aproximado \$x\$, el número de iteraciones realizadas y la norma del último residuo.

Incluya una documentación clara.

Luego,

   * Genere una matriz aleatoria \$5\times5\$ (por ejemplo, con `np.random.rand`) y un vector \$b\$ aleatorio.
   * Resuelva \$Ax=b\$ con su función; calcule el error relativo frente a `numpy.linalg.solve`.
   * Estime igualmente el error respecto a la solución obtenida mediante \$x=A^{-1}b\$ (usando `numpy.linalg.inv`).
   * Presente las normas de los residuos y los errores relativos.

In [4]:
def Gauss_Seidel(A, b, tol=1e-7, max_iter=100):
    """
    Resuelve el sistema lineal Ax = b usando el método iterativo de Gauss-Seidel.

    Parámetros:
    A : ndarray (n x n)
        Matriz de coeficientes.
    b : ndarray (n)
        Vector de términos independientes.
    tol : float
        Tolerancia para la convergencia (norma infinito del cambio en x).
    max_iter : int
        Número máximo de iteraciones permitidas.

    Retorna:
    x : ndarray
        Aproximación del vector solución.
    iter_count : int
        Número de iteraciones realizadas.
    residuo_norm : float
        Norma infinito del último residuo
    """
    n = len(b)
    x = np.zeros_like(b, dtype=float)
    iter_count = 0

    for _ in range(max_iter):
        x_old = np.copy(x)

        for i in range(n):
            suma1 = sum(A[i, j] * x[j] for j in range(i))       #Usa valores actualizados
            suma2 = sum(A[i, j] * x_old[j] for j in range(i + 1, n))  #Usa valores antiguos
            x[i] = (b[i] - suma1 - suma2) / A[i, i]

        # Verificamos convergencia con norma infinito
        error = np.linalg.norm(x - x_old, ord=np.inf)
        if error < tol:
            break
        iter_count += 1

    residuo = b - A @ x
    residuo_norm = np.linalg.norm(residuo, ord=np.inf)

    return x, iter_count + 1, residuo_norm

In [5]:
np.random.seed(0)
A = np.random.rand(5, 5)
b = np.random.rand(5)
#Solución con la función de Gauss-Seidel
x, iter_count, residuo_norm = Gauss_Seidel(A, b)
#Solución con numpy.linalg.solve
x_solve = np.linalg.solve(A, b)
#Solución con la inversa
x_inv = np.linalg.inv(A) @ b
#Errores relativos
error_relativo_solve = np.linalg.norm(x - x_solve, ord=np.inf) / np.linalg.norm(x_solve, ord=np.inf)
error_relativo_inv = np.linalg.norm(x - x_inv, ord=np.inf) / np.linalg.norm(x_inv, ord=np.inf)
#Residuo de la solución con solve y con inversa
residuo_solve = b - A @ x_solve
residuo_inv = b - A @ x_inv
residuo_norm_solve = np.linalg.norm(residuo_solve, ord=np.inf)
residuo_norm_inv = np.linalg.norm(residuo_inv, ord=np.inf)
#Resultados
print(f'-Error relativo con solve: {error_relativo_solve}')
print(f'-Error relativo con inversa: {error_relativo_inv}')
print(f'-Norma del residuo con solve: {residuo_norm_solve}')
print(f'-Norma del residuo con inversa: {residuo_norm_inv}')

-Error relativo con solve: 7.263635606562689e+108
-Error relativo con inversa: 7.263635606562685e+108
-Norma del residuo con solve: 1.915134717478395e-15
-Norma del residuo con inversa: 1.6653345369377348e-15


#4 Método de potencias para el valor propio dominante

Sea \$A\in\mathbb{R}^{n\times n}\$ diagonalizable con valor propio dominante \$\lambda\_{\max}\$ (en magnitud) y vector propio asociado \$v\_{\max}\$.

El método de potencias genera, a partir de un vector inicial \$q^{(0)}\neq 0\$, la sucesión

$$
q^{(k+1)} \;=\; \frac{A\,q^{(k)}}{\lVert A\,q^{(k)}\rVert_2},
\qquad
\lambda^{(k+1)} \;=\; (q^{(k+1)})^{\!\top} A\, q^{(k+1)},
$$

que converge a \$v\_{\max}/\lVert v\_{\max}\rVert\_2\$ y a \$\lambda\_{\max}\$ respectivamente, bajo hipótesis estándar.

Implemente `power_method(A, tol=1e-7, max_iter=1000)` que:

   * Acepte matrices reales cuadradas,
   * Devuelva \$\lambda\_{\max}\$, el vector propio normalizado \$v\_{\max}\$, el número de iteraciones y la última variación relativa de \$\lambda\$,
   * detenga la iteración cuando
     $\bigl|\lambda^{(k+1)}-\lambda^{(k)}\bigr|<\text{tol}\,|\lambda^{(k+1)}|$
     o se alcance `max_iter`.

Luego,
   * Genere una matriz simétrica aleatoria \$6\times6\$ (por ejemplo, \$A = (M+M^\top)/2\$ con \$M\$ aleatoria).
   * Aplique su `power_method` y compare \$\lambda\_{\max}\$ y \$v\_{\max}\$ con los resultados de `numpy.linalg.eig`.

In [12]:
def power_method(A, tol=1e-7, max_iter=1000):
    #Verificar que la matriz sea cuadrada
    n, m = A.shape
    if n != m:
        raise ValueError('La matriz no es cuadrada')
    q = np.random.rand(n) #Vector inicial aleatorio
    q = q / np.linalg.norm(q)

    lambda_ = 0
    for i in range(max_iter):
        z = A @ q #Multiplicamos por A
        q = z / np.linalg.norm(z) #Normalizamos
        lambda_nuevo = q.T @ A @ q #Calculamos el nuevo valor de lambda
        v_relativa = abs(lambda_nuevo - lambda_)
        if v_relativa < tol:
            return lambda_nuevo, q, i+1, v_relativa

        lambda_ = lambda_nuevo

    return lambda_nuevo, q, max_iter, v_relativa

#Generamps una matriz simétrica aleatoria 6x6
np.random.seed(42)
M = np.random.rand(6, 6)
A = (M + M.T) / 2

#Aplicar método de potencias
lambda_1, v1, i, v_r = power_method(A)
print('Método de potencias:')
print(f'λ_max ≈ {lambda_1}')
print(f'v_max ≈ {v1}')
print(f'Iteraciones: {i}')
print(f'Variación final: {v_r}')

#Comparar con numpy.linalg.eig
lambda_2, v2 = np.linalg.eig(A)
idx_max = np.argmax(lambda_2)
print('Con Numpy:')
print(f'λ_max exacto: {lambda_2[idx_max]}')
print(f'v_max exacto: {v2[:, idx_max]}')


Método de potencias:
λ_max ≈ 2.835152533482731
v_max ≈ [0.40258952 0.47908181 0.33574933 0.38350287 0.3542382  0.47235107]
Iteraciones: 6
Variación final: 2.2363044305251378e-08
Con Numpy:
λ_max exacto: 2.835152534247637
v_max exacto: [-0.40259498 -0.4790814  -0.3357358  -0.38350111 -0.3542414  -0.47235548]


#5

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [15]:
#Matrices de Pauli
sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)
sigma_z = np.array([[1, 0], [0, -1]], dtype=complex)
I = np.eye(2, dtype=complex)

#Generamos una matriz Hermitiana aleatoria
np.random.seed(0)
L = np.random.rand(2, 2) + 1j * np.random.rand(2, 2)
L = (L + L.conj().T) / 2

a = np.trace(L @ sigma_x) / 2
b = np.trace(L @ sigma_y) / 2
c = np.trace(L @ sigma_z) / 2
d = np.trace(L @ I) / 2

L_ = a * sigma_x + b * sigma_y + c * sigma_z + d * I

#Verificamos si son iguales
print( np.allclose(L, L_))



True


# 6

Haga un breve resumen en Markdown de las funciones y métodos más relevantes para algebra lineal usando Python. Emplee ejemplos.

* Creacion y manipulación de matrices, operaciones entre ellas, determinantes,inversas, etc.
(Como en el primer punto)

* Resolver sistemas de ecuaciones Gauss, Gauss-Jordan y numpy:

x = np.linalg.solve(A, b)

* Métodos iterativos:

Jacobi: actualiza todas las variables usando valores de la iteración anterior.

Gauss–Seidel: usa valores recién calculados en la misma iteración.

* Operaciones con números complejos

B = np.array([[1+2j, 3], [4, 5-1j]])
np.linalg.inv(B)

* Valores y vectores propios

valores, vectores = np.linalg.eig(A)