In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
A = np.array(([2., 3.],
             [4., -1.]), dtype = float)

b = np.array(([5,6]), dtype = float)

## $Regla$ $De$ $Cramer$

In [3]:
def Cramer(A, b):
    '''
    Encuentra la solucion a un sistema de ecuaciones
    usando la regla de CRamer

    A = matriz cuadrada
    b = vectro 



    '''

    if A.shape[0]!

SyntaxError: invalid syntax (1009675575.py, line 13)

## $ELiminacion$ $Gaussiana$

In [4]:
def Eliminacion_Gauss(A, b):
    '''
    Encuantra la solucion de un sistema de ecuaciones
    usando eliminacion Gaussiana

    Entradas:
    A: Matriz --> ndarray
    b : vectror de factores imdependientes

    Salidas 
    U : matriz triangular superior -> nd array
    x: vector de soluciones
    '''
    A_aumentada = np.column_stack((A,b))
    n = A.shape[0] #Numero de soluciones


 
    
    for i in range(n):
        #Nos ubicamos en la fila con el pivote
        for j in range(i+1, n):
            #Calculamos el factor para la eliminación
            factor = A_aumentada[j,i]/A_aumentada[i,i]
            #OPeramos en la fila i-esima con el factor y reemplazamos en la j-esima
            A_aumentada[j, :]-= factor * A_aumentada[i, :]

    #Sustitución hacia atras
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        x[i] = (A_aumentada[i, -1] - np.dot(A_aumentada[i, i+1:n], x[i+1 :n])) /A_aumentada[i,i]
                
    return A_aumentada,x

In [5]:
A = np.array(([1., 2., 3.],
              [2., 3., 1.],
              [3., 1., 2.]), dtype = float)

b = np.array(([9., 8., 7.]), dtype = float)

In [6]:
Eliminacion_Gauss(A, b)

(array([[  1.,   2.,   3.,   9.],
        [  0.,  -1.,  -5., -10.],
        [  0.,   0.,  18.,  30.]]),
 array([0.66666667, 1.66666667, 1.66666667]))

In [7]:
max_index= np.argmax(np.abs(A[:,0]))

In [8]:
def Eliminacion_Gauss_pivote_simple(A, b):
    '''
    Encuantra la solucion de un sistema de ecuaciones
    usando eliminacion Gaussiana

    Entradas:
    A: Matriz --> ndarray
    b : vectror de factores imdependientes

    Salidas 
    U : matriz triangular superior -> nd array
    x: vector de soluciones
    '''
    A_aumentada = np.column_stack((A,b))
    n = A.shape[0] #Numero de soluciones

    max_index = np.argmax(np.abs(A_aumentada[:, 0]))
    A_aumentada[[0,max_index], :] = A_aumentada[[max_index, 0], :]
    
    for i in range(n):
        #Nos ubicamos en la fila con el pivote
        for j in range(i+1, n):
            #Calculamos el factor para la eliminación
            factor = A_aumentada[j,i]/A_aumentada[i,i]
            #OPeramos en la fila i-esima con el factor y reemplazamos en la j-esima
            A_aumentada[j, :]-= factor * A_aumentada[i, :]

    #Sustitución hacia atras
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        x[i] = (A_aumentada[i, -1] - np.dot(A_aumentada[i, i+1:n], x[i+1 :n])) /A_aumentada[i,i]
                
    return A_aumentada,x

In [9]:
Eliminacion_Gauss_pivote_simple(A,b)

(array([[ 3.        ,  1.        ,  2.        ,  7.        ],
        [ 0.        ,  2.33333333, -0.33333333,  3.33333333],
        [ 0.        ,  0.        ,  2.57142857,  4.28571429]]),
 array([0.66666667, 1.66666667, 1.66666667]))

## $Gauss$ $Jordan$

In [14]:
A = np.array(([2, 1,-1],
             [-3, -1, 2],
             [-2, 1, 2]), dtype = float)
b = np.array([8, -11, -3], dtype = float)
la.solve(A, b)

array([ 2.,  3., -1.])

In [20]:
A_aumentada = np.column_stack((A,b))
A_aumentada

array([[  2.,   1.,  -1.,   8.],
       [ -3.,  -1.,   2., -11.],
       [ -2.,   1.,   2.,  -3.]])

In [21]:
A_aumentada[0] = A_aumentada[0] / A_aumentada[0,0]

In [22]:
A_aumentada[1] -= A_aumentada[1,0] * A_aumentada[0]
A_aumentada[2] -= A_aumentada[2,0] * A_aumentada[0]
A_aumentada

array([[ 1. ,  0.5, -0.5,  4. ],
       [ 0. ,  0.5,  0.5,  1. ],
       [ 0. ,  2. ,  1. ,  5. ]])

In [28]:
A_aumentada[1] = A_aumentada[1] / A_aumentada[1,1]
A_aumentada[0] -= A_aumentada[0,1] * A_aumentada[1]
A_aumentada[2] -= A_aumentada[2,1] * A_aumentada[1]

A_aumentada

array([[ 1.,  0., -1.,  3.],
       [ 0.,  1.,  1.,  2.],
       [ 0.,  0., -1.,  1.]])

In [34]:
def Gauss_Jordan(A, b):
    '''
    Resuelve el sistema Ax = b usando Gauss - Jordan

    Entradas:
    A : Matriz 
    b : vector

    Salida:
    x: Vector solucion

    '''

    A_aun = np.column_stack((A, b))
    n = A.shape[0]

    for i in range(n):
        pivote = A_aun[i, i] #Elegimos el pivote

        if np.isclose(pivote, 0):
            raise ValueError('EL pivote es cercano a cero')
        A_aun[i] = A_aun[i]/ pivote #Normalizacion

        for j in range(n):
            if j!=i:
                #Dejamos los elementos en la columna j-esima diferente a donde esta el pivote
                A_aun[j] -= A_aun[j,i] * A_aun[i] #Eliminacion
    return A_aun, A_aun[:, -1]

In [35]:
A = np.array(([2, 1,-1],
             [-3, -1, 2],
             [-2, 1, 2]), dtype = float)
b = np.array([8, -11, -3], dtype = float)
Gauss_Jordan(A,b)

(array([[ 1.,  0.,  0.,  2.],
        [ 0.,  1.,  0.,  3.],
        [-0., -0.,  1., -1.]]),
 array([ 2.,  3., -1.]))

In [42]:
n = A.shape[0]

I = np.eye(n)

M, solve = Gauss_Jordan(A,I)

solve = solve[:,[n, -1)]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

## $Usando$ $LU$

In [43]:
A = np.array(([2,3],
              [4,7]), dtype = float)

In [ ]:
import scipy.linalg as sla
sla.A