In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
from random import randint
import sympy as sp


# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Maria Jose Jaimes Gelves
*Métodos computacionales*

---

## 1
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [3]:
# Primero vamos a definir las matrices A, B y C
A = np.random.rand(3,3)
B = np.random.rand(3,3)
C = np.random.rand(3,3)

print('============ Estas son las matrices que vamos a utilizar ============')

print(f'Matriz A:\n {A}', 
    f'\nMatriz B:\n {B}',
    f'\nMatriz C:\n {C}')
print('======='*10)

# Como todas las matrices son cuadradas y del mismo tamaño, podemos multiplicarlas sin problemas
# ==============================================================================================
# Multiplicamos AB
AB = A@B
print(f'\nProducto de A*B:\n {AB}')
# Multiplicamos BA
BA = B@A
print(f'\nProducto de B*A:\n {BA}\n')

# Ahora vamos a comprobar si AB y BA son iguales
print('¿Son iguales AB y BA?:')
if np.allclose(AB, BA)== True:
    print('Sí, son iguales')
else:
    print('No, no son iguales')

print('======='*10)

# ==============================================================================================

# Calculamos (AB)C
ABC1 = (A @ B) @ C
print(f'\nProducto de (AB)C:\n {ABC1}')
# Calculamos A(BC)
ABC2 = A @ (B @ C)
print(f'\nProducto de A(BC):\n {ABC2}\n')

# Ahora vamos a comprobar si (AB)C y A(BC) son iguales
print('¿Son iguales (AB)C y A(BC)?:')
if np.allclose(ABC1, ABC2) == True:
    print('Sí, son iguales')
else:
    print('No, no son iguales')

print('======='*10)

# ==============================================================================================

# Calculamos A(B + C)
abc1 = A @ (B + C)
print(f'\nProducto de A(B + C):\n {abc1}')
# Calculamos AB + AC
abc2 = (A @ B) + (A @ C)
print(f'\nProducto de AB + AC:\n {abc2}\n')

# Ahora vamos a comprobar si A(B + C) y AB + AC son iguales
print('¿Son iguales A(B + C) y AB + AC?:')
if np.allclose(abc1, abc2) == True:
    print('Sí, son iguales')
else:
    print('No, no son iguales')

print('======='*10)

# ==============================================================================================

# Calculamos (A + B)C
abc3 = (A + B) @ C
print(f'\nProducto de (A + B)C:\n {abc3}')
# Calculamos AC + BC
abc4 = (A @ C) + (B @ C)
print(f'\nProducto de AC + BC:\n {abc4}\n')

# Ahora vamos a comprobar si (A + B)C y AC + BC son iguales
print('¿Son iguales (A + B)C y AC + BC?:')
if np.allclose(abc3, abc4) == True:
    print('Sí, son iguales')
else:
    print('No, no son iguales')

print('======='*10)

# ==============================================================================================

# Calculamos (AB)^T
AB_T = (A @ B).T
print(f'\nTranspuesta del producto (AB)^T:\n {AB_T}')
# Calculamos B^T A^T
B_tA_t = B.T @ A.T
print(f'\nProducto de B^T y A^T:\n {B_tA_t}\n')

# Ahora vamos a comprobar si (AB)^T y B^T A^T son iguales
print('¿Son iguales (AB)^T y B^T*A^T?:')
if np.allclose(AB_T, B_tA_t) == True:
    print('Sí, son iguales')
else:
    print('No, no son iguales')

print('======='*10)

# ==============================================================================================

# Calculamos det(AB)
det_AB = la.det(A @ B)
print(f'\nDeterminante del producto AB (det(AB)): {det_AB}')
# Calculamos det(A) * det(B)
det_A_B = la.det(A) * np.linalg.det(B)
print(f'\nProducto de los determinantes de A y B (det(A)*det(B)): {det_A_B}\n')

# Ahora vamos a comprobar si det(AB) y det(A) * det(B) son iguales
print('¿Son iguales det(AB) y det(A) * det(B)?:')
if np.isclose(det_AB, det_A_B) == True:
    print('Sí, son iguales')
else:
    print('No, no son iguales')

print('======='*10)

# ==============================================================================================

print('Esta es la matriz A original:\n', A)
# Calculamos ((A)^T)^T
A_T_T = (A.T).T
print(f'\nTranspuesta de la transpuesta de A ((A)^T)^T:\n {A_T_T}\n')
# Ahora vamos a comprobar si ((A)^T)^T es igual a A
print('¿Es igual ((A)^T)^T a A?:')
if np.allclose(A_T_T, A) == True:
    print('Sí, son igual')
else:
    print('No, no son igual')

print('======='*10)

# ==============================================================================================

# Elegimos un número aleatorio entre 1 y 10
num = randint(1, 10)
print(f'\nNúmero aleatorio elegido(c): {num}')
# Calculamos cA
cA = (num * A).T
print(f'\nTranspuesta del producto de (cA)^T:\n {cA}')
# Calculamos cA^T
cA_T = (num * A.T)
print(f'\nProducto de cA^T:\n {cA_T}\n')

# Ahora vamos a comprobar si cA^T y cA son iguales
print('¿Son iguales cA^T y cA?:')
if np.allclose(cA_T, cA) == True:
    print('Sí, son iguales')
else:
    print('No, no son iguales')

print('======='*10)

# ==============================================================================================

# Calculamos (A + B)^T
A_B_T = (A + B).T
print(f'\nTranspuesta de la suma (A + B)^T:\n {A_B_T}')
# Calculamos A^T + B^T
A_T_B_T = A.T + B.T
print(f'\nResultado de A^T + B^T:\n {A_T_B_T}\n')

# Ahora vamos a comprobar si (A + B)^T y A^T + B^T son iguales
print('¿Son iguales (A + B)^T y A^T + B^T?:')
if np.allclose(A_B_T, A_T_B_T) == True:
    print('Sí, son iguales')
else:
    print('No, no son iguales')

============ Estas son las matrices que vamos a utilizar ============
Matriz A:
 [[0.31564192 0.49644313 0.54883712]
 [0.28892097 0.75679136 0.70212606]
 [0.1666682  0.55451852 0.59786317]] 
Matriz B:
 [[0.66536053 0.78388007 0.3965681 ]
 [0.22913733 0.1132782  0.36359094]
 [0.24645018 0.78893072 0.1259824 ]] 
Matriz C:
 [[0.95214232 0.22991715 0.90860624]
 [0.24798473 0.74766025 0.76456866]
 [0.15916892 0.93600297 0.03405985]]

Producto de A*B:
 [[0.45903033 0.73665606 0.37481955]
 [0.53868485 0.86613618 0.47819485]
 [0.38529882 0.66513537 0.34303344]]

Producto de B*A:
 [[0.50259036 1.14345168 1.15265065]
 [0.16565284 0.40109953 0.42267229]
 [0.3267259  0.78926402 0.76451006]]

¿Son iguales AB y BA?:
No, no son iguales

Producto de (AB)C:
 [[0.67940128 1.00713962 0.99306826]
 [0.80380695 1.21902028 1.16796024]
 [0.58640299 0.9069624  0.87031024]]

Producto de A(BC):
 [[0.67940128 1.00713962 0.99306826]
 [0.80380695 1.21902028 1.16796024]
 [0.58640299 0.9069624  0.87031024]]

¿Son igu

## 2

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [4]:
def determinante_Laplace(matrix):
    '''
    Calcula el determinante de una matriz cuadrada utilizando una función recursiva del Teorema de Laplace
    Input:
    - matrix: numpy array de forma (n, n) que representa la matriz cuadrada
    Output:
    - det: valor del determinante de la matriz
    '''

    if matrix.shape[0] != matrix.shape[1]: 
        # Verifica si la matriz es cuadrada
        raise ValueError('La matriz debe ser cuadrada para calcular su determinante.')

    if matrix.shape == (1,1):
        # Caso base: si la matriz es 1x1, el determinante es el único elemento
        return matrix[0,0]

    det = 0 # Inicializa el determinante
    n = len(matrix) # Número de filas de la matriz
    for i in range(n): # Itera sobre cada elemento de la primera fila
        # Calcula la submatriz eliminando la primera fila y la columna i
        submatrix = np.delete(np.delete(matrix, 0, axis=0), i, axis=1)
        # Determina el signo basado en la posición del elemento
        signo = (-1) ** i 
        # Calcula el determinante recursivamente
        det += signo * matrix[0, i] * determinante_Laplace(submatrix)
    return det

A = np. array([10])
B = np.array([
    [3, 2, 1],
    [0, 2, -5],
    [-2, 1, 4]
])

A.shape 
determinante_Laplace(B)

np.int64(63)

## 3 Método de Gauss - Seidel

Sea $A\in\mathbb{R}^{n\times n}$ no singular y sea $b\in\mathbb{R}^n$.
Descomponga $ A $ como
 
$$
A \;=\; D \;+\; L \;+\; U,
$$

donde

* $D$ es la matriz diagonal de $A$,
* $L$ es la parte estrictamente triangular inferior,
* $U$ es la parte estrictamente triangular superior.

El algoritmo de Gauss - Seidel reorganiza el sistema $Ax=b$ como

$$
x \;=\; (D+L)^{-1}\bigl(b \;-\; Ux\bigr),
$$

y genera la sucesión

$$
x_i^{(k+1)}
= \frac{1}{a_{ii}}
\Bigl(b_i - \sum_{j<i} a_{ij}\,x_j^{(k+1)} - \sum_{j>i} a_{ij}\,x_j^{(k)}\Bigr),
\qquad i=1,\dots,n.
$$

Implemente una función `gauss_seidel(A, b, tol=1e-7, max_iter=100)` que:
   * Realice las iteraciones hasta que
     $lVert x^{(k+1)}-x^{(k)}\rVert_\infty<\text{tol}$
     o se alcance `max_iter`;
   * devuelva el vector solución aproximado $x$, el número de iteraciones realizadas y la norma del último residuo.

Incluya una documentación clara.

Luego,

   * Genere una matriz aleatoria $5\times5$ (por ejemplo, con `np.random.rand`) y un vector \$b\$ aleatorio.
   * Resuelva $Ax=b$ con su función; calcule el error relativo frente a `numpy.linalg.solve`.
   * Estime igualmente el error respecto a la solución obtenida mediante $x=A^{-1}b$ (usando `numpy.linalg.inv`).
   * Presente las normas de los residuos y los errores relativos.

In [5]:
def gauss_seidel(A, b, tol=1e-7, max_iter=100):
    '''
    Implementa el método de Gauss-Seidel para resolver un sistema de ecuaciones lineales Ax = b.
    Input:
    - A: matriz de coeficientes (numpy array de forma (n, n))
    - b: vector de términos independientes (numpy array de forma (n,))
    - tol: tolerancia para la convergencia (float, por defecto 1e-7)
    - max_iter: número máximo de iteraciones (int, por defecto 100)
    Output:
    - x: solución del sistema (numpy array de forma (n,))
    - iter: número de iteraciones realizadas
    - res_norm: norma del residuo del sistema
    '''
    
    # Verifica si A es cuadrada y b tiene la forma correcta
    if A.shape[0] != A.shape[1] or A.shape[0] != b.shape[0]:
        raise ValueError("La matriz A debe ser cuadrada y el vector b debe tener la misma longitud que las filas de A.")

    n = len(b) # Número de ecuaciones
    x = np.zeros_like(b, dtype= float) # Inicializa la solución con ceros
    iter = 0 # Contador de iteraciones

    for h in range(max_iter): # Itera hasta el máximo de iteraciones
        x_old = np.copy(x) # Copia la solución actual para comparar después
        # Itera sobre cada ecuación
        for i in range(n): 
            suma1 = np.dot(A[i, :i], x[:i])  # Suma de los términos anteriores
            suma2 = np.dot(A[i, i+1:], x_old[i+1:])  # Suma de los términos posteriores
            x[i] = (b[i] - suma1 - suma2) / A[i, i] # Actualiza la solución para la i-ésima variable
        iter += 1 # Incrementa el contador de iteraciones

        # Verificamos convergencia usando norma infinito
        error = np.linalg.norm(x - x_old, ord=np.inf)

        if error < tol: 
            # Si el error es menor que la tolerancia, se considera convergencia
            break
    residuo = A@x - b # Calcula el residuo del sistema
    res_norm = np.linalg.norm(residuo, ord=np.inf) # Norma infinito del residuo

    return x, iter, res_norm

A = np.random.rand(5, 5) # Generamos una matriz aleatoria de 5x5
b = np.random.rand(5) # Generamos un vector aleatorio de 5 elementos

# Aseguramos que A sea una matriz diagonal dominante para garantizar la convergencia
for i in range(len(A)):
    A[i, i] += sum(abs(A[i]))  # Aumenta el elemento diagonal para asegurar la convergencia

print("Matriz A:\n", A)
print("\nVector b:\n", b)
print("\nResolviendo el sistema Ax = b usando Gauss-Seidel:")

x, iteraciones, residuo = gauss_seidel(A, b) # llamamos a la función gauss_seidel
print(f"\nSolución x: {x}")
print(f"Número de iteraciones: {iteraciones}")
print(f"Norma del residuo: {residuo}")

# ==============================================================================================

# Ahora vamos a comparar el resultado de la función gauss_seidel con la solución de numpy
x_numpy = np.linalg.solve(A, b)
print(f'\nSolución usando np.linalg.solve:\n {x_numpy}')

# Calculamos el error entre la solución de Gauss-Seidel y la solución de numpy
error = np.linalg.norm(x - x_numpy)
print(f'\nError entre la solución de Gauss-Seidel y la solución de np.linalg.solve: {error}')

# ==============================================================================================

x_inv = np.linalg.inv(A) @ b
print(f'\nSolución usando np.linalg.inv:\n {x_inv}')
# Calculamos el error entre la solución de Gauss-Seidel y la solución usando la inversa de A
error_inv = np.linalg.norm(x - x_inv)
print(f'\nError entre la solución de Gauss-Seidel y la solución usando np.linalg.inv: {error_inv}')


Matriz A:
 [[3.54077287 0.00899734 0.98512602 0.12375993 0.52491417]
 [0.5034543  3.62068307 0.39097058 0.27121206 0.54261305]
 [0.79976238 0.75214785 3.26560232 0.67859369 0.85473757]
 [0.10941319 0.3227271  0.26452409 2.38868265 0.21012024]
 [0.07429181 0.45653026 0.39333149 0.65563905 2.49559955]]

Vector b:
 [0.75350489 0.41075575 0.55785739 0.7230939  0.13071787]

Resolviendo el sistema Ax = b usando Gauss-Seidel:

Solución x: [ 0.19266997  0.06615744  0.06269079  0.28236688 -0.04952229]
Número de iteraciones: 8
Norma del residuo: 3.688968031045903e-08

Solución usando np.linalg.solve:
 [ 0.19266996  0.06615744  0.0626908   0.28236689 -0.04952229]

Error entre la solución de Gauss-Seidel y la solución de np.linalg.solve: 1.1782852226783883e-08

Solución usando np.linalg.inv:
 [ 0.19266996  0.06615744  0.0626908   0.28236689 -0.04952229]

Error entre la solución de Gauss-Seidel y la solución usando np.linalg.inv: 1.1782852191708593e-08


## 4 Método de potencias para el valor propio dominante

Sea $A\in\mathbb{R}^{n\times n}$ diagonalizable con valor propio dominante $\lambda\_{\max}$ (en magnitud) y vector propio asociado $v\_{\max}$.

El método de potencias genera, a partir de un vector inicial $q^{(0)}\neq 0$, la sucesión

$$
q^{(k+1)} \;=\; \frac{A\,q^{(k)}}{\lVert A\,q^{(k)}\rVert_2},
\qquad
\lambda^{(k+1)} \;=\; (q^{(k+1)})^{\!\top} A\, q^{(k+1)},
$$

que converge a $v\_{\max}/\lVert v\_{\max}\rVert\_2$ y a $\lambda\_{\max}$ respectivamente, bajo hipótesis estándar.

Implemente `power_method(A, tol=1e-7, max_iter=1000)` que:

   * Acepte matrices reales cuadradas,
   * Devuelva $\lambda\_{\max}$, el vector propio normalizado $v\_{\max}$, el número de iteraciones y la última variación relativa de $\lambda$,
   * detenga la iteración cuando
     $\bigl|\lambda^{(k+1)}-\lambda^{(k)}\bigr|<\text{tol}\,|\lambda^{(k+1)}|$
     o se alcance `max_iter`.

Luego,
   * Genere una matriz simétrica aleatoria $6\times6$ (por ejemplo, $A = (M+M^\top)/2$ con $M$ aleatoria).
   * Aplique su `power_method` y compare $\lambda\_{\max}$ y $v\_{\max}$ con los resultados de `numpy.linalg.eig`.

In [6]:
def power_method(A, tol=1e-7, max_iter=1000):
    '''
    Implementa el método de potencias para encontrar el valor propio dominante y su vector propio asociado.
    Input:
    - A: matriz cuadrada (numpy array de forma (n, n))
    - tol: tolerancia para la convergencia (float, por defecto 1e-7)
    - max_iter: número máximo de iteraciones (int, por defecto 1000)
    Output:
    - lambda_max: valor propio dominante (float)
    - v_max: vector propio normalizado asociado al valor propio dominante (numpy array de forma (n,))
    - iter: número de iteraciones realizadas (int)
    - last_variation: última variación relativa del valor propio (float)
    '''

    # Verifica si A es cuadrada
    if A.shape[0] != A.shape[1]:
        raise ValueError('La matriz A debe ser cuadrada.')
    
    # Número de filas/columnas de la matriz
    n = A.shape[0]  

    # Vector inicial aleatorio de dimension n
    q = np.random.rand(n)

    # Normaliza el vector inicial
    q /= la.norm(q)

    # Inicializa el valor propio anterior en 0
    lambda_anterior = 0

    for iter in range(max_iter):
        
        # Multiplica A por el vector q
        q_new = A @ q 

        # Normaliza el nuevo vector
        q_new /= la.norm(q_new)  

        # Calcula el valor propio asociado al nuevo vector
        lambda_new = q_new.T @ A @ q_new 

        # Calcula la variación relativa del valor propio
        last_variation = abs(lambda_new - lambda_anterior) / abs(lambda_new) if lambda_anterior != 0 else np.inf

        # Verifica si la variación es menor que la tolerancia
        if last_variation < tol:  
            break

        # Actualiza el vector q y el valor propio anterior
        q = q_new 
        lambda_anterior = lambda_new  

    v_max = q_new  # El vector propio asociado al valor propio dominante es el último vector normalizado
    lambda_max = lambda_new  # El valor propio dominante es el último valor calculado

    return lambda_max, v_max, iter + 1, last_variation

# Generamos una matriz simétrica aleatoria 6x6
M = np.random.rand(6, 6)
M = (M + M.T) / 2  # Hacemos la matriz simétrica
print(f'Matriz simétrica aleatoria 6x6:\n{M}')

# Aplicamos el método de potencias
lambda_max, v_max, iteraciones, last_variation = power_method(M)
print(f'\nValor propio dominante (lambda_max): {lambda_max}')
print(f'Vector propio asociado (v_max): {v_max}')
print(f'Número de iteraciones: {iteraciones}')
print(f'Última variación relativa del valor propio: {last_variation}')

# Comparamos con numpy.linalg.eig
lambda_numpy, v_numpy = np.linalg.eig(M)
print(f'\nValor propio dominante usando numpy.linalg.eig: {lambda_numpy[np.argmax(np.abs(lambda_numpy))]}')
print(f'Vector propio asociado usando numpy.linalg.eig: {v_numpy[:, np.argmax(np.abs(lambda_numpy))]}')

# Comparamos los resultados
print(f'\n¿Son iguales los valores propios?: {np.isclose(lambda_max, lambda_numpy[np.argmax(np.abs(lambda_numpy))])}')
print(f'¿Son iguales los vectores propios?: {np.allclose(v_max, v_numpy[:, np.argmax(np.abs(lambda_numpy))])}')

# Veamos su error
error_lambda = abs(lambda_max - lambda_numpy[np.argmax(np.abs(lambda_numpy))])
print(f'\nError en el valor propio: {error_lambda}')
error_vector = np.linalg.norm(v_max - v_numpy[:, np.argmax(np.abs(lambda_numpy))])
print(f'Error en el vector propio: {error_vector}')



Matriz simétrica aleatoria 6x6:
[[0.26296872 0.50304728 0.51030109 0.78762333 0.56778458 0.9184432 ]
 [0.50304728 0.32928102 0.10745329 0.23795118 0.34269774 0.50754075]
 [0.51030109 0.10745329 0.62694841 0.53797871 0.35344077 0.48294097]
 [0.78762333 0.23795118 0.53797871 0.53128676 0.35305826 0.43065624]
 [0.56778458 0.34269774 0.35344077 0.35305826 0.77250996 0.23203611]
 [0.9184432  0.50754075 0.48294097 0.43065624 0.23203611 0.14175834]]

Valor propio dominante (lambda_max): 2.803614184370322
Vector propio asociado (v_max): [0.50538303 0.29802784 0.39314613 0.43587479 0.38217657 0.40639605]
Número de iteraciones: 7
Última variación relativa del valor propio: 1.9454520684219355e-08

Valor propio dominante usando numpy.linalg.eig: 2.8036141892628637
Vector propio asociado usando numpy.linalg.eig: [0.50540982 0.29802991 0.39314788 0.43586607 0.38217234 0.40637286]

¿Son iguales los valores propios?: True
¿Son iguales los vectores propios?: False

Error en el valor propio: 4.892541483

## 5

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [7]:
print('======='*10)
print('Primero vamos a verificar simbolicamente si una matriz hermitiana 2x2 puede ser expresada como una combinación lineal de las matrices de Pauli y la identidad.')

# Definimos las matrices de Pauli simbólicamente y la identidad
sigma_x = sp.Matrix([[0, 1], [1, 0]])
sigma_y = sp.Matrix([[0, -sp.I], [sp.I, 0]])
sigma_z = sp.Matrix([[1, 0], [0, -1]])
I = sp.eye(2)

p, q, r, s = sp.symbols('p q r s')

# Definimos la matriz hermitiana H 
H = sp.Matrix([[r, p + sp.I*q],
    [p - sp.I*q, s]])

a, b, c, d = sp.symbols('a b c d') # Coeficientes reales que queremos encontrar

# Definimos la suma de las matrices de Pauli y la identidad con los coeficientes a, b, c y d
sum_term = a*sigma_x + b*sigma_y + c*sigma_z + d*I

# Igualamos la matriz hermitiana H a la suma de las matrices de Pauli
L = sp.Eq(H, sum_term)

# Resolvemos el sistema de ecuaciones para encontrar los coeficientes a, b, c y d
solution = sp.solve(L, [a, b, c, d])
print(f'\nSolución del sistema de ecuaciones:\n{solution}')

# Imprimimos los coeficientes encontrados
print(f'\nCoeficientes encontrados:\n a = {solution[a]}, b = {solution[b]}, c = {solution[c]}, d = {solution[d]}')

# Verificamos que la suma de las matrices de Pauli es igual a la matriz hermitiana H
H_calculated = solution[a]*sigma_x + solution[b]*sigma_y + solution[c]*sigma_z + solution[d]*I
print(f'\nMatriz hermitiana calculada:\n{H_calculated}')

is_equal = H == H_calculated
print(f'\n¿La matriz hermitiana original es igual a la calculada?: {is_equal} \n')

print('======='*10)
# ===============================================================================================

print('\nAhora vamos a generar una matriz hermitiana 2x2 random y verificar si puede ser expresada como una combinación lineal de las matrices de Pauli y la identidad.')    

# Definimos las matrices de Pauli y la identidad
sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)
sigma_z = np.array([[1, 0], [0, -1]], dtype=complex)
I = np.array([[1, 0], [0, 1]], dtype=complex)

# Generamos una matriz hermitiana 2x2 
p = np.random.randint(-100,100)
q = np.random.randint(-100,100)
r = np.random.randint(-100,100)
s = np.random.randint(-100,100)

L = np.array([[r, p + q*1j],
            [p - q*1j, s]])

print('Matriz hermitiana L:')
print(L)

# Queremos encontrar reales a, b, c, d tal que:
# L = a*sigma_x + b*sigma_y + c*sigma_z + d*I

# Utilizamos el resultado anterior
print('Vamos a utilizar el resultado anterior para encontrar los coeficientes reales a, b, c y d.')
a = p
b = -q
c = (r-s)/2
d = (r+s)/2

print(f'\nCoeficientes reales:')
print(f'a = {a}, b = {b}, c = {c}, d = {d}')

# Reconstruimos la matriz usando los coeficientes
L_reconstruida = a * sigma_x + b * sigma_y + c * sigma_z + d * I

print('\nMatriz reconstruida L:')
print(L_reconstruida)

# Verificamos si son iguales
print('\n¿L ≈ L?:', np.allclose(L, L_reconstruida))


Primero vamos a verificar simbolicamente si una matriz hermitiana 2x2 puede ser expresada como una combinación lineal de las matrices de Pauli y la identidad.

Solución del sistema de ecuaciones:
{a: p, b: -q, c: r/2 - s/2, d: r/2 + s/2}

Coeficientes encontrados:
 a = p, b = -q, c = r/2 - s/2, d = r/2 + s/2

Matriz hermitiana calculada:
Matrix([[r, p + I*q], [p - I*q, s]])

¿La matriz hermitiana original es igual a la calculada?: True 


Ahora vamos a generar una matriz hermitiana 2x2 random y verificar si puede ser expresada como una combinación lineal de las matrices de Pauli y la identidad.
Matriz hermitiana L:
[[ 69. +0.j  18.-58.j]
 [ 18.+58.j -87. +0.j]]
Vamos a utilizar el resultado anterior para encontrar los coeficientes reales a, b, c y d.

Coeficientes reales:
a = 18, b = 58, c = 78.0, d = -9.0

Matriz reconstruida L:
[[ 69. +0.j  18.-58.j]
 [ 18.+58.j -87. +0.j]]

¿L ≈ L?: True


## 6

Haga un breve resumen en Markdown de las funciones y métodos más relevantes para algebra lineal usando Python. Emplee ejemplos.

Se utiliza principalmente `numpy` y/o `scipy.linalg`. 

Sea $A$ una matriz, $v$ y $u$ vectores
1. Para crear matrices o vectores se puede utilizar `numpy.array()`
2. Se puede utilizar `numpyp.dot(A, v)` para multiplicar vectores y/o matrices. Sin embargo, existe una funcion `@` que se utiliza para multiplicar matrices
3. Para calcular el producto cruz de vectores se puede utilizar `numpy.cross(u, v)`
4. Para acceder a filas, columnas, submatrices y/o elementos de una matriz se hace mediante `A[1]` (segunda fila), `A[:, 1]` (segunda columna), `A[0, 1]` (elemento [1,2])
5. Numpy tiene diversas funciones para facilitar crear matrices comunes como:
    * A. `numpy.eye(n)` matriz identidad
    * B. `numpy.zeros((m, n))` matriz de ceros 
    * C. `numpy.ones((m, n))` matriz de unos
    * D. `numpy.random.rand(m, n)` matriz con valores aleatorios de 0 a 1
6. * A. Con `A.shape` se puede saber la dimension de la matriz $A$
    * B. Con `A.size` se puede conocer la cantidad de elementos
    * C. Con `len(A)` se puede conocer el numero de filas
7. Se puede calcular el determinante de una matriz utilizando `numpy.linalg.det(A)` o `scipy.linalg.det(A)`
8. Para calcular la matriz transpuesta se utiliza `A.T`
9. Para conocer la inversa de una matriz se puede utilizar la funcion `numpy.linalg.inv(A)` o `scipy.linalg.inv(A)`
10. `A.conjugate` sirve para calcular la conjugada de una matriz
11. Para extraer los valores de la diagonal se utiliza `numpy.diag(A)`
12. Se puede calcular la traza de una matriz con `numpy.trace(A)`
13. Con el fin de resolver sistemas de ecuaciones de la forma $Ax = b$ se puede utilizar `numpy.linalg.solve(A, b)` o `scipy.linalg.solve(A, b)`
14. Para obtener los autovalores y los autovectores se utiliza la funcion `scipy.linalg.eig(A)` que retorna dos terminos, el primero de autovalores y el segundo de autovectores. Tambien se puede usar `numpy.linalg.eig(A)`
15. Se puede utilizar Sympy para obtener resultados exactos o mostrar de forma mas bonita las matrices



In [11]:
# Utilizamos np. random.randint (5.D) y np.array (1)
A = np.random.randint(-10,10, size=(3,3))
B = np.random.randint(-10,10, size=(3,3))
D = np.random.randint(-10,10, size=(4,6))
v = np.array([[1], [18], [23]]) #vector fila
u = np.array([1, 2, 3]) # vector columna

# Convertimos las matrices a formato sympy para imprimirlas (15)
A_sympy = sp.Matrix(A)
B_sympy = sp.Matrix(B)
D_sympy = sp.Matrix(D)
v_sympy = sp.Matrix(v)
u_sympy = sp.Matrix(u)
print('Matriz A:\n')
sp.pprint(A_sympy, use_unicode=True)
print('\nMatriz B:\n')
sp.pprint(B_sympy, use_unicode=True)
print('\nMatriz D:\n')
sp.pprint(D_sympy, use_unicode=True)
print('\nVector v:\n')
sp.pprint(v_sympy, use_unicode=True)
print('\nVector u:\n')
sp.pprint(u_sympy, use_unicode=True)

# 2
# Ahora vamos a calcular el producto de A y B
C = A @ B
C_sympy = sp.Matrix(C)
print('\nProducto de A y B con @:\n')
sp.pprint(C_sympy, use_unicode=True)

C_ = np.dot(A, B)
print('\nProducto de A y B con np.dot:\n')
sp.pprint(sp.Matrix(C_), use_unicode=True)

# Calculamos el producto de A y v
Av = A @ v
Av_sympy = sp.Matrix(Av)
print('\nProducto de A y v con @:\n')
sp.pprint(Av_sympy, use_unicode=True)

Av_ = np.dot(A, v)
print('\nProducto de A y v con np.dot:\n')
sp.pprint(sp.Matrix(Av_), use_unicode=True)

# Calculamos el producto de v y u
v_u = u @ v
v_u_sympy = sp.Matrix(v_u)
print('\nProducto de u y v con @:\n')
sp.pprint(v_u_sympy, use_unicode=True)

v_u_ = np.dot(u, v)
print('\nProducto de u y v con np.dot:\n')
sp.pprint(sp.Matrix(v_u_), use_unicode=True)

# 3
# Ahora vamos a calcular el producto cruz de v y u
cruz_vu = np.cross(v.flatten(), u.flatten())
cruz_vu_sympy = sp.Matrix(cruz_vu)
print('\nProducto cruz de v y u:\n')
sp.pprint(cruz_vu_sympy, use_unicode=True)

# Calculamos el producto cruz de u y v
cruz_uv = np.cross(u.flatten(), v.flatten())
cruz_uv_sympy = sp.Matrix(cruz_uv)
print('\nProducto cruz de u y v:\n')
sp.pprint(cruz_uv_sympy, use_unicode=True)

# 4
elemento = A[1,2] # Accedemos al elemento en la fila 2, columna 3
fila = A[1, :] # Accedemos a la fila 2
columna = A[:, 2] # Accedemos a la columna 3
submatriz = D[1:4, 0:3] # Accedemos a la submatriz de filas 1 y 2, columnas 2 y 3
print(f'\nElemento en la fila 2, columna 3 de A: {elemento}')
print(f'\nFila 2 de A: {fila}')
print(f'\nColumna 3 de A: {columna}')
print(f'\nSubmatriz de D (filas 2, 3 y 4, columnas 1, 2 y 3):\n{submatriz}')

# 5
identidad = np.eye(3) # Matriz identidad de 3x3
print('\nMatriz identidad de 3x3:\n')
sp.pprint(sp.Matrix(identidad), use_unicode=True)

ceros = np.zeros((3,3)) # Matriz de ceros de 3x3
print('\nMatriz de ceros de 3x3:\n')
sp.pprint(sp.Matrix(ceros), use_unicode=True)

unos = np.ones((3,3)) # Matriz de unos de 3x3
print('\nMatriz de unos de 3x3:\n')
sp.pprint(sp.Matrix(unos), use_unicode=True)

# 6
dimension = D.shape # Obtenemos la dimensión de la matriz A
print(f'\nDimensión de la matriz D: {dimension}')

num_elementos = D.size # Obtenemos el número de elementos de la matriz A
print(f'Número de elementos de la matriz D: {num_elementos}')

num_filas = len(D) # Obtenemos el número de filas de la matriz A
print(f'Número de filas de la matriz D: {num_filas}')

# 7
det_la = la.det(A) # Calculamos el determinante de A con scipy
print(f'\nDeterminante de la matriz A con scipy: {det_la}')
det_np = np.linalg.det(A) # Calculamos el determinante de A con numpy
print(f'Determinante de la matriz A con numpy: {det_np}')

# Verificamos si son iguales
if np.isclose(det_la, det_np):
    print('Los determinantes son iguales.')
else:
    print('Los determinantes no son iguales.')

# 8
transpuesta_B = B.T # Transponemos la matriz A
print('\nTranspuesta de la matriz B:\n')
sp.pprint(sp.Matrix(transpuesta_B), use_unicode=True)

# 9
inversa_A_la = la.inv(A) # Calculamos la inversa de A con scipy
print('\nInversa de la matriz A con scipy:\n')
sp.pprint(sp.Matrix(inversa_A_la), use_unicode=True)
inversa_A_np = np.linalg.inv(A) # Calculamos la inversa de A con numpy
print('\nInversa de la matriz A con numpy:\n')
sp.pprint(sp.Matrix(inversa_A_np), use_unicode=True)
# Verificamos si son iguales
if np.allclose(inversa_A_la, inversa_A_np):
    print('Las inversas son iguales.')
else:
    print('Las inversas no son iguales.')

# 10
conjugada = B.conjugate()
print(f'\nConjugada de la matriz B: \n')
sp.pprint(conjugada)

# 11
diagonal = np.diag(A)
print('\n La diagonal de la matriz A:\n')
sp.pprint(sp.Matrix(diagonal), use_unicode=True)

# 12
traza = np.trace(B)
print(f'\nLa traza de la matriz B: {traza}')

# 13
sol_Av_la = la.solve(A,v)
sol_Av_np = np.linalg.solve(A,v)
print('\nVector x para el sistema Ax = b con scipy:\n')
sp.pprint(sp.Matrix(sol_Av_la))
print('\nVector x para el sistema Ax = b con numpy:\n')
sp.pprint(sp.Matrix(sol_Av_np))

# 14
auto_val_la, auto_vec_la = la.eig(A)
auto_val_np, auto_vec_np = np.linalg.eig(A)

print('\nAutovalores de la matriz A con scipy:\n')
sp.pprint(sp.Matrix(np.diag(auto_val_la)))
print('\nAutovectores de la matriz A con scipy:\n')
sp.pprint(sp.Matrix(auto_vec_la))

print('\nAutovalores de la matriz A con numpy:\n')
sp.pprint(sp.Matrix(np.diag(auto_val_np)))
print('\nAutovectores de la matriz A con numpy:\n')
sp.pprint(sp.Matrix(auto_vec_np))

# Verificamos si son iguales
if np.allclose(auto_val_la, auto_val_np):
    print('Los autovalores son iguales.')
else:
    print('Los autovalores no son iguales.')

if np.allclose(auto_vec_la, auto_vec_np):
    print('Los autovectores son iguales.')
else:
    print('Los autovectores no son iguales.')


Matriz A:

⎡-4  -2  -7⎤
⎢          ⎥
⎢-2  8   -2⎥
⎢          ⎥
⎣-7  -3  -1⎦

Matriz B:

⎡5   -2  -10⎤
⎢           ⎥
⎢-9  -1  -1 ⎥
⎢           ⎥
⎣-7  -6  -5 ⎦

Matriz D:

⎡-7    1   5   3   4  7⎤
⎢                      ⎥
⎢ 9    1   1   -4  4  5⎥
⎢                      ⎥
⎢-10   8   -2  8   0  4⎥
⎢                      ⎥
⎣ 2   -10  -3  5   0  0⎦

Vector v:

⎡1 ⎤
⎢  ⎥
⎢18⎥
⎢  ⎥
⎣23⎦

Vector u:

⎡1⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎣3⎦

Producto de A y B con @:

⎡47   52  77⎤
⎢           ⎥
⎢-68  8   22⎥
⎢           ⎥
⎣-1   23  78⎦

Producto de A y B con np.dot:

⎡47   52  77⎤
⎢           ⎥
⎢-68  8   22⎥
⎢           ⎥
⎣-1   23  78⎦

Producto de A y v con @:

⎡-201⎤
⎢    ⎥
⎢ 96 ⎥
⎢    ⎥
⎣-84 ⎦

Producto de A y v con np.dot:

⎡-201⎤
⎢    ⎥
⎢ 96 ⎥
⎢    ⎥
⎣-84 ⎦

Producto de u y v con @:

[106]

Producto de u y v con np.dot:

[106]

Producto cruz de v y u:

⎡ 8 ⎤
⎢   ⎥
⎢20 ⎥
⎢   ⎥
⎣-16⎦

Producto cruz de u y v:

⎡-8 ⎤
⎢   ⎥
⎢-20⎥
⎢   ⎥
⎣16 ⎦

Elemento en la fila 2, columna 3 de A: -2

Fila 2 de A: [-2  8 -2]

Column