In [26]:
import numpy as np
import matplotlib.pyplot as plt
import numpy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Juan Sebastian Buitrago Díaz
*Métodos computacionales*

---

#1
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [27]:
n=0
Bool=[]
while n<1000:
  A = np.random.rand(3, 3)
  B = np.random.rand(3, 3)
  C = np.random.rand(3, 3)
  if (A@B != B@A).all() == False:
    print(f'La condición 1 no se cumple')
    break
  else:
    n+=1
if n==1000:
  print(f'La relacion 1 se cumple')

La relacion 1 se cumple


In [28]:
n=0
Bool=[]
while n<1000:
  A = np.random.rand(3, 3)
  B = np.random.rand(3, 3)
  C = np.random.rand(3, 3)
  if np.isclose(A@(B@C),(A@B)@C).all() == False:
    print(f'La condición 2 no se cumple')
    break
  else:
    n+=1
if n==1000:
  print(f'La relacion 2 se cumple')

La relacion 2 se cumple


In [29]:
n=0
Bool=[]
while n<1000:
  A = np.random.rand(3, 3)
  B = np.random.rand(3, 3)
  C = np.random.rand(3, 3)
  if np.isclose(A@(B+C),(A@B)+(A@C)).all() == False:
    print(f'La condición 3 no se cumple')
    break
  else:
    n+=1
if n==1000:
  print(f'La relacion 3 se cumple')

La relacion 3 se cumple


In [30]:
n=0
Bool=[]
while n<1000:
  A = np.random.rand(3, 3)
  B = np.random.rand(3, 3)
  C = np.random.rand(3, 3)
  if np.isclose((A+B)@C,(A@C)+(B@C)).all() == False:
    print(f'La condición 4 no se cumple')
    break
  else:
    n+=1
if n==1000:
  print(f'La relacion 4 se cumple')

La relacion 4 se cumple


In [31]:
n=0
Bool=[]
while n<1000:
  A = np.random.rand(3, 3)
  B = np.random.rand(3, 3)
  C = np.random.rand(3, 3)
  if np.isclose(np.transpose(A@B),np.transpose(B)@np.transpose(A)).all() == False:
    print(f'La condición 5 no se cumple')
    break
  else:
    n+=1
if n==1000:
  print(f'La relacion 5 se cumple')

La relacion 5 se cumple


In [32]:
n=0
Bool=[]
while n<1000:
  A = np.random.rand(3, 3)
  B = np.random.rand(3, 3)
  C = np.random.rand(3, 3)
  if np.isclose(la.det(A@B),(la.det(A)*la.det(B))).all() == False:
    print(f'La condición 6 no se cumple')
    break
  else:
    n+=1
if n==1000:
  print(f'La relacion 6 se cumple')

La relacion 6 se cumple


In [33]:
n=0
Bool=[]
while n<1000:
  A = np.random.rand(3, 3)
  B = np.random.rand(3, 3)
  C = np.random.rand(3, 3)
  if np.isclose(np.transpose(np.transpose(A)),A).all() == False:
    print(f'La condición 7 no se cumple')
    break
  else:
    n+=1
if n==1000:
  print(f'La relacion 7 se cumple')

La relacion 7 se cumple


In [34]:
n=0
Bool=[]
while n<1000:
  A = np.random.rand(3, 3)
  B = np.random.rand(3, 3)
  C = np.random.rand(3, 3)
  c=np.random.rand()
  if np.isclose(np.transpose(c*A),c*np.transpose(A)).all() == False:
    print(f'La condición 8 no se cumple')
    break
  else:
    n+=1
if n==1000:
  print(f'La relacion 8 se cumple')

La relacion 8 se cumple


In [35]:
n=0
Bool=[]
while n<1000:
  A = np.random.rand(3, 3)
  B = np.random.rand(3, 3)
  C = np.random.rand(3, 3)
  if np.isclose(np.transpose(A+B),np.transpose(A)+np.transpose(B)).all() == False:
    print(f'La condición 9 no se cumple')
    break
  else:
    n+=1
if n==1000:
  print(f'La relacion 9 se cumple')

La relacion 9 se cumple


#2

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [36]:
def determinante(A):
  """
  Resuelve el sistema lineal Ax = b usando el método iterativo de Gauss-Seidel.

  Input:
  A : La matriz de la que se busca el determinante

  Output:
det : El determinante de la matriz
  """
  #Para matrices de grado menor a 2
  n = A.shape[0]
  if n == 1:
    return A[0, 0]
  if n == 2:
    return A[0,0]*A[1,1] - A[0,1]*A[1,0]
  #Para matrices de grado igual o mayor a 3
  det = 0
  for i in range(n):
    B= np.delete(np.delete(A, 0, axis=0), i, axis=1) #Esto elimina la columna y la fila
    cofact = (-1) ** (2 + i) #Esto encuentra el simbolo del cofactor (2+i debido a que Python cuenta desde 0)
    det += cofact * A[0, i] * determinante(B) #Esto suma el valor de cada multipliación
  return det

In [37]:
A = np.random.rand(3, 3)
print(f'Matriz:\n {A}')
print(f'Determinante según Laplace: {determinante(A)}')
print(f'Determinante según numpy: {(la.det(A))}')

Matriz:
 [[0.41705619 0.94142317 0.48958471]
 [0.51324385 0.68891903 0.5159633 ]
 [0.11455419 0.65899469 0.75447996]]
Determinante según Laplace: -0.10698397233531382
Determinante según numpy: -0.10698397233531384


#3 Método de Gauss - Seidel

Sea \$A\in\mathbb{R}^{n\times n}\$ no singular y sea \$b\in\mathbb{R}^n\$.
Descomponga \$A\$ como

$$
A \;=\; D \;+\; L \;+\; U,
$$

donde

* \$D\$ es la matriz diagonal de \$A\$,
* \$L\$ es la parte estrictamente triangular inferior,
* \$U\$ es la parte estrictamente triangular superior.

El algoritmo de Gauss - Seidel reorganiza el sistema \$Ax=b\$ como

$$
x \;=\; (D+L)^{-1}\bigl(b \;-\; Ux\bigr),
$$

y genera la sucesión

$$
x_i^{(k+1)}
= \frac{1}{a_{ii}}
\Bigl(b_i - \sum_{j<i} a_{ij}\,x_j^{(k+1)} - \sum_{j>i} a_{ij}\,x_j^{(k)}\Bigr),
\qquad i=1,\dots,n.
$$

Implemente una función `gauss_seidel(A, b, tol=1e-7, max_iter=100)` que:
   * Realice las iteraciones hasta que
     $\lVert x^{(k+1)}-x^{(k)}\rVert_\infty<\text{tol}$
     o se alcance `max_iter`;
   * devuelva el vector solución aproximado \$x\$, el número de iteraciones realizadas y la norma del último residuo.

Incluya una documentación clara.

Luego,

   * Genere una matriz aleatoria \$5\times5\$ (por ejemplo, con `np.random.rand`) y un vector \$b\$ aleatorio.
   * Resuelva \$Ax=b\$ con su función; calcule el error relativo frente a `numpy.linalg.solve`.
   * Estime igualmente el error respecto a la solución obtenida mediante \$x=A^{-1}b\$ (usando `numpy.linalg.inv`).
   * Presente las normas de los residuos y los errores relativos.

In [38]:
def gauss_seidel(A, b, tol=1e-7, max_iter=100):
  """
  Resuelve el sistema lineal Ax = b usando el método iterativo de Gauss-Seidel.

  Input:
  A : La matriz que representa al sistema lineal.
  b : Solución del sistema lineal en forma de vector.
  tol : Tolerancia de la convergencia.
  max_iter : Número máximo de iteraciones.

  Output:
  x : Vector de coeficientes.
  iter : Número de iteraciones realizadas.
  res : Norma infinito del último residuo
  """
  n = len(b)
  x = np.zeros_like(b, dtype=float)
  iter = 0

  while iter < max_iter: #Esto mantiene las interacciones en el rango deseado
    x_old = np.copy(x)
    for i in range(n):
      sum_0 = sum(A[i, j] * x[j] for j in range(i)) #Esto hace la suma con el valor actual
      sum_1 = sum(A[i, j] * x_old[j] for j in range(i + 1, n)) #Esto hace la suma con el valor inmediatamente anterior
      x[i] = (b[i] - sum_0 - sum_1) / A[i, i] #Esto actualiza los valores de x
      if la.norm(x[i]-x[i-1]) < tol: #Esto revisa si ya se cumple el criterio de divergencia deseado
        break
    iter += 1

  res = b - A @ x
  res_norm = la.norm(res, ord=np.inf)

  return x, iter + 1, res_norm

In [42]:
A = np.random.rand(5, 5)
b= np.random.rand(5,1)

x, iter, res = gauss_seidel(A, b)

err=la.norm(x - la.solve(A,b))/la.norm(la.solve(A,b))
err_inv=la.norm(x - (la.inv(A)@b))/la.norm(la.inv(A)@b)

print(f'Matriz:\n {A}')
print(f'Vector b:\n {b}')
print(f'Vector solución:\n {x}')
print(f'Error según numpy.la: {err}')
print(f'Error según la inversa: {err_inv}')
#Los errores son casi iguales

Matriz:
 [[0.88185345 0.4707825  0.74205358 0.24689668 0.92098693]
 [0.86528914 0.94172191 0.08678333 0.97788323 0.452602  ]
 [0.59250253 0.86369959 0.60966019 0.11576185 0.40535501]
 [0.14139508 0.1085549  0.4370603  0.75080455 0.07503924]
 [0.70187788 0.61349553 0.62747232 0.48696895 0.4449782 ]]
Vector b:
 [[0.37782975]
 [0.54011472]
 [0.40975062]
 [0.10921528]
 [0.69265313]]
Vector solución:
 [[-1.59141062e+11]
 [ 6.09086413e+10]
 [-2.92441446e+10]
 [ 2.40472626e+10]
 [ 1.81964045e+11]]
Error según numpy.la: 69117619872.27577
Error según la inversa: 69117619872.2758


#4 Método de potencias para el valor propio dominante

Sea \$A\in\mathbb{R}^{n\times n}\$ diagonalizable con valor propio dominante \$\lambda\_{\max}\$ (en magnitud) y vector propio asociado \$v\_{\max}\$.

El método de potencias genera, a partir de un vector inicial \$q^{(0)}\neq 0\$, la sucesión

$$
q^{(k+1)} \;=\; \frac{A\,q^{(k)}}{\lVert A\,q^{(k)}\rVert_2},
\qquad
\lambda^{(k+1)} \;=\; (q^{(k+1)})^{\!\top} A\, q^{(k+1)},
$$

que converge a \$v\_{\max}/\lVert v\_{\max}\rVert\_2\$ y a \$\lambda\_{\max}\$ respectivamente, bajo hipótesis estándar.

Implemente `power_method(A, tol=1e-7, max_iter=1000)` que:

   * Acepte matrices reales cuadradas,
   * Devuelva \$\lambda\_{\max}\$, el vector propio normalizado \$v\_{\max}\$, el número de iteraciones y la última variación relativa de \$\lambda\$,
   * detenga la iteración cuando
     $\bigl|\lambda^{(k+1)}-\lambda^{(k)}\bigr|<\text{tol}\,|\lambda^{(k+1)}|$
     o se alcance `max_iter`.

Luego,
   * Genere una matriz simétrica aleatoria \$6\times6\$ (por ejemplo, \$A = (M+M^\top)/2\$ con \$M\$ aleatoria).
   * Aplique su `power_method` y compare \$\lambda\_{\max}\$ y \$v\_{\max}\$ con los resultados de `numpy.linalg.eig`.

In [43]:
def power_method(A, tol=1e-7, max_iter=1000):
  """
  Eleva una matriz A.

  Input:
  A : La matriz que se desea elevar.
  tol : Tolerancia de la convergencia.
  max_iter : Número máximo de iteraciones.

  Output:
  λ_new : Mayor valor propio.
  q_new : Vector propio.
  iter : Número de iteraciones realizadas.
  v_r : Variación relativa de λ.
  """
  n, m = A.shape #Esto se asegura de que la matriz sea cuadrada
  if n != m:
    raise ValueError('La matriz no es cuadrada')

  λ = 0
  iter=0
  q = np.random.rand(n) #Vector inicial aleatorio
  while iter < max_iter: #Esto mantiene las interacciones en el rango deseado
    q_new = (A @ q) / la.norm(A @ q) #Calculamos el nuevo vector q
    λ_new = np.transpose(q_new) @ A @ q_new #Calculamos el nuevo valor de lambda
    v_r=abs(λ_new - λ) #Calculamos la variación relativa de lambda
    if abs(λ_new - λ) < tol:
      return λ_new, q_new, iter+1,  abs(λ_new - λ)
      break
    elif iter == max_iter-1:
      raise RuntimeError('Se alcanzarón las maximas iteraciones posibles')
    iter+=1
    λ = λ_new

  return λ_new, q_new, iter, v_r

In [45]:
M = np.random.rand(6, 6)
A = (M + np.transpose(M)) / 2

λ_1, v1, i, v_r = power_method(A)
λ_2, v2 = la.eig(A)
idx_max = np.argmax(λ_2)

print(f'λ_max según power_method: {λ_1}')
print(f'v_max según power_method:\n {v1}')
print(f'Iteraciones: {i}')
print(f'Variación final: {v_r}')
print(f'λ_max según numpy: {λ_2[idx_max]}')
print(f'v_max según numpy:\n {v2[:, idx_max]}')

λ_max según power_method: 2.6103055590906608
v_max según power_method:
 [0.3646532  0.46037765 0.48276924 0.37716604 0.31998091 0.42115593]
Iteraciones: 9
Variación final: 1.793528214832918e-08
λ_max según numpy: 2.6103055620688473
v_max según numpy:
 [-0.3646662  -0.46039903 -0.48275766 -0.37713561 -0.31999264 -0.42115291]


#5

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [60]:
sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)
sigma_z = np.array([[1, 0], [0, -1]], dtype=complex)
I = np.array([[1, 0], [0, 1]],dtype=complex)

n=0
Bool=[]
while n<1000:
  L_0 = np.random.rand(2, 2) + 1j
  L = (L_0 + np.transpose(np.conjugate(L_0))) / 2
  a = np.trace(L @ sigma_x) / 2
  b = np.trace(L @ sigma_y) / 2
  c = np.trace(L @ sigma_z) / 2
  d = np.trace(L @ I) / 2
  L_ = a * sigma_x + b * sigma_y + c * sigma_z + d * I

  if np.allclose(L, L_) == False:
    print(f'La condición no se cumple')
    break
  else:
    n+=1
if n==1000:
  print(f'La condición se cumple')

La condición se cumple


# 6

Haga un breve resumen en Markdown de las funciones y métodos más relevantes para algebra lineal usando Python. Emplee ejemplos.