In [65]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
import numpy.linalg as nla
from IPython.display import display, Math

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Orly de Jesus Rivera Cruz
*Métodos computacionales*

---

#1
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [77]:
#Problema 1

A = np.random.randint(-99, 100, size=(3, 3))
B = np.random.randint(-99, 100, size=(3, 3))            #Nuestras tres matrices aleatorias
C = np.random.randint(-99, 100, size=(3, 3))

k = np.random.randint(-99, 100)                         #Una constante aleatoria

print("\nLa matriz A escogida al azar es:\n",A)
print("\nLa matriz B escogida al azar es:\n",B)
print("\nLa matriz C escogida al azar es:\n",C)

print()


display(Math(r"\mathbf{A}\mathbf{B} = \mathbf{B}\mathbf{A}"))

print( "---" , np.array_equal(  A@B , B@A  ) , "---" , "\n(Esto es FALSE generalmente)") #Indica que NO son iguales
print()

display(Math(r"(\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C})"))

print( "---" , np.array_equal(  (A@B)@C , A@(B@C)  ), "---" , )
print()

display(Math(r"\mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C}"))

print( "---" , np.array_equal(  A@(B+C) , A@B + A@C  ), "---" , )
print()

display(Math(r"(\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C}"))

print( "---" , np.array_equal(  (A+B)@C , A@C + B@C  ), "---" , )
print()

display(Math(r"(\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top"))

print( "---" , np.array_equal(  (A@B).T , B.T@A.T  ), "---" , )
print()

display(Math(r"\det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B})"))

print( "---" , la.det(A@B) == la.det(A)*la.det(B), "---" , "\n(Generalmente da FALSE debido a errores numericos)\n")
print( "Det(A@B) = " , la.det(A@B) , "\nDet(A)*Det(B) = " , la.det(A)*la.det(B) , "\n\nPor lo que en este caso redondearemos para que de TRUE")
print( round(la.det(A@B) , 2) == round(la.det(A)*la.det(B) , 2) , "(Vemos que con el redondeo ahora si da )" )
print()

display(Math(r"(\mathbf{A}^\top)^\top = \mathbf{A}"))

print( "---" , np.array_equal(  (A.T).T , A  ), "---" , )
print()

display(Math(r"(c\mathbf{A})^\top = c\mathbf{A}^\top"))

print( "---" , np.array_equal(  (k*A).T , k*(A.T)  ), "---" , )
print()

display(Math(r"(\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top"))

print( "---" , np.array_equal(  (A+B).T , A.T + B.T  ), "---" , )


print("\n\n\n")
print("----------Quedan demostradas todas las relaciones mostradas----------")


La matriz A escogida al azar es:
 [[-62 -95  35]
 [-61 -50 -36]
 [ 99 -66  60]]

La matriz B escogida al azar es:
 [[ 91   7   6]
 [ 98   6 -19]
 [  9  63 -69]]

La matriz C escogida al azar es:
 [[-92 -79  24]
 [-17  81 -14]
 [ 67  -9  59]]



<IPython.core.display.Math object>

--- False --- 
(Esto es FALSE generalmente)



<IPython.core.display.Math object>

--- True ---



<IPython.core.display.Math object>

--- True ---



<IPython.core.display.Math object>

--- True ---



<IPython.core.display.Math object>

--- True ---



<IPython.core.display.Math object>

--- False --- 
(Generalmente da FALSE debido a errores numericos)

Det(A@B) =  98376426720.00003 
Det(A)*Det(B) =  98376426720.00002 

Por lo que en este caso redondearemos para que de TRUE
True (Vemos que con el redondeo ahora si da )



<IPython.core.display.Math object>

--- True ---



<IPython.core.display.Math object>

--- True ---



<IPython.core.display.Math object>

--- True ---




----------Quedan demostradas todas las relaciones mostradas----------


#2

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [83]:
#Problema 2

def Det(A):

    """
    La funcion Det(A) nos devolvera el determinante de dicha matriz

    Entradas:
    A: Es una matriz cuadrada de tamaño n (Matriz nxn)

    Salidas:
    D: El determinante de la matriz (float)

    """

    if A.shape[0] != A.shape[1]:
        return "Su matriz no es cuadrada, no es posible sacar el determinante"
    else:
        pass

    n = A.shape[0]              #Numero de filas 
    D = 0

    if n > 1:
        
        for j in range(n):

            M = np.delete(np.delete(A, 1, axis=0), j, axis=1)           #Matriz sin la fila 1 y sin la columna j
            Signo = (-1)**(1+j)                                         #El signo dependiendo de j
            a = A[1,j]                                                  #La componente A[1,j]
            D += Det(M)*a*Signo                                         #Se suma iterativamente al determinante

    else:
        return A[0,0]                                                   #Si es un array 1x1 entonces regresamos el unico valor que hay
    
    return float(D)                                                     #Lo regresamos en float

A = np.random.randint(-99, 100, size=(5 , 5))                           #Generamos una matriz al azar 5x5

print("Determinante con nuestra funcion:",Det(A))                                                         
print("Determinante con scipy:",la.det(A))                                                               

print("\nPodemos percatarnos que nuestra funcion funciona increiblemente increible")

Determinante con nuestra funcion: 1173321633.0
Determinante con scipy: 1173321633.0

Podemos percatarnos que nuestra funcion funciona increiblemente increible


#3 Método de Gauss - Seidel

Sea \$A\in\mathbb{R}^{n\times n}\$ no singular y sea \$b\in\mathbb{R}^n\$.
Descomponga \$A\$ como

$$
A \;=\; D \;+\; L \;+\; U,
$$

donde

* \$D\$ es la matriz diagonal de \$A\$,
* \$L\$ es la parte estrictamente triangular inferior,
* \$U\$ es la parte estrictamente triangular superior.

El algoritmo de Gauss - Seidel reorganiza el sistema \$Ax=b\$ como

$$
x \;=\; (D+L)^{-1}\bigl(b \;-\; Ux\bigr),
$$

y genera la sucesión

$$
x_i^{(k+1)}
= \frac{1}{a_{ii}}
\Bigl(b_i - \sum_{j<i} a_{ij}\,x_j^{(k+1)} - \sum_{j>i} a_{ij}\,x_j^{(k)}\Bigr),
\qquad i=1,\dots,n.
$$

Implemente una función `gauss_seidel(A, b, tol=1e-7, max_iter=100)` que:
   * Realice las iteraciones hasta que
     $\lVert x^{(k+1)}-x^{(k)}\rVert_\infty<\text{tol}$
     o se alcance `max_iter`;
   * devuelva el vector solución aproximado \$x\$, el número de iteraciones realizadas y la norma del último residuo.

Incluya una documentación clara.

Luego,

   * Genere una matriz aleatoria \$5\times5\$ (por ejemplo, con `np.random.rand`) y un vector \$b\$ aleatorio.
   * Resuelva \$Ax=b\$ con su función; calcule el error relativo frente a `numpy.linalg.solve`.
   * Estime igualmente el error respecto a la solución obtenida mediante \$x=A^{-1}b\$ (usando `numpy.linalg.inv`).
   * Presente las normas de los residuos y los errores relativos.

In [90]:
#Problema 3

def gauss_seidel(A, b, tol=1e-7, max_iter=100):
    """
    Nuestra funcion Gauss_Seidel funciona de manera iterativa para encontrar la solucion a nuestra matriz cuadrada (Si cumple las condiciones necesarias)

    Entradas:
    A: La matriz asociada a nuestro problema (Matriz)
    b: El vector resultante de nuestro problema (Vector)

    Salidas:
    x_new: El vector solucion con tolerancia establecida (Vector)
    m: Numero de iteracion en la cual convergio (Numero int)
    Error: La norma de nuestro residuo (Numero Float)

    """
    if A.shape[0] != A.shape[1]:
        return "Su matriz no es cuadrada, no es posible sacar el determinante"
    else:
        pass

    n = len(b)                                              #Longitud de nuestra matriz cuadrada
    x = np.zeros_like(b, dtype = float)                     #Vector solucion antiguo
    x_new = np.zeros_like(x)                                #Vector solucion nuevo

    for m in range(1 , max_iter + 1):                       #Limite de iteraciones
        for i in range(n):                                  #Recorremos filas
            Suma_1 = 0.0
            Suma_2 = 0.0
            for j in range(n):                              #Recorremos columnas
                if j < i :                                  #Vamos haciendo las sumatorias aparte para despues sumarlas al final
                    Suma_1 += A[i,j]*x_new[j]
                elif j == i:
                    pass
                else:
                    Suma_2 += A[i,j]*x[j]
            x_new[i] = (b[i] - Suma_1 - Suma_2)/(A[i,i])    #Reemplazamos la componente i de nuestro x_new
        error = np.linalg.norm(x_new - x, ord=np.inf)       #Calculamos el error
        if error < tol:                                     #Evaluamos convergencia
            return x_new , m , error    
        else:                                               #Si no se cumple convergencia reemplazamos el vector antiguo por el nuevo
            x = x_new.copy()
    
    print("Una disculpa pero no convergio, porfavor revise que sea diagonalmente dominante o simetrica positiva.")  #Si no converge

#Matriz 5x5 aleatoria

D = np.random.randint(-99, 100, size=(5, 5))
d = np.random.randint(-99, 100, size=(5, 1))

def Dia_Dom(A):                         #Creamos uan funcion para que la diagonal domine
    for i in range(5):                  #Si no cumple la condicion en cada componente le sumanos 10 unidades hasta que cumpla
        Suma = 0.0
        for j in range(5):
            if i != j :
                Suma += abs(A[i,j])
            else:
                pass
        
        if A[i,i] > Suma:
            pass
        else:
            while A[i,i] < Suma:
                A[i,i] += 10
    return A

D = Dia_Dom(D)

print("Nuestra matriz D aleatoria con la diagonal dominante es de:\n",D)

Aprox , Iter , Error = gauss_seidel(D,d)    #Evaluamos nuestra función

print("\nNuestro vector aproximado es:\n" , Aprox)
print("Convergio en la iteracion numero",Iter)
print("El ultimo residuo de la funcion fue de:",Error)

Error_s = np.linalg.norm(Aprox - nla.solve(D,d), ord=np.inf)
Error_i = np.linalg.norm(Aprox - nla.inv(D)@d, ord=np.inf)

print("\nEl error relativo con respecto a numpy es de:",Error_s)
print("El error relativo con respecto a la inversa por el vector resultante es de:",Error_i)

Nuestra matriz D aleatoria con la diagonal dominante es de:
 [[283 -79  82 -79  35]
 [ -3 218  78  36  95]
 [ 23  91 163  11  35]
 [-51  -3 -64 172 -45]
 [ 87  27 -37  35 195]]

Nuestro vector aproximado es:
 [[ 0.34879308]
 [ 0.56157054]
 [-0.8335917 ]
 [-0.6917762 ]
 [-0.0468622 ]]
Convergio en la iteracion numero 20
El ultimo residuo de la funcion fue de: 5.748437559294217e-08

El error relativo con respecto a numpy es de: 4.2567598335097045e-08
El error relativo con respecto a la inversa por el vector resultante es de: 4.256759844611935e-08


#4 Método de potencias para el valor propio dominante

Sea \$A\in\mathbb{R}^{n\times n}\$ diagonalizable con valor propio dominante \$\lambda\_{\max}\$ (en magnitud) y vector propio asociado \$v\_{\max}\$.

El método de potencias genera, a partir de un vector inicial \$q^{(0)}\neq 0\$, la sucesión

$$
q^{(k+1)} \;=\; \frac{A\,q^{(k)}}{\lVert A\,q^{(k)}\rVert_2},
\qquad
\lambda^{(k+1)} \;=\; (q^{(k+1)})^{\!\top} A\, q^{(k+1)},
$$

que converge a \$v\_{\max}/\lVert v\_{\max}\rVert\_2\$ y a \$\lambda\_{\max}\$ respectivamente, bajo hipótesis estándar.

Implemente `power_method(A, tol=1e-7, max_iter=1000)` que:

   * Acepte matrices reales cuadradas,
   * Devuelva \$\lambda\_{\max}\$, el vector propio normalizado \$v\_{\max}\$, el número de iteraciones y la última variación relativa de \$\lambda\$,
   * detenga la iteración cuando
     $\bigl|\lambda^{(k+1)}-\lambda^{(k)}\bigr|<\text{tol}\,|\lambda^{(k+1)}|$
     o se alcance `max_iter`.

Luego,
   * Genere una matriz simétrica aleatoria \$6\times6\$ (por ejemplo, \$A = (M+M^\top)/2\$ con \$M\$ aleatoria).
   * Aplique su `power_method` y compare \$\lambda\_{\max}\$ y \$v\_{\max}\$ con los resultados de `numpy.linalg.eig`.

In [96]:
#Problema 4

def power_method(A , tol=1e-7 , max_iter=1000):

    """
    Nuestra funcion power_method nos permite encontrar el valor propio DOMINANTE con su respectivo vector propio asociado

    Entradas:
    A: Matriz simetrica real (Matriz)

    Salidas:
    q_new: El vector propio asociado a el valor propio DOMINANTE (Vector)
    Y_new: El valor propio DOMINANTE (Numero float)
    m: El numero de iteracion donde convergio (Numero Int)
    error: El residuo relativo de los valores propios (Numero float)

    """

    if (A != A.T).all():                                                                                    #Verificamos si la matriz es simetrica 
        return "Una disculpa pero su matriz no es simetrica y no podemos usar este metodo"
    else:
        pass

    n = len(A[0])                                                                                   #Guardamos el largo de las filas de la matriz
    q = np.ones(n , dtype=float)                                                                    #Vector propio antiguo
    Y = 0                                                                                           #Valor propio antiguo
    for m in range(1,max_iter+1):                                                                   #Numero de iteraciones
        Numerador = A@q                                                                             #Vector por el producto matricial
        Denominador = la.norm(A@q, ord=2)                                                           #Norma 2 de el numerador
        q_new = Numerador / Denominador                                                             #Nuevo vector propio
        Y_new = (q_new.T)@A@q_new                                                                   #Nuevo valor propio

        error = abs(Y_new - Y)                                                                      #Calculamos el error de los valores propios
        if error < tol:                                                                             #Evaluamos convergencia
            return q_new , Y_new , m , error
        else:                                                                                       #Si no cumple convergencia reemplazamos los valores
            q = q_new.copy()
            Y = Y_new
    return "Se alcanzo el maximo de iteraciones"

A = np.random.randint(-99, 100, size=(6, 6))                                                        #Generamos uan matriz 6x6 aleatoria

A = (A + A.T)/2                                                                                     #La convertimos en una simetrica

Vector , Valor , Iter , Error = power_method(A)                                                     #Evaluamos nuestra función

print("La convergencia se alcanzo a las",Iter,"Iteraciones")
print("Su error fue de",Error)

print("El vector propio asociado es:",Vector)
print()
print("El valor propio DOMINANTE es:",Valor)
print("\n")

Valores, Vectores = nla.eig(A)

i = np.argmax(np.abs(Valores))                                                                      #Encontramos el indice de el valor que es dominante

Valor_dominante = Valores[i]

Vector_asociado = Vectores[:, i]

print("El vector propio asociado mediante numpy es de:",Vector_asociado)
print("El valor propio dominante mediante numpy es de:",Valor_dominante)


La convergencia se alcanzo a las 21 Iteraciones
Su error fue de 4.0636336962052155e-08
El vector propio asociado es: [-0.40593727 -0.66012818  0.46464887  0.02420225 -0.05865532 -0.42369912]

El valor propio DOMINANTE es: -166.59231604019283


El vector propio asociado mediante numpy es de: [ 0.40593224  0.66013221 -0.46464617 -0.02420211  0.05866066  0.42369989]
El valor propio dominante mediante numpy es de: -166.59231606069397


#5

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [125]:
#Problema 5

x = np.array([[0,1],[1,0]])
y = np.array([[0,-1j],[1j,0]])
z = np.array([[1,0],[0,-1]])
I = np.array([[1,0],[0,1]])

al , be , de, th = np.random.uniform(-99, 100, 4)                                   #Generamos numeros reales para una hermitiana 2x2 general

Hermi = np.array([[al , be + th*1j] , [be - 1j*th , de]])                           #Hermitiana 2x2

"""
Mediante calculo analitico obtenemos que nuestra matriz hermitiana debe que igualar a la siguiente matriz:

(c+d      a-bi)
(a+bi      d-c)

Por lo que obtenemos cuatro ecuaciones:

al = c + d                      (1)
be + i*th = a-bi                (2)
be - i*th = a+bi                (3)
de = d - c                      (4)

Si despejamos "d" de la ecuacion (4) obtenemos que:

de + c = d

Y si reemplazamos en la ecuacion (1) obtenemos:

al = 2c + de
c = (al - de)/2

Si reemplazamos c nuevamente en (4) obtenemos:

de = d - (al - de)/2
d = (de + al)/2

Por lo que ya obtenemos de manera analitica c y d

Para encontrar a y b tenemos que resolver el sistema de ecuaciones:

a - bi = be + i*th
a + bi = be - i*th

Que en forma matricial es:

(1   -i)  (be + i*th)
(1   +i)  (be - i*th)

Resolviendo de forma analitica para evitar errores numericos obtenemos que los valores de a y b respectivamente son:

a = be
b = -th

Ahora vamos a comprobar nuestros resultados

"""

#Escribimos nuestros valores

a = be
b = -th
c = (al - de)/2
d = (de + al)/2

print("\nMatriz hermitiana aleatoria")
print(Hermi)
print("\nParte derecha de la ecuación")
print(a*x + b*y + c*z + d*I)

print("\n",Hermi == a*x + b*y + c*z + d*I) #Comprobamos si se cumple la igualdad

print("\nComo nos podemos dar cuenta la igualdad se cumple para todas las matrices hermitianas (A no ser de que ocurra algun error numerico pequeño)")


Matriz hermitiana aleatoria
[[-81.6926283  +0.j         -17.74873168+66.94945314j]
 [-17.74873168-66.94945314j -42.59194391 +0.j        ]]

Parte derecha de la ecuación
[[-81.6926283  +0.j         -17.74873168+66.94945314j]
 [-17.74873168-66.94945314j -42.59194391 +0.j        ]]

 [[ True  True]
 [ True False]]

Como nos podemos dar cuenta la igualdad se cumple para todas las matrices hermitianas (A no ser de que ocurra algun error numerico pequeño)


# 6

Haga un breve resumen en Markdown de las funciones y métodos más relevantes para algebra lineal usando Python. Emplee ejemplos.

## Álgebra Lineal con NumPy

Generalmente usamos el modulo de numpy dirigido para algebra lineal para nuestras funciones mas importantes, pero primero iniciaremos con las bases que son crear las matrices y los vectores con los arrays de numpy, ya que estos estan vectorizados

`np.array([])` ---> Con esta podemos creas todos nuestros vectores y matrices

Otra muy util para probar distintos casos es generar matrices o vectores aleatorios con

`np.random.randint(a,b, size=(n,m))` ---> Crea matrices aleatorias con valroes entre a y b

A veces necesitamos simplemente arrays especiales para reemplazar, sumar o multiplicar aprovechando el hecho de que son vectores por lo que utilizamos

- `np.zeros(n,m)` ---> Genera una matriz nxm llena de ceros  
- `np.zeros_like(x)` ---> Genera una matriz llena de ceros como alguna otra "x"  
- `np.ones(n,m)` ---> Genera una matriz nxm llena de unos  
- `np.ones_like(x)` ---> Genera una matriz llena de unos como alguna otra "x"  
- `np.eye(n)` ---> Genera una matriz identidad de tamaño n  

Si tenemos alguna matriz `"A"` podemos jugar con ella con las siguientes funciones:

- `A.T` ---> La matriz transpuesta de A  
- `A.conjugate()` ---> La matriz conjugada de A  
- `np.diag(A)` ---> La diagonal de la matriz  
- `np.trace(A)` ---> La traza de la matriz  
- `nla.norm(A)` ---> Distintos tipos de normas  
- `nla.det(A)` ---> El determinante  

Si tenemos dos matrices `"A"` y `"B"` podemos realizar operaciones entre ellas:

- `A + B` o `A - B` ---> Puedes sumar o restar matrices (Tienen que ser del mismo tamaño)  
- `A * B` o `A / B` ---> Puedes multiplicar o dividir componente a componente las matrices (Tienen que ser del mismo tamaño)  
- `A @ B` ---> Puedes realizar producto matricial entre matrices o producto punto entre vectores (Cumpliendo que el len(A[j]) = len(B[i]))  

Para cosas un poquito más avanzadas también tenemos funciones para autovalores, inversas y resolver sistemas del tipo Ax = b:

- `nla.inv(A)` ---> Devuelve la inversa de la matriz, útil para resolver sistemas  
- `nla.solve(A, b)` ---> Devuelve el vector solución de ese sistema  
- `nla.eig(A)` ---> Devuelve los autovalores y autovectores de la matriz, útil para diagonalizar  
- `np.isclose(A,B)` ---> Verifica si las matrices se acercan dentro de una tolerancia establecida, útil para errores numéricos


In [141]:
#EJEMPLOS

#Creacion de matrices y vectores aleatorios
A = np.random.randint(-10,10, size=(5,5))
B = np.random.randint(-10,10, size=(5,5))
b = np.random.randint(-10,10, size=(5,1))

print("MATRIZ A:\n",A ,"\n\n","MATRIZ B:\n", B ,"\n\n","Vector b:\n", b)

#Matrices llena de ceros o unos

A_0 = np.zeros_like(A)
B_1 = np.ones_like(B)

print("\nMATRIZ A LLENA DE CEROS:\n",A_0 ,"\n\n","MATRIZ B LLENA DE UNOS:\n", B_1 )

#Funciones y metodos basicos

AT = A.T
Conjugada = A.conjugate()
Diagonal = np.diag(A)
Traza = np.trace(A)
Norma = nla.norm(b , 2)
Determinante = nla.det(A)

print("\nMATRIZ A CONJUGADA (La misma por ser real):\n",Conjugada ,"\n\n","VECTOR PLANO DE LA DIAGONAL DE A:\n"
, Diagonal ,"\n\n","MATRIZ A TRANSPUESTA:\n", AT)

print("\nEl determinante de la matriz A es:", Determinante)
print("La norma euclidiana de el vector b es:", Norma)
print("La traza de la matriz A es igual a:",Traza)

#Algunas operaciones basicas

print("La suma de las matrices A,B es:\n",A+B)
print("La multiplicacion de las matrices A,B elemento por elemento es:\n",A*B)
print("El producto matricial de las matrices A,B es:\n",A@B)

#Funciones un poquito mas avanzadas

print("\nLa inversa de la funcion B es de:\n",nla.inv(B))

print("\nEl vector solucion de la matriz Bx = b es igual a:\n",nla.solve(B,b))

print("Podriamos compararla con la solucion de la inversa con np.isclose\n",np.isclose( nla.solve(B,b) , nla.inv(B)@b))

Valores , Vectores = nla.eig(A)
print("Por ultimo los valores y vectores propios de la matriz A son\n")
print("Valores = " , Valores)
print("Vectores = " , Vectores)



MATRIZ A:
 [[ -7   3  -7   6   0]
 [  6  -2  -9  -8  -5]
 [  4  -3   9   6  -2]
 [ -4  -9 -10  -6   8]
 [-10   1   4   4   0]] 

 MATRIZ B:
 [[  9  -5   1  -8   2]
 [ -1   3   8   5   7]
 [-10   0  -2   9  -9]
 [ -1   9   3   1  -9]
 [  4  -9  -8  -7 -10]] 

 Vector b:
 [[-7]
 [-3]
 [-6]
 [ 6]
 [ 4]]

MATRIZ A LLENA DE CEROS:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] 

 MATRIZ B LLENA DE UNOS:
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

MATRIZ A CONJUGADA (La misma por ser real):
 [[ -7   3  -7   6   0]
 [  6  -2  -9  -8  -5]
 [  4  -3   9   6  -2]
 [ -4  -9 -10  -6   8]
 [-10   1   4   4   0]] 

 VECTOR PLANO DE LA DIAGONAL DE A:
 [-7 -2  9 -6  0] 

 MATRIZ A TRANSPUESTA:
 [[ -7   6   4  -4 -10]
 [  3  -2  -3  -9   1]
 [ -7  -9   9 -10   4]
 [  6  -8   6  -6   4]
 [  0  -5  -2   8   0]]

El determinante de la matriz A es: 104430.0000000001
La norma euclidiana de el vector b es: 12.083045973594572
La traza de la matriz A es igual a: -6
L