In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
import sympy as sp

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Martín Calvo D
*Métodos computacionales*

---

#1
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [138]:
from math import isclose
n=0
for k in range(10000):
  A=np.random.randint(-10000,10000,size=(3,3))
  B=np.random.randint(np.random.randint(-20500,0),np.random.randint(0,20500),size=(3,3))
  C=np.random.randint(np.random.randint(-10000,0),np.random.randint(0,10000),size=(3,3))
  a=sp.Matrix(A)
  b=sp.Matrix(B)

  AB=A@B
  BA=B@A

  bul=np.ones_like(AB, dtype=bool)
  suma=0
  for i in range(3):
    for j in range(3):
      suma+=(abs(AB[i,j]-BA[i,j]))
  if np.isclose(suma,0)==True: #Esta es la forma que se me ocurrió de comparar todos los elementos de ambas matrices, porque toca demostrar que no son iguales
    print("En el caso específico de estas dos matrices, el producto es conmutativo")

  abC=(A@B)@C
  Abc=A@(B@C)
  bul=np.isclose(abC,Abc)
  for i in range(3):
    for j in range(3):
      if bul[i,j]==False: #Para este y el resto de ejemplos es suficiente que uno sea falso para que no se cumpla, pues se quiere demostrar igualdad
        sp.pprint(a)
        sp.pprint(b)
        print("Para el caso de estas dos matrices, el producto matricial no es asociativo")
        n+=1

  distAbc=A@(B+C)
  AbAc=A@B+A@C
  bul=np.isclose(distAbc,AbAc)
  for i in range(3):
    for j in range(3):
      if bul[i,j]==False: #El resto siguen la misma lógica, de encontrar un False en el arreglo que entrega el isclose
        sp.pprint(a)
        sp.pprint(b)
        print("Para el caso de estas dos matrices, el producto matricial no es distributivo")
        n+=1

  abT=(A@B).T
  aTbT=B.T@A.T
  bul=np.isclose(abT,aTbT)
  for i in range(3):
    for j in range(3):
      if bul[i,j]==False:
        sp.pprint(a)
        print("")
        sp.pprint(b)
        print("Para el caso de estas dos matrices, la transpuesta del producto no es igual al producto de las transpuestas planteado")
        n+=1

  detAB=la.det(A@B)
  detAdetB=la.det(A)*la.det(B)
  bul=np.isclose(detAB,detAdetB)
  if bul==False:
    sp.pprint(a)
    sp.pprint(b)
    print("Para el caso de estas dos matrices, el determinante de un producto no es igual al producto de determinantes")
    n+=1

  bul=np.isclose(A,(A.T).T)
  for i in range(3):
    for j in range(3):
      if bul[i,j]==False:
        sp.pprint(a)
        sp.pprint(b)
        print("Para el caso de esta matriz, la transpuesta de la transpuesta no es igual a la matriz")
        n+=1

  q=np.random.randint(-1000,1000)
  p=np.random.randint(1,10000)
  alpha=q/p #Este es un escalar arbitrario
  bul=np.isclose(alpha*(A.T),(alpha*A).T)
  for i in range(3):
    for j in range(3):
      if bul[i,j]==False:
        sp.pprint(a)
        sp.pprint(b)
        print("Para el caso de esta matriz, la transpuesta por un escalar no es igual a la matriz por un escalar transpuesta")
        n+=1

  bul=np.isclose(A.T+B.T,(A+B).T)
  for i in range(3):
    for j in range(3):
      if bul[i,j]==False:
        sp.pprint(a)
        sp.pprint(b)
        print("Para el caso de estas dos matrices, la suma de las transpuestas no es igual a la transpuesta de las sumas")
        n+=1

print(f"En 10000 iteraciones, se encontraron {n} excepciones a los enunciados")

En 10000 iteraciones, se encontraron 0 excepciones a los enunciados


#2

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( M_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [ ]:
n=np.random.randint(2,5)
A=np.random.randint(-50,50, size=(n,n))
def dt(A):
  """
  Calcula el determinante por la primera fila, usando recursividad y el Teorema de Laplace

  Inputs
    A: matriz cuadrada

  Outputs
    suma: El determinante de la matriz
  """
  if len(A[0])==1:

    return A[0,0]
  suma=0
  for k in range(len(A[0])):
    menor=np.delete(A,0,0)
    menor=np.delete(menor,k,1)
    suma+=((-1)**(2+k))*A[0,k]*dt(menor)
  return suma
dt(A)-la.det(A)
print(f"El determinante de una matriz arbitraria obtenido de esta forma es {dt(A)}, con la.det es {la.det(A)}, el error es de {abs((dt(A)-la.det(A))/la.det(A))}")

El determinante de una matriz arbitraria obtenido de esta forma es 474, con la.det es 474.0, el error es de 0.0


#3 Método de Gauss - Seidel

Sea \$A\in\mathbb{R}^{n\times n}\$ no singular y sea \$b\in\mathbb{R}^n\$.
Descomponga \$A\$ como

$$
A \;=\; D \;+\; L \;+\; U,
$$

donde

* \$D\$ es la matriz diagonal de \$A\$,
* \$L\$ es la parte estrictamente triangular inferior,
* \$U\$ es la parte estrictamente triangular superior.

El algoritmo de Gauss - Seidel reorganiza el sistema \$Ax=b\$ como

$$
x \;=\; (D+L)^{-1}\bigl(b \;-\; Ux\bigr),
$$

y genera la sucesión

$$
x_i^{(k+1)}
= \frac{1}{a_{ii}}
\Bigl(b_i - \sum_{j<i} a_{ij}\,x_j^{(k+1)} - \sum_{j>i} a_{ij}\,x_j^{(k)}\Bigr),
\qquad i=1,\dots,n.
$$

Implemente una función `gauss_seidel(A, b, tol=1e-7, max_iter=100)` que:
   * Realice las iteraciones hasta que
     $\lVert x^{(k+1)}-x^{(k)}\rVert_\infty<\text{tol}$
     o se alcance `max_iter`;
   * devuelva el vector solución aproximado \$x\$, el número de iteraciones realizadas y la norma del último residuo.

Incluya una documentación clara.

Luego,

   * Genere una matriz aleatoria \$5\times5\$ (por ejemplo, con `np.random.rand`) y un vector \$b\$ aleatorio.
   * Resuelva \$Ax=b\$ con su función; calcule el error relativo frente a `numpy.linalg.solve`.
   * Estime igualmente el error respecto a la solución obtenida mediante \$x=A^{-1}b\$ (usando `numpy.linalg.inv`).
   * Presente las normas de los residuos y los errores relativos.

In [501]:
def gauss_seidel(A, b, tol=1e-7, maxiter=100):
  """
  Resuelve un sistema de la forma AX=b usando el método de gauss_seidel

  Entradas
    A: matriz
    b: vector solución

  Salida
    xnext: vector x
 """
  x=np.zeros_like(b,dtype=float)
  xnext=np.zeros_like(b,dtype=float)

  for k in range(maxiter):
    for i in range(len(xnext)):
      mayores=0  #defino las sumas cuando j es menor o mayor que i
      menores=0
      for j in range(len(xnext)):
        if j>i:
          mayores+=A[i,j]*x[j]
        if j<i:
          menores+=A[i,j]*xnext[j]
      xnext[i]=(1/A[i,i])*(b[i]-menores-mayores)

    dif= la.norm(xnext-x,ord=np.inf) #la forma de comparar con la última iteración

    if dif<tol:
      return xnext

    x=xnext.copy() #me estaba loco porque en lugar de estar haciendo la copia estaba poniendo x=xnext, y al parecer eso hace que explote todo, x se volvía 2 vectores en uno solo, estaba rarísimo. .copy() lo resolvió
  print("Demasiadas iteracioens")




#A=np.random.randint(-10,10, size=(5,5))*np.random.rand()
#b=np.random.rand(5)

#gs=gauss_seidel(A,b)

print("Al parecer Gauss-Seidel es relativamente dificil que converja, entonces hacer matrices aleatorias con random.rand o random.randint difícilmente van a dar un resultado, casi siempre tiran error o no convergen")

A = np.random.rand(5,5)
for i in range(len(A[0])):
  A[i,i]=np.random.randint(10,1000) #Según lo que averigué, el método solo converge cuando hay valores más grandes en la diagonal, entonces hice esto para que siempre converja

b=np.array([np.random.rand(), np.random.rand(), np.random.rand(), np.random.rand(), np.random.rand()], dtype=float)*np.random.randint(-100,100) #lo hice así porque el rand y el randint dan unas dimensiones que joden mi función o las de numpy

gs=gauss_seidel(A,b)

Ainv=la.inv(A)
inb=Ainv@b

lan=la.solve(A,b)

print(gs, inb, lan) #Los vectores x

print(f"El error respecto la.solve es {abs(la.norm(gs)-la.norm(lan))/la.norm(lan):.2e}")
print(f"El error respecto al producto de la inversa es {abs(la.norm(gs)-la.norm(inb))/la.norm(inb):.2e}")

Al parecer Gauss-Seidel es relativamente dificil que converja, entonces hacer matrices aleatorias con random.rand o random.randint difícilmente van a dar un resultado, casi siempre tiran error o no convergen
[-0.11436067 -0.20727576 -0.59925932 -0.02963942 -0.08264911] [-0.11436067 -0.20727576 -0.59925932 -0.02963942 -0.08264911] [-0.11436067 -0.20727576 -0.59925932 -0.02963942 -0.08264911]
El error respecto la.solve es 1.16e-13
El error respecto al producto de la inversa es 1.15e-13


#4 Método de potencias para el valor propio dominante

Sea \$A\in\mathbb{R}^{n\times n}\$ diagonalizable con valor propio dominante \$\lambda\_{\max}\$ (en magnitud) y vector propio asociado \$v\_{\max}\$.

El método de potencias genera, a partir de un vector inicial \$q^{(0)}\neq 0\$, la sucesión

$$
q^{(k+1)} \;=\; \frac{A\,q^{(k)}}{\lVert A\,q^{(k)}\rVert_2},
\qquad
\lambda^{(k+1)} \;=\; (q^{(k+1)})^{\!\top} A\, q^{(k+1)},
$$

que converge a \$v\_{\max}/\lVert v\_{\max}\rVert\_2\$ y a \$\lambda\_{\max}\$ respectivamente, bajo hipótesis estándar.

Implemente `power_method(A, tol=1e-7, max_iter=1000)` que:

   * Acepte matrices reales cuadradas,
   * Devuelva \$\lambda\_{\max}\$, el vector propio normalizado \$v\_{\max}\$, el número de iteraciones y la última variación relativa de \$\lambda\$,
   * detenga la iteración cuando
     $\bigl|\lambda^{(k+1)}-\lambda^{(k)}\bigr|<\text{tol}\,|\lambda^{(k+1)}|$
     o se alcance `max_iter`.

Luego,
   * Genere una matriz simétrica aleatoria \$6\times6\$ (por ejemplo, \$A = (M+M^\top)/2\$ con \$M\$ aleatoria).
   * Aplique su `power_method` y compare \$\lambda\_{\max}\$ y \$v\_{\max}\$ con los resultados de `numpy.linalg.eig`.

In [422]:
def power_method(A, tol=1e-7, maxiter=1000):
  """
  Entrega el vector propio dominante de una matriz normalizado, así como el valor propio dominante, usando método dde potencias

  Inputs
    A:Matriz real nxn
    tol: tolerancia
    maxiter máximo de iteraciones

  Outputs
    landanext: valor propio dominante normalizado
    qnext: vector propio dominante
    k+1: cantidad de iteraciones necesarias para la convergencia
    (abs(landanext-landa)/landa)*100: ülitma variación relativa en porcentaje
  """
  if A.dtype!=float:
    raise ValueError("la matriz debe ser real") #Filtro para que todas las matrices sean reales
  if len(A[0])!=len(A[1]):
    raise ValueError("La matriz debe ser cuadrada")
  q=np.ones_like(A[0])
  qnext=np.ones_like(q)
  landa=1
  for k in range(maxiter):
    v=A@q
    norma=la.norm(A@q, ord=2)
    qnext=v/norma
    landanext=qnext.T@A@qnext
    if abs(landanext-landa)<tol:
      return landanext,qnext,k+1, (abs(landanext-landa)/landa)*100
    landa=landanext
    q=qnext.copy()
  print("Demasiadas iteraciones")

In [492]:
M=np.random.rand(6,6)*np.random.randint(-50,50)
A=M+M.T

vplinalg=1*la.eig(A)[1].T[0] #Esa cantidad de índices para que me de el vector que quiero, los vectores propios son las columnas de la matriz que entrega eig
lplinalg=float(la.eig(A)[0][0])


vmax=power_method(A)[1]
landamax=power_method(A)[0]

if vplinalg[0]*vmax[0]<0:
  vplinalg=-vplinalg #Un truquito para que el error no sea del 200%, el signo no es relevante cuando se habla de vectores propios

print("A=")
print(A)
print("")
print(f"Para la matriz simétrica A, con el método encontramos el valor propio dominante {landamax:.2e}, con la.eig el valor propio dominante es {lplinalg:.2e}") #Las amtrices simétricas siempre tienen valores propios reales entonces no hay problema con mocharle ese pedazo
print(f"El error es de {abs(landamax-(lplinalg))/(lplinalg)*100:.2e} %")
print("")
vspl=sp.Matrix(vplinalg)
vspm=sp.Matrix(vmax)
print("El vector obtenido con el método fue")
print("")
sp.pprint(vspm)
print("")
print("El vector obtenido con linalg.eig fue")
print("")
sp.pprint(vspl)
print("")
print(f"El error es de {abs(la.norm(vplinalg-vmax))/la.norm(vplinalg)}")




print("")
print("")
print("")

A=
[[ 5.82685315  7.05504174  0.28708902  7.66613651 14.86064525  7.85597008]
 [ 7.05504174 15.75305453 11.78251026  4.27626018 18.01988725 18.95571446]
 [ 0.28708902 11.78251026 20.76978554 11.14091255 10.8493744   6.02236218]
 [ 7.66613651  4.27626018 11.14091255  1.01957585 18.68937228 12.9822339 ]
 [14.86064525 18.01988725 10.8493744  18.68937228 13.94884085  2.43296401]
 [ 7.85597008 18.95571446  6.02236218 12.9822339   2.43296401  9.77802624]]

Para la matriz simétrica A, con el método encontramos el valor propio dominante 6.44e+01, con la.eig el valor propio dominante es 6.44e+01
El error es de 6.32e-09 %

El vector obtenido con el método fue

⎡0.284117354336267⎤
⎢                 ⎥
⎢0.496665777214792⎥
⎢                 ⎥
⎢0.401905620667756⎥
⎢                 ⎥
⎢0.360024585964922⎥
⎢                 ⎥
⎢0.498169976163893⎥
⎢                 ⎥
⎣0.365077086563789⎦

El vector obtenido con linalg.eig fue

⎡0.284116191988808⎤
⎢                 ⎥
⎢0.496662978382678⎥
⎢                 ⎥
⎢

/tmp/ipython-input-652132627.py:5: ComplexWarning: Casting complex values to real discards the imaginary part
  lplinalg=float(la.eig(A)[0][0])


#5

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [ ]:
x=np.array([[0,1],
            [1,0]])

y=np.array([[0,-1j],
            [1j,0]])

z=np.array([[1,0],
            [0,-1]]) #Finalmente no las terminé usando pero las dejo enunciadas

I=np.eye(2)

def eshermit(A):
  """
  Recibe una matriz cuadrada y regresa un True o False
  True si es Hermítica
  False si no lo es
  """
  Adagger=A.conj().T
  bul=np.isclose(A,Adagger)
  for i in bul:
    for j in i:
      if j!=True:
        return False
  return True #Si llega acá significa que fue por todos y cada uno y solo encontró True


n=0
for i in range(100000): #Vamos a revisar 100000 iteraciones y ver que no haya ninguna excepción
  a=np.random.randint(-10000,10000)*np.random.rand()
  b=np.random.randint(-10000,10000)*np.random.rand()
  c=np.random.randint(-10000,10000)*np.random.rand()
  d=np.random.randint(-10000,10000)*np.random.rand()
  A=np.array([[c+d,a-b*1j],
            [a+b*1j,-c+d]],dtype=complex) #La combinación lineal de las matrices usando valores aleatorios de a,b,c,d
  if eshermit(A)==False: #Si alguna combinación no resulta en una hermítica demostrará que no necesariamente una combinación de esa forma resulta en una hermítica, y por ende no todas las Hermíticas tienen esa forma
    n+=1
    print("Se rompieron las matemáticas llamen a Dios")

print(f"Tras 100000 iteraciones con valores de a,b,c,d aleatorios, se encontraron {n} combinaciones lineales de las matrices de Pauli que no resultaran en una Hermítica")



Tras 100000 iteraciones con valores de a,b,c,d aleatorios, se encontraron 0 combinaciones lineales de las matrices de Pauli que no resultaran en una Hermítica


# 6

##Haga un breve resumen en Markdown de las funciones y métodos más relevantes para algebra lineal usando Python. Emplee ejemplos.

La librería más clave para problemas de álgebra lineal es `numpy`, y más específicamente `numpy.linalg`.
Se crean matrices usando `numpy.array()`. Siendo A un array (una matriz), se puede usar `len()` para conocer su cantidad de filas, y `len(A[0])` para conocer la cantidad de columnas. Se usa la @ para el producto de matrices.
Sean A y B dos matrices 3x3, a continuación se mostrarán las funciones más importantes para ttrabajar álgebra lineal en Python

In [30]:
import numpy as np
from numpy import linalg as la

A=np.random.randint(-10,10, size=(3,3))
B=np.random.randint(-10,10, size=(3,3))

As=sp.Matrix(A) #Se pueden convertir a sympy para mostrarlas mejor
Bs=sp.Matrix(B)
sp.pprint(As)
print("")
sp.pprint(Bs)


⎡7   0   5 ⎤
⎢          ⎥
⎢7   -1  -9⎥
⎢          ⎥
⎣-6  -7  7 ⎦

⎡5   -3   9 ⎤
⎢           ⎥
⎢-3  -10  -3⎥
⎢           ⎥
⎣9    2   7 ⎦


Otras formas de hacer matrices es con `np.zeros`, `np.zeros_like`, `np.ones`, `np.ones_like`, que hacen matrices llenas de zeros o unos, o `np.eye`, que hace una matriz identidad nxn de la dimensión que se especifique.

In [48]:
print("Traspuesta de A")
sp.pprint(sp.Matrix(A.T))
print("Conjugada de A, como es una matriz real es ella misma")
sp.pprint(sp.Matrix(A.conjugate()))
A.conjugate
print("Valores de la diagonal, o sea aij tal que i=j")
sp.pprint(sp.Matrix(np.diag(A)))
print("si se le entreg un array devuelve una matriz diagonal con esos elementos")
sp.pprint(sp.Matrix(np.diag(np.diag(A))))
print("La traza, la suma de los elemntos de la diagonal")
print(np.trace(A))
print("El determinante")
print(la.det(A))
print("La forma de hacer una identidad")
sp.pprint(sp.Matrix(np.eye(np.shape(A)[0])))

Traspuesta de A
⎡7  7   -6⎤
⎢         ⎥
⎢0  -1  -7⎥
⎢         ⎥
⎣5  -9  7 ⎦
Conjugada de A, como es una matriz real es ella misma
⎡7   0   5 ⎤
⎢          ⎥
⎢7   -1  -9⎥
⎢          ⎥
⎣-6  -7  7 ⎦
Valores de la diagonal, o sea aij tal que i=j
⎡7 ⎤
⎢  ⎥
⎢-1⎥
⎢  ⎥
⎣7 ⎦
si se le entreg un array devuelve una matriz diagonal con esos elementos
⎡7  0   0⎤
⎢        ⎥
⎢0  -1  0⎥
⎢        ⎥
⎣0  0   7⎦
La traza, la suma de los elemntos de la diagonal
13
El determinante
-765.0
La forma de hacer una identidad
⎡1.0  0.0  0.0⎤
⎢             ⎥
⎢0.0  1.0  0.0⎥
⎢             ⎥
⎣0.0  0.0  1.0⎦


In [39]:
print("Producto cruz y producto punto")

v=np.diag(A)
u=np.diag(B)

print(np.dot(u,v))
sp.pprint(sp.Matrix(np.cross(u,v)))
print("")
sp.pprint(sp.Matrix(np.cross(v,u)))
print("")
print("Producto matricial")
print("AB")
sp.pprint(sp.Matrix(A@B))
print("BA")
sp.pprint(sp.Matrix(B@A))

Producto cruz y producto punto
94
⎡-63⎤
⎢   ⎥
⎢14 ⎥
⎢   ⎥
⎣65 ⎦

⎡63 ⎤
⎢   ⎥
⎢-14⎥
⎢   ⎥
⎣-65⎦

Producto matricial
AB
⎡80   -11  98⎤
⎢            ⎥
⎢-43  -29  3 ⎥
⎢            ⎥
⎣54   102  16⎦
BA
⎡-40  -60  115⎤
⎢             ⎥
⎢-73  31   54 ⎥
⎢             ⎥
⎣35   -51  76 ⎦


Para solucionar matrices

In [42]:
print("Vector x para el sistema AX=b")
sp.pprint(sp.Matrix(la.solve(A,u)))

Vector x para el sistema AX=b
⎡-0.0457516339869281⎤
⎢                   ⎥
⎢ 0.103267973856209 ⎥
⎢                   ⎥
⎣  1.0640522875817  ⎦


Autovectores y autovaores, `la.eig` devuelve un array con los autovectores y otro que es la matriz U tal que $ A=UDU^{-1}$, así que los autovectiores son las columnas de `eig(A)[1]`, o las filas de `eig(A)[1].T`

In [47]:
autovalores=la.eig(A)[0]
print("Diagonalizar una matriz")
sp.Matrix(np.diag(autovalores))

Diagonalizar una matriz


Matrix([
[9.62597049988939 + 5.45001754099*I,                                  0,                 0],
[                                 0, 9.62597049988939 - 5.45001754099*I,                 0],
[                                 0,                                  0, -6.25194099977881]])

In [50]:
print("U")
sp.Matrix(la.eig(A)[1])

U


Matrix([
[  0.243606221561882 - 0.505587622047723*I,   0.243606221561882 + 0.505587622047723*I, -0.153327225841365],
[-0.463536787814414 - 0.0953164447296261*I, -0.463536787814414 + 0.0953164447296261*I,  0.900749001560745],
[                        0.679032832015707,                         0.679032832015707,  0.406376670101905]])

Inversa de Una Matriz


In [52]:
sp.Matrix(la.inv(A))

Matrix([
[  0.0915032679738562,  0.0457516339869281, -0.0065359477124183],
[-0.00653594771241829,  -0.103267973856209,  -0.128104575163399],
[  0.0718954248366013, -0.0640522875816994, 0.00915032679738562]])

En general, para ver si dos matrices son aproximadamente iguales se usa `np.isclose`, que devuelve un array booleano que dice si cada elemento de los arrays son aproximadamente iguales, dentro de una tolerancia.

In [56]:
np.isclose(la.inv(A)@A, np.eye(3))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])