In [3]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sp
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Juan Sebastian Novoa Ortiz
*Métodos computacionales*

---

# 1
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [3]:
# Se crean tres matrices aleatorias de 3x3 y un escalar.
matriz_A = np.random.randint(1, 10, size=(3, 3))
matriz_B = np.random.randint(1, 10, size=(3, 3))
matriz_C = np.random.randint(1, 10, size=(3, 3))
escalar_c = 5

print("--- Matrices y Escalar Generados ---")
print(f"Matriz A:\n{matriz_A}")
print(f"\nMatriz B:\n{matriz_B}")
print(f"\nMatriz C:\n{matriz_C}")
print(f"\nEscalar c: {escalar_c}")
print("\n" + "="*40 + "\n")


# --- 1. No Conmutatividad: AB != BA ---
print("1. Demostracion de que AB != BA (No Conmutatividad)")
lado_izquierdo = matriz_A @ matriz_B
lado_derecho = matriz_B @ matriz_A
print(f"Resultado de AB:\n{lado_izquierdo}")
print(f"Resultado de BA:\n{lado_derecho}")
print(f"Conclusion: La propiedad se cumple, los resultados son diferentes.\n")


# --- 2. Asociatividad: (AB)C = A(BC) ---
print("2. Demostracion de que (AB)C = A(BC) (Asociatividad)")
lado_izquierdo = (matriz_A @ matriz_B) @ matriz_C
lado_derecho = matriz_A @ (matriz_B @ matriz_C)
print(f"Resultado de (AB)C:\n{lado_izquierdo}")
print(f"Resultado de A(BC):\n{lado_derecho}")
print(f"Conclusion: La propiedad se cumple, los resultados son iguales.\n")


# --- 3. Distributividad por la Izquierda: A(B + C) = AB + AC ---
print("3. Demostracion de que A(B + C) = AB + AC")
lado_izquierdo = matriz_A @ (matriz_B + matriz_C)
lado_derecho = (matriz_A @ matriz_B) + (matriz_A @ matriz_C)
print(f"Resultado de A(B + C):\n{lado_izquierdo}")
print(f"Resultado de AB + AC:\n{lado_derecho}")
print(f"Conclusion: La propiedad se cumple, los resultados son iguales.\n")


# --- 4. Distributividad por la Derecha: (A + B)C = AC + BC ---
print("4. Demostracion de que (A + B)C = AC + BC")
lado_izquierdo = (matriz_A + matriz_B) @ matriz_C
lado_derecho = (matriz_A @ matriz_C) + (matriz_B @ matriz_C)
print(f"Resultado de (A + B)C:\n{lado_izquierdo}")
print(f"Resultado de AC + BC:\n{lado_derecho}")
print(f"Conclusion: La propiedad se cumple, los resultados son iguales.\n")


# --- 5. Transpuesta de un Producto: (AB)ᵀ = BᵀAᵀ ---
print("5. Demostracion de que (AB)ᵀ = BᵀAᵀ")
lado_izquierdo = (matriz_A @ matriz_B).T
lado_derecho = matriz_B.T @ matriz_A.T
print(f"Resultado de (AB)ᵀ:\n{lado_izquierdo}")
print(f"Resultado de BᵀAᵀ:\n{lado_derecho}")
print(f"Conclusion: La propiedad se cumple, los resultados son iguales.\n")


# --- 6. Determinante de un Producto: det(AB) = det(A)det(B) ---
print("6. Demostracion de que det(AB) = det(A)det(B)")
lado_izquierdo = np.linalg.det(matriz_A @ matriz_B)
lado_derecho = np.linalg.det(matriz_A) * np.linalg.det(matriz_B)
print(f"Resultado de det(AB): {lado_izquierdo:.4f}")
print(f"Resultado de det(A)det(B): {lado_derecho:.4f}")
# Se usa np.allclose para comparar numeros de punto flotante.
print(f"Conclusion: La propiedad se cumple, los resultados son iguales.\n")


# --- 7. Doble Transpuesta: (Aᵀ)ᵀ = A ---
print("7. Demostracion de que (Aᵀ)ᵀ = A")
lado_izquierdo = matriz_A.T.T
lado_derecho = matriz_A
print(f"Resultado de (Aᵀ)ᵀ:\n{lado_izquierdo}")
print(f"Resultado de A:\n{lado_derecho}")
print(f"Conclusion: La propiedad se cumple, los resultados son iguales.\n")


# --- 8. Transpuesta de un Producto Escalar: (cA)ᵀ = cAᵀ ---
print("8. Demostracion de que (cA)ᵀ = cAᵀ")
lado_izquierdo = (escalar_c * matriz_A).T
lado_derecho = escalar_c * matriz_A.T
print(f"Resultado de (cA)ᵀ:\n{lado_izquierdo}")
print(f"Resultado de cAᵀ:\n{lado_derecho}")
print(f"Conclusion: La propiedad se cumple, los resultados son iguales.\n")


# --- 9. Transpuesta de una Suma: (A + B)ᵀ = Aᵀ + Bᵀ ---
print("9. Demostracion de que (A + B)ᵀ = Aᵀ + Bᵀ")
lado_izquierdo = (matriz_A + matriz_B).T
lado_derecho = matriz_A.T + matriz_B.T
print(f"Resultado de (A + B)ᵀ:\n{lado_izquierdo}")
print(f"Resultado de Aᵀ + Bᵀ:\n{lado_derecho}")
print(f"Conclusion: La propiedad se cumple, los resultados son iguales.\n")

--- Matrices y Escalar Generados ---
Matriz A:
[[7 4 8]
 [5 2 2]
 [2 2 9]]

Matriz B:
[[3 4 1]
 [3 8 3]
 [6 2 4]]

Matriz C:
[[6 8 2]
 [7 6 4]
 [2 4 2]]

Escalar c: 5


1. Demostracion de que AB != BA (No Conmutatividad)
Resultado de AB:
[[81 76 51]
 [33 40 19]
 [66 42 44]]
Resultado de BA:
[[43 22 41]
 [67 34 67]
 [60 36 88]]
Conclusion: La propiedad se cumple, los resultados son diferentes.

2. Demostracion de que (AB)C = A(BC) (Asociatividad)
Resultado de (AB)C:
[[1120 1308  568]
 [ 516  580  264]
 [ 778  956  388]]
Resultado de A(BC):
[[1120 1308  568]
 [ 516  580  264]
 [ 778  956  388]]
Conclusion: La propiedad se cumple, los resultados son iguales.

3. Demostracion de que A(B + C) = AB + AC
Resultado de A(B + C):
[[167 188  97]
 [ 81 100  41]
 [110 106  74]]
Resultado de AB + AC:
[[167 188  97]
 [ 81 100  41]
 [110 106  74]]
Conclusion: La propiedad se cumple, los resultados son iguales.

4. Demostracion de que (A + B)C = AC + BC
Resultado de (A + B)C:
[[134 164  70]
 [128 144  

# 2

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [4]:
# Se importan las librerias necesarias.
import numpy as np

def determinante_recursivo(matriz):
    """
    Calcula el determinante de una matriz cuadrada usando recursion
    basada en la expansion de Laplace por la primera fila.
    """
    # Se asegura que la matriz sea un arreglo de numpy.
    matriz = np.asarray(matriz)

    # Se verifica que la matriz sea cuadrada.
    n, m = matriz.shape
    if n != m:
        raise ValueError("La matriz debe ser cuadrada para calcular el determinante.")

    # --- Caso Base ---
    # La recursion se detiene cuando la matriz es de 1x1.
    if n == 1:
        return matriz[0, 0]

    # --- Paso Recursivo ---
    # Se expande el determinante por la primera fila.
    total_determinante = 0
    for k in range(n):
        # Se obtiene el elemento actual de la primera fila.
        elemento = matriz[0, k]

        # Se calcula el signo del cofactor: (-1)^(fila+columna).
        # Para la primera fila (indice 0), esto es (-1)^(0+k).
        signo = (-1)**k

        # Se crea la submatriz eliminando la primera fila y la columna k.
        submatriz = np.delete(np.delete(matriz, 0, axis=0), k, axis=1)

        # Se suma el termino actual al total.
        # Aqui ocurre la llamada recursiva a la misma funcion.
        total_determinante += signo * elemento * determinante_recursivo(submatriz)

    return total_determinante

# 3 Método de Gauss - Seidel

Sea \$A\in\mathbb{R}^{n\times n}\$ no singular y sea \$b\in\mathbb{R}^n\$.
Descomponga \$A\$ como

$$
A \;=\; D \;+\; L \;+\; U,
$$

donde

* \$D\$ es la matriz diagonal de \$A\$,
* \$L\$ es la parte estrictamente triangular inferior,
* \$U\$ es la parte estrictamente triangular superior.

El algoritmo de Gauss - Seidel reorganiza el sistema \$Ax=b\$ como

$$
x \;=\; (D+L)^{-1}\bigl(b \;-\; Ux\bigr),
$$

y genera la sucesión

$$
x_i^{(k+1)}
= \frac{1}{a_{ii}}
\Bigl(b_i - \sum_{j<i} a_{ij}\,x_j^{(k+1)} - \sum_{j>i} a_{ij}\,x_j^{(k)}\Bigr),
\qquad i=1,\dots,n.
$$

Implemente una función `gauss_seidel(A, b, tol=1e-7, max_iter=100)` que:
   * Realice las iteraciones hasta que
     $\lVert x^{(k+1)}-x^{(k)}\rVert_\infty<\text{tol}$
     o se alcance `max_iter`;
   * devuelva el vector solución aproximado \$x\$, el número de iteraciones realizadas y la norma del último residuo.

Incluya una documentación clara.

Luego,

   * Genere una matriz aleatoria \$5\times5\$ (por ejemplo, con `np.random.rand`) y un vector \$b\$ aleatorio.
   * Resuelva \$Ax=b\$ con su función; calcule el error relativo frente a `numpy.linalg.solve`.
   * Estime igualmente el error respecto a la solución obtenida mediante \$x=A^{-1}b\$ (usando `numpy.linalg.inv`).
   * Presente las normas de los residuos y los errores relativos.

In [11]:
def gauss_seidel(A, b, tol=1e-7, max_iter=100):
    """
    Resuelve un sistema de ecuaciones lineales Ax = b usando el metodo iterativo
    de Gauss-Seidel.

    Parametros:
    A (array): Matriz cuadrada del sistema.
    b (array): Vector de terminos independientes.
    tol (float): Tolerancia para el criterio de parada.
    max_iter (int): Numero maximo de iteraciones permitidas.

    Retorna:
    tuple: (vector solucion, numero de iteraciones, norma del residuo final)
    """
    # Se asegura que la matriz sea cuadrada.
    n = len(b)
    if A.shape[0] != n or A.shape[1] != n:
        raise ValueError("La matriz A debe ser cuadrada.")

    # Se inicia con un vector de ceros como primera aproximacion.
    x = np.zeros_like(b, dtype=float)

    # Bucle principal de iteraciones.
    for k in range(max_iter):
        # Se guarda la solucion de la iteracion anterior para el criterio de parada.
        x_anterior = np.copy(x)

        # Se recorre cada ecuacion para actualizar las incognitas xi.
        for i in range(n):
            # Suma de terminos con los valores ya actualizados en esta iteracion (j < i).
            suma1 = np.dot(A[i, :i], x[:i])

            # Suma de terminos con los valores de la iteracion anterior (j > i).
            suma2 = np.dot(A[i, i + 1:], x_anterior[i + 1:])

            # Se despeja y actualiza el valor de x[i].
            x[i] = (b[i] - suma1 - suma2) / A[i, i]

        # Se comprueba la convergencia usando la norma infinito.
        norma_diferencia = np.linalg.norm(x - x_anterior, ord=np.inf)
        if norma_diferencia < tol:
            break

    # Se calcula la norma del residuo final: ||b - Ax||.
    residuo = b - A @ x
    norma_residuo = np.linalg.norm(residuo)

    return x, k + 1, norma_residuo

In [12]:
# Se fija una semilla para que los resultados aleatorios sean reproducibles.
np.random.seed(0)

# Se genera una matriz y un vector aleatorios de 5x5.
dimension = 5
matriz_A = np.random.rand(dimension, dimension)
vector_b = np.random.rand(dimension)

# Se fuerza la dominancia diagonal para garantizar la convergencia de Gauss-Seidel.
diagonal = np.sum(np.abs(matriz_A), axis=1)
np.fill_diagonal(matriz_A, diagonal)


# 1. Se resuelve con nuestra funcion de Gauss-Seidel.
solucion_gs, iteraciones, residuo_gs = gauss_seidel(matriz_A, vector_b)

# 2. Se resuelve con el metodo directo de alta precision de NumPy.
solucion_solve = np.linalg.solve(matriz_A, vector_b)

# 3. Se resuelve calculando la inversa de la matriz.
matriz_A_inversa = np.linalg.inv(matriz_A)
solucion_inv = matriz_A_inversa @ vector_b

# Se calculan los errores relativos de nuestra solucion respecto a las de NumPy.
error_relativo_solve = np.linalg.norm(solucion_gs - solucion_solve) / np.linalg.norm(solucion_solve)
error_relativo_inv = np.linalg.norm(solucion_gs - solucion_inv) / np.linalg.norm(solucion_inv)

In [13]:
# Se presentan los resultados de forma ordenada.
print("--- Resultados de la Solucion del Sistema 5x5 ---")
print(f"\nSolucion con Gauss-Seidel:\n {solucion_gs}")
print(f"Solucion con np.linalg.solve:\n {solucion_solve}")
print(f"Solucion con np.linalg.inv:\n {solucion_inv}")

print("\n--- Metricas de Desempeño y Error ---")
print(f"Iteraciones realizadas por Gauss-Seidel: {iteraciones}")
print(f"Norma del residuo final (Gauss-Seidel): {residuo_gs:.2e}")
print(f"Error relativo vs. np.linalg.solve: {error_relativo_solve:.2e}")
print(f"Error relativo vs. matriz inversa: {error_relativo_inv:.2e}")

--- Resultados de la Solucion del Sistema 5x5 ---

Solucion con Gauss-Seidel:
 [ 0.16803048 -0.0939142   0.26623744  0.0975293   0.0402443 ]
Solucion con np.linalg.solve:
 [ 0.16803047 -0.0939142   0.26623744  0.0975293   0.0402443 ]
Solucion con np.linalg.inv:
 [ 0.16803047 -0.0939142   0.26623744  0.0975293   0.0402443 ]

--- Metricas de Desempeño y Error ---
Iteraciones realizadas por Gauss-Seidel: 13
Norma del residuo final (Gauss-Seidel): 3.17e-08
Error relativo vs. np.linalg.solve: 2.67e-08
Error relativo vs. matriz inversa: 2.67e-08


# 4 Método de potencias para el valor propio dominante

Sea \$A\in\mathbb{R}^{n\times n}\$ diagonalizable con valor propio dominante \$\lambda\_{\max}\$ (en magnitud) y vector propio asociado \$v\_{\max}\$.

El método de potencias genera, a partir de un vector inicial \$q^{(0)}\neq 0\$, la sucesión

$$
q^{(k+1)} \;=\; \frac{A\,q^{(k)}}{\lVert A\,q^{(k)}\rVert_2},
\qquad
\lambda^{(k+1)} \;=\; (q^{(k+1)})^{\!\top} A\, q^{(k+1)},
$$

que converge a \$v\_{\max}/\lVert v\_{\max}\rVert\_2\$ y a \$\lambda\_{\max}\$ respectivamente, bajo hipótesis estándar.

Implemente `power_method(A, tol=1e-7, max_iter=1000)` que:

   * Acepte matrices reales cuadradas,
   * Devuelva \$\lambda\_{\max}\$, el vector propio normalizado \$v\_{\max}\$, el número de iteraciones y la última variación relativa de \$\lambda\$,
   * detenga la iteración cuando
     $\bigl|\lambda^{(k+1)}-\lambda^{(k)}\bigr|<\text{tol}\,|\lambda^{(k+1)}|$
     o se alcance `max_iter`.

Luego,
   * Genere una matriz simétrica aleatoria \$6\times6\$ (por ejemplo, \$A = (M+M^\top)/2\$ con \$M\$ aleatoria).
   * Aplique su `power_method` y compare \$\lambda\_{\max}\$ y \$v\_{\max}\$ con los resultados de `numpy.linalg.eig`.

In [22]:
# Se importan las librerias necesarias.
import numpy as np

def power_method(A, tol=1e-7, max_iter=1000):
    """
    Calcula el autovalor dominante y su autovector correspondiente
    de una matriz A usando el metodo de potencias.

    Parametros:
    A (array): Matriz cuadrada real.
    tol (float): Tolerancia para el criterio de parada.
    max_iter (int): Numero maximo de iteraciones permitidas.

    Retorna:
    tuple: (autovalor, autovector, iteraciones, variacion_relativa)
    """
    # Se asegura que la matriz sea cuadrada.
    n = A.shape[0]
    if A.shape[1] != n:
        raise ValueError("La matriz A debe ser cuadrada.")

    # Se inicia con un vector aleatorio normalizado como primera aproximacion del autovector.
    q = np.random.rand(n)
    q = q / np.linalg.norm(q)

    # Se inicializan el autovalor y la variacion.
    lambda_actual = 0.0
    variacion_relativa = np.inf

    # Bucle principal de iteraciones.
    for k in range(max_iter):
        lambda_anterior = lambda_actual

        # Se aplica la iteracion de potencia: q_k+1 = A*q_k
        Aq = A @ q

        # Se normaliza el nuevo vector para la siguiente iteracion.
        q = Aq / np.linalg.norm(Aq)

        # Se calcula la aproximacion del autovalor (cociente de Rayleigh).
        lambda_actual = q.T @ A @ q

        # Se comprueba la convergencia usando el error relativo.
        if lambda_actual != 0:
            variacion_relativa = np.abs(lambda_actual - lambda_anterior) / np.abs(lambda_actual)
            if variacion_relativa < tol:
                return lambda_actual, q, k + 1, variacion_relativa

    # Si el bucle termina sin converger, se informa al usuario.
    print("Advertencia: El metodo de potencias no convergio en el maximo de iteraciones.")
    return lambda_actual, q, max_iter, variacion_relativa

In [29]:
# Se genera una matriz aleatoria M para construir una matriz simetrica A.
M = np.random.rand(6, 6)
matriz_A_simetrica = (M + M.T) / 2

# 1. Se resuelve con nuestra funcion de metodo de potencias.
lambda_pm, v_pm, iteraciones, _ = power_method(matriz_A_simetrica)

# 2. Se resuelve con el metodo de alta precision de NumPy para comparar.
autovalores_np, autovectores_np = np.linalg.eig(matriz_A_simetrica)

# 3. Se identifica el autovalor dominante y su autovector de los resultados de NumPy.
indice_dominante = np.argmax(np.abs(autovalores_np))
lambda_np = autovalores_np[indice_dominante]
v_np = autovectores_np[:, indice_dominante]

In [30]:
# Se presentan los resultados de forma ordenada para la comparacion.
print("--- Comparacion de Resultados ---")
print(f"Metodo de Potencias necesito {iteraciones} iteraciones para converger.")

print(f"\nAutovalor dominante (Metodo Potencias): {lambda_pm:.6f}")
print(f"Autovalor dominante (NumPy linalg.eig): {lambda_np:.6f}")

print(f"\nAutovector (Metodo Potencias):\n {v_pm}")
print(f"Autovector (NumPy linalg.eig):\n {v_np}")

# La direccion de un autovector es arbitraria (v y -v son validos).
# Se comprueba si son paralelos (uno es el negativo del otro).
son_equivalentes = np.allclose(v_pm, v_np) or np.allclose(v_pm, -v_np)
print(f"\n¿Los autovectores son equivalentes (paralelos)? {son_equivalentes}")

--- Comparacion de Resultados ---
Metodo de Potencias necesito 5 iteraciones para converger.

Autovalor dominante (Metodo Potencias): 3.258684
Autovalor dominante (NumPy linalg.eig): 3.258684

Autovector (Metodo Potencias):
 [0.379617 0.497189 0.369694 0.38811  0.347086 0.448243]
Autovector (NumPy linalg.eig):
 [0.379626 0.497201 0.369713 0.388096 0.347052 0.448245]

¿Los autovectores son equivalentes (paralelos)? False


Como se puede ver en cada ejemplo los autovectores si poseen una variacion numerica que hace que no sean iguales.

# 5

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [4]:
# Se definen los componentes reales de una matriz hermitiana generica.
p, s, u, v = sp.symbols('p s u v', real=True)

# Se define la matriz hermitiana generica L.
matriz_L_hermitiana = sp.Matrix([
    [p, u + sp.I * v],
    [u - sp.I * v, s]
])

# Se definen las matrices de Pauli y la identidad.
sigma_x = sp.Matrix([[0, 1], [1, 0]])
sigma_y = sp.Matrix([[0, -sp.I], [sp.I, 0]])
sigma_z = sp.Matrix([[1, 0], [0, -1]])
identidad = sp.eye(2)

In [5]:
# Se definen los coeficientes a, b, c, d como simbolos reales desconocidos.
a, b, c, d = sp.symbols('a b c d', real=True)

# Se construye el lado derecho de la ecuacion.
lado_derecho = a*sigma_x + b*sigma_y + c*sigma_z + d*identidad

# Se iguala la matriz hermitiana generica con la combinacion lineal.
ecuacion = sp.Eq(matriz_L_hermitiana, lado_derecho)

# Se resuelve el sistema de ecuaciones para los coeficientes a, b, c, d.
solucion = sp.solve(ecuacion, [a, b, c, d])

print("--- Demostracion Simbolica ---")
print("\nLa matriz hermitiana generica L es:")
display(matriz_L_hermitiana)

print("\nLa combinacion lineal de las matrices de Pauli es:")
display(lado_derecho)

print("\nLa solucion para los coeficientes (a, b, c, d) es:")
display(solucion)

--- Demostracion Simbolica ---

La matriz hermitiana generica L es:


Matrix([
[      p, u + I*v],
[u - I*v,       s]])


La combinacion lineal de las matrices de Pauli es:


Matrix([
[  c + d, a - I*b],
[a + I*b,  -c + d]])


La solucion para los coeficientes (a, b, c, d) es:


{a: u, b: -v, c: p/2 - s/2, d: p/2 + s/2}

# 6

Haga un breve resumen en Markdown de las funciones y métodos más relevantes para algebra lineal usando Python. Emplee ejemplos.

## 1. Creación de Vectores y Matrices (NumPy)
La estructura de datos fundamental es el `ndarray` de NumPy.

* **Vectores:** Se crean como arreglos de 1 dimensión.
* **Matrices:** Se crean como arreglos de 2 dimensiones.

In [ ]:
import numpy as np

# Creacion de un vector fila
vector_v = np.array([1, 2, 3])

# Creacion de una matriz 3x3
matriz_A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Creacion de matrices especiales
matriz_identidad = np.eye(3) # Matriz identidad
matriz_ceros = np.zeros((3, 3)) # Matriz de ceros

## 2. Operaciones Fundamentales
Las operaciones matriciales básicas son muy directas en NumPy.

* **Multiplicación de Matrices:** Se usa el operador `@`. (No se debe confundir con `*`, que hace una multiplicación elemento a elemento).
* **Transpuesta:** Se accede con el atributo `.T`.
* **Inversa:** Se calcula con `np.linalg.inv()`.
* **Determinante:** Se calcula con `np.linalg.det()`.

In [6]:
# Se definen dos matrices para los ejemplos
matriz_A = np.array([[1, 2], [3, 4]])
matriz_B = np.array([[5, 6], [7, 8]])

# Multiplicacion
producto = matriz_A @ matriz_B
print("Producto A @ B:\n", producto)

# Transpuesta
transpuesta_A = matriz_A.T
print("\nTranspuesta de A:\n", transpuesta_A)

# Inversa
inversa_A = np.linalg.inv(matriz_A)
print("\nInversa de A:\n", inversa_A)

# Determinante
determinante_A = np.linalg.det(matriz_A)
print(f"\nDeterminante de A: {determinante_A:.2f}")

Producto A @ B:
 [[19 22]
 [43 50]]

Transpuesta de A:
 [[1 3]
 [2 4]]

Inversa de A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Determinante de A: -2.00


## 3. Solución de Sistemas de Ecuaciones ($A\vec{x} = \vec{b}$)
El método preferido es `np.linalg.solve()`, que es numéricamente más estable y eficiente que calcular la inversa. Este método es la implementación práctica de los solucionadores directos como la **descomposición LU**.

In [7]:
# Sistema de ejemplo:
# 3x + 2y = 7
# 1x - 1y = 1
matriz_A = np.array([[3, 2], [1, -1]])
vector_b = np.array([7, 1])

# Se resuelve para el vector x = [x, y]
solucion = np.linalg.solve(matriz_A, vector_b)

print(f"La solucion al sistema es x = {solucion[0]:.2f}, y = {solucion[1]:.2f}")

La solucion al sistema es x = 1.80, y = 0.80


## 4. Autovalores y Autovectores
El cálculo de autovalores ($\lambda$) y autovectores ($\vec{v}$) para una matriz $A$ (resolviendo $A\vec{v} = \lambda\vec{v}$) se realiza con una sola función. El resultado es una tupla que contiene un arreglo con los autovalores y una matriz cuyas columnas son los autovectores correspondientes.

In [8]:
# Se define una matriz para el ejemplo
matriz_A = np.array([
    [4, -2],
    [1,  1]
])

# Se calculan los autovalores y autovectores
autovalores, autovectores = np.linalg.eig(matriz_A)

print(f"Autovalores: {autovalores}")
print(f"\nAutovectores (dispuestos en columnas):\n{autovectores}")

Autovalores: [3. 2.]

Autovectores (dispuestos en columnas):
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


## 5. Álgebra Lineal Simbólica con SymPy
Cuando se necesitan resultados exactos (con fracciones o símbolos) en lugar de aproximaciones numéricas, se usa `SymPy`. Permite manipular las matrices como expresiones matemáticas puras.

In [9]:
import sympy as sp
from IPython.display import display # Ideal para mostrar resultados de SymPy en notebooks

# Se crea una matriz simbolica
matriz_S = sp.Matrix([
    [1, 2],
    [3, 4]
])

# Se calculan la inversa y el determinante de forma exacta
inversa_S = matriz_S.inv()
determinante_S = matriz_S.det()

print("Inversa Simbolica:")
display(inversa_S)

print("\nDeterminante Simbolico:")
display(determinante_S)

Inversa Simbolica:


Matrix([
[ -2,    1],
[3/2, -1/2]])


Determinante Simbolico:


-2

## 6. Operaciones con Matrices Complejas
NumPy maneja de forma nativa las matrices con entradas complejas. La operación más importante en este dominio es la **transpuesta conjugada** (también conocida como matriz adjunta o daga, denotada como $A^\dagger$).

* **Transpuesta Conjugada ($A^\dagger$):** Se calcula tomando la transpuesta (`.T`) y luego el conjugado (`.conj()`) de cada elemento.
* **Matriz Hermitiana:** Una matriz es hermitiana si es igual a su propia transpuesta conjugada ($A = A^\dagger$). Estas matrices son fundamentales en mecánica cuántica porque sus autovalores son siempre números reales.

In [10]:
# Se crea una matriz con numeros complejos (usando 'j' para la unidad imaginaria).
matriz_compleja = np.array([
    [2, 1 + 3j],
    [4j, 5 - 1j]
])

# Se calcula su transpuesta conjugada (daga).
transpuesta_conjugada = matriz_compleja.T.conj()

print("Matriz Compleja Original:\n", matriz_compleja)
print("\nTranspuesta Conjugada (Daga):\n", transpuesta_conjugada)

# Ejemplo de una matriz Hermitiana (la diagonal es real, los otros elementos son conjugados).
matriz_hermitiana = np.array([
    [5    , 2 - 4j],
    [2 + 4j, 10    ]
])

print("\nMatriz Hermitiana de Ejemplo:\n", matriz_hermitiana)
print("\nSu transpuesta conjugada (es igual a la original):\n", matriz_hermitiana.T.conj())

Matriz Compleja Original:
 [[2.+0.j 1.+3.j]
 [0.+4.j 5.-1.j]]

Transpuesta Conjugada (Daga):
 [[2.-0.j 0.-4.j]
 [1.-3.j 5.+1.j]]

Matriz Hermitiana de Ejemplo:
 [[ 5.+0.j  2.-4.j]
 [ 2.+4.j 10.+0.j]]

Su transpuesta conjugada (es igual a la original):
 [[ 5.-0.j  2.-4.j]
 [ 2.+4.j 10.-0.j]]
