In [5]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: Sara Calle Muñoz
*Métodos computacionales*

---

#1
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [6]:
#generamos las matrices aleatorias 3x3
A = np.random.randint(0, 10, size=(3, 3))
B = np.random.randint(0, 10, size=(3, 3))
C = np.random.randint(0, 10, size=(3, 3))

print("Matriz A:\n", A)
print("Matriz B:\n", B)
print("Matriz C:\n", C)

#usamos np.array_equal para comparar si son identicos
#1: AB ≠ BA
AB = A @ B
BA = B @ A

if np.array_equal(AB, BA):
    print("Relación 1: AB = BA")
else:
    print("Relación 1: AB ≠ BA")

#2: (AB)C = A(BC)
AB_C = AB @ C
A_BC = A @ (B @ C)

if np.array_equal(AB_C, A_BC):
    print("Relación 2: (AB)C = A(BC)")
else:
    print("Relación 2: (AB)C ≠ A(BC)")

#3: A(B + C) = AB + AC
A_BmasC = A @ (B + C)
ABmasAC = AB + A @ C

if np.array_equal(A_BmasC, ABmasAC):
    print("Relación 3: A(B + C) = AB + AC")
else:
    print("Relación 3: A(B + C) ≠ AB + AC")

#4: (A + B)C = AC + BC
AmasB_C = (A + B) @ C
ACmasBC = A @ C + B @ C

if np.array_equal(AmasB_C, ACmasBC):
    print("Relación 4: (A + B)C = AC + BC")
else:
    print("Relación 4: (A + B)C ≠ AC + BC")

#5: (AB)^T = B^T A^T
AB_T = AB.T
BT_AT = B.T @ A.T

if np.array_equal(AB_T, BT_AT):
    print("Relación 5: (AB)^T = B^T A^T")
else:
    print("Relación 5: (AB)^T ≠ B^T A^T")

#6: det(AB) = det(A) * det(B)
detAB = np.linalg.det(AB)
detA = np.linalg.det(A)
detB = np.linalg.det(B)

if np.isclose(detAB, detA * detB):
    print("Relación 6: det(AB) = det(A) * det(B)")
else:
    print("Relación 6: det(AB) ≠ det(A) * det(B)")

#7: (A^T)^T = A
if np.array_equal(A.T.T, A):
    print("Relación 7: (A^T)^T = A")
else:
    print("Relación 7: (A^T)^T ≠ A")

#8: (cA)^T = c A^T
c = np.random.randint(1, 100)
cA_T = (c * A).T
c_AT = c * A.T
if np.array_equal(cA_T, c_AT):
    print(f"Relación 8: ({c}A)^T = {c}(A^T)")
else:
    print(f"Relación 8: ({c}A)^T ≠ {c}(A^T)")

#9: (A + B)^T = A^T + B^T
AmasB_T = (A + B).T
ATmasBT = A.T + B.T
if np.array_equal(AmasB_T, ATmasBT):
    print("Relación 9: (A + B)^T = A^T + B^T")
else:
    print("Relación 9: (A + B)^T ≠ A^T + B^T")


Matriz A:
 [[0 2 6]
 [8 0 4]
 [9 5 9]]
Matriz B:
 [[0 8 3]
 [2 8 4]
 [6 2 6]]
Matriz C:
 [[0 5 6]
 [8 8 0]
 [4 7 4]]
Relación 1: AB ≠ BA
Relación 2: (AB)C = A(BC)
Relación 3: A(B + C) = AB + AC
Relación 4: (A + B)C = AC + BC
Relación 5: (AB)^T = B^T A^T
Relación 6: det(AB) = det(A) * det(B)
Relación 7: (A^T)^T = A
Relación 8: (53A)^T = 53(A^T)
Relación 9: (A + B)^T = A^T + B^T


#2

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [7]:
def determinante(matriz):
    """
    Calcula el determinante de una matriz cuadrada usando recursividad
    y el Teorema de Laplace.
    """
    #para asegurar que es la matriz es cuadrada
    if matriz.shape[0] != matriz.shape[1]:
        raise ValueError("La matriz debe ser cuadrada")

    n = matriz.shape[0]

    #caso base: matriz 1x1
    if n == 1:
        return matriz[0, 0]

    #inicializamos el determinante
    det = 0

    #expansión de Laplace por la primera fila
    for j in range(n):
        #menor complementario: eliminar la primera fila y columna j
        menor = np.delete(np.delete(matriz, 0, axis=0), j, axis=1)

        #calculamos el cofactor
        cofactor = (-1) ** j * matriz[0, j] * determinante(menor)

        #sumar al determinante
        det += cofactor

    return det

In [8]:
A = np.array([[2, 1, -1],
              [4, -2, 4],
              [-6, 2, 1]])

print("Determinante de A:", determinante(A))

Determinante de A: -44


#3 Método de Gauss - Seidel

Sea \$A\in\mathbb{R}^{n\times n}\$ no singular y sea \$b\in\mathbb{R}^n\$.
Descomponga \$A\$ como

$$
A \;=\; D \;+\; L \;+\; U,
$$

donde

* \$D\$ es la matriz diagonal de \$A\$,
* \$L\$ es la parte estrictamente triangular inferior,
* \$U\$ es la parte estrictamente triangular superior.

El algoritmo de Gauss - Seidel reorganiza el sistema \$Ax=b\$ como

$$
x \;=\; (D+L)^{-1}\bigl(b \;-\; Ux\bigr),
$$

y genera la sucesión

$$
x_i^{(k+1)}
= \frac{1}{a_{ii}}
\Bigl(b_i - \sum_{j<i} a_{ij}\,x_j^{(k+1)} - \sum_{j>i} a_{ij}\,x_j^{(k)}\Bigr),
\qquad i=1,\dots,n.
$$

Implemente una función `gauss_seidel(A, b, tol=1e-7, max_iter=100)` que:
   * Realice las iteraciones hasta que
     $\lVert x^{(k+1)}-x^{(k)}\rVert_\infty<\text{tol}$
     o se alcance `max_iter`;
   * devuelva el vector solución aproximado \$x\$, el número de iteraciones realizadas y la norma del último residuo.

Incluya una documentación clara.

Luego,

   * Genere una matriz aleatoria \$5\times5\$ (por ejemplo, con `np.random.rand`) y un vector \$b\$ aleatorio.
   * Resuelva \$Ax=b\$ con su función; calcule el error relativo frente a `numpy.linalg.solve`.
   * Estime igualmente el error respecto a la solución obtenida mediante \$x=A^{-1}b\$ (usando `numpy.linalg.inv`).
   * Presente las normas de los residuos y los errores relativos.

In [9]:
#función para Gauss-Seidel
def gauss_seidel(A, b, tol=1e-7, max_iter=100):
    """
    Resuelve el sistema Ax = b usando el método iterativo de Gauss-Seidel

    Parámetros:
    A : Matriz de coeficientes, debe ser cuadrada -> ndarray
    b : Vector de términos independientes -> ndarray
    tol : Tolerancia para la norma del residuo -> float
    max_iter : Número máximo de iteraciones permitidas -> int

    Retorna:
    x : Vector solución -> ndarray
    iter : Número de iteraciones realizadas -> int
    residuo : Norma del residuo final -> float
    """

    n = len(b)
    x = np.zeros_like(b, dtype=float)
    iter = 0

    for _ in range(max_iter):
        x_o = x.copy()

        for i in range(n):
            suma1 = sum(A[i, j] * x[j] for j in range(i))
            suma2 = sum(A[i, j] * x_o[j] for j in range(i + 1, n))
            x[i] = (b[i] - suma1 - suma2) / A[i, i]

        residuo = np.linalg.norm(x - x_o, ord=np.inf)
        iter += 1

        if residuo < tol:
            break

    return x, iter, residuo

In [10]:
#generamos la matriz A y vector b aleatorios
A = np.random.rand(5, 5) * 10
b = np.random.rand(5) * 10

print("Matriz A:\n", A)
print("Vector b:\n", b)

#resolvemos con Gauss-Seidel
x_g, iteraciones, residuo_final = gauss_seidel(A, b)

print("\nResultados Gauss-Seidel")
print("Solución aproximada:", x_g)
print("Iteraciones:", iteraciones)
print("Norma del residuo final:", residuo_final)

Matriz A:
 [[7.05617527 6.99052551 8.60457572 8.32445816 5.19277457]
 [8.95163797 7.25106899 6.88601406 1.03914539 8.3625741 ]
 [4.52174122 8.20872162 1.16600527 1.64503424 2.92016445]
 [0.94534191 5.43925826 4.77146713 5.79753617 8.107128  ]
 [6.82420987 5.60106601 5.36865403 0.29193873 2.34210314]]
Vector b:
 [7.68635847 8.61676962 5.01476169 6.08205847 9.22679025]

Resultados Gauss-Seidel
Solución aproximada: [-6.68937186e+70  8.43890323e+69 -1.10650485e+71 -4.86711334e+70
  4.34431372e+71]
Iteraciones: 100
Norma del residuo final: 3.3236392378267573e+71


In [11]:
#comparamos con numpy.linalg.solve
x_exacta = np.linalg.solve(A, b)
error_relativo = np.linalg.norm(x_g - x_exacta, ord=np.inf) / np.linalg.norm(x_exacta, ord=np.inf)

print("\nComparación con np.linalg.solve")
print("Solución exacta:", x_exacta)
print("Error relativo:", error_relativo)


Comparación con np.linalg.solve
Solución exacta: [-1.12463549  1.30984689  2.0328365  -1.04676363 -0.44532843]
Error relativo: 2.1370699105742572e+71


In [12]:
#comparamos con A^-1 b
x_inversa = np.linalg.inv(A) @ b
error_inversa = np.linalg.norm(x_g - x_inversa, ord=np.inf)

print("\nComparación con (A^-1) b")
print("Solución por (A^-1) b:", x_inversa)
print("Error respecto a (A^-1) b:", error_inversa)


Comparación con (A^-1) b
Solución por (A^-1) b: [-1.12463549  1.30984689  2.0328365  -1.04676363 -0.44532843]
Error respecto a (A^-1) b: 4.344313724492413e+71


In [13]:
#normas del residuo
residuo_vector = b - A @ x_g
norma_2 = np.linalg.norm(residuo_vector, ord=2)
norma_inf = np.linalg.norm(residuo_vector, ord=np.inf)

print("Norma 2 del residuo:", norma_2)
print("Norma infinito del residuo:", norma_inf)

Norma 2 del residuo: 3.6592857233801084e+72
Norma infinito del residuo: 2.694516873535831e+72


#4 Método de potencias para el valor propio dominante

Sea \$A\in\mathbb{R}^{n\times n}\$ diagonalizable con valor propio dominante \$\lambda\_{\max}\$ (en magnitud) y vector propio asociado \$v\_{\max}\$.

El método de potencias genera, a partir de un vector inicial \$q^{(0)}\neq 0\$, la sucesión

$$
q^{(k+1)} \;=\; \frac{A\,q^{(k)}}{\lVert A\,q^{(k)}\rVert_2},
\qquad
\lambda^{(k+1)} \;=\; (q^{(k+1)})^{\!\top} A\, q^{(k+1)},
$$

que converge a \$v\_{\max}/\lVert v\_{\max}\rVert\_2\$ y a \$\lambda\_{\max}\$ respectivamente, bajo hipótesis estándar.

Implemente `power_method(A, tol=1e-7, max_iter=1000)` que:

   * Acepte matrices reales cuadradas,
   * Devuelva \$\lambda\_{\max}\$, el vector propio normalizado \$v\_{\max}\$, el número de iteraciones y la última variación relativa de \$\lambda\$,
   * detenga la iteración cuando
     $\bigl|\lambda^{(k+1)}-\lambda^{(k)}\bigr|<\text{tol}\,|\lambda^{(k+1)}|$
     o se alcance `max_iter`.

Luego,
   * Genere una matriz simétrica aleatoria \$6\times6\$ (por ejemplo, \$A = (M+M^\top)/2\$ con \$M\$ aleatoria).
   * Aplique su `power_method` y compare \$\lambda\_{\max}\$ y \$v\_{\max}\$ con los resultados de `numpy.linalg.eig`.

In [14]:
#realizamos la función
def power_method(A, tol=1e-7, max_iter=1000):
  '''
  Método de potencias para encontrar el valor propio dominante y su vector propio asociado.

  Parámetros:
  A: Matriz cuadrada real -> ndarray
  tol: Tolerancia para el criterio de convergencia. -> float
  max_iter: Número máximo de iteraciones -> int

  Retorna:
  tupla: (λ_max, v_max, iteraciones, delta_lambda)
  λ_max: valor propio dominante
  v_max: vector propio asociado
  iteraciones: número de iteraciones realizadas
  delta_lambda: última variación relativa del valor propio.
  '''

  #verificamos si la matriz es cuadrada
  if A.shape[0] != A.shape[1]:
      raise ValueError("La matriz debe ser cuadrada para aplicar el método.")

  n = A.shape[0]
  q = np.random.rand(n) #vector inicial aleatorio
  q = q / la.norm(q) #normalizamos

#inicializar el valor propio anterior
  lambda_o = 0

  for i in range(max_iter):
      Aq = A @ q #multiplicar la matriz por el vector actual
      q = Aq / la.norm(Aq) #normalizar el nuevo vector
      lambda_n = q.T @ A @ q #estimar el valor propio usando el producto escalar

      #criterio de convergencia para lambda
      if abs(lambda_n - lambda_o) < tol:
          break #convergió

      lambda_o = lambda_n

  #valor propio, vector propio, número de iteraciones, variación final
  return lambda_n, q, i + 1, abs(lambda_n - lambda_o)

In [15]:
#generamos la matriz aleatoria
M = np.random.rand(6, 6)
A = (M + M.T) / 2  #simetría

In [16]:
#método de potencias
lambdap_max, vp_max, iteraciones, delta_lambda = power_method(A)

#comparar con el método de numpy
valores, vectores = la.eig(A)
i_max = np.argmax(np.abs(valores))
lambdan_max = valores[i_max]
vn_max = vectores[:, i_max]

# resultados
print(f"λ_max con Power Method: {lambdap_max}")
print(f"v_max con Power Method: {vp_max}")
print(f"Número de iteraciones: {iteraciones}")
print(f"Última variación de λ: {delta_lambda}")
print(f"\nλ_max con NumPy: {lambdan_max}")
print(f"v_max con NumPy {vn_max / la.norm(vn_max)}")


λ_max con Power Method: 2.555774689386226
v_max con Power Method: [0.46205267 0.41456819 0.49573051 0.27779233 0.47870249 0.25013429]
Número de iteraciones: 7
Última variación de λ: 2.6911397110751523e-08

λ_max con NumPy: (2.5557746914739248+0j)
v_max con NumPy [0.46206711 0.41457179 0.49571215 0.27779676 0.4787058  0.25012677]


#5

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [17]:
#definimos las matrices de Pauli e identidad
sigma_x = np.array([[0, 1], [1, 0]], dtype=complex)
sigma_y = np.array([[0, -1j], [1j, 0]], dtype=complex)
sigma_z = np.array([[1, 0], [0, -1]], dtype=complex)
I = np.eye(2, dtype=complex)

def decomponer(L):
    """Recibe matriz 2x2 Hermitiana L y devuelve (a,b,c,d) reales
       tales que L = a*sigma_x + b*sigma_y + c*sigma_z + d*I
    """
    if L.shape != (2,2):
        raise ValueError("L debe ser 2x2")
    if not np.allclose(L, L.conj().T):
        raise ValueError("L debe ser Hermitiana")
    p = L[0,0].real
    r = L[1,1].real
    q = L[0,1]
    a = q.real
    b = -q.imag
    c = (p - r) / 2
    d = (p + r) / 2
    return float(a), float(b), float(c), float(d)

def reconstruir(a,b,c,d):
    """Reconstruye la matriz a*sx + b*sy + c*sz + d*I"""
    return a*sigma_x + b*sigma_y + c*sigma_z + d*I


In [18]:
#generamos una matriz aleatoria hermitiana 2x2
p = np.random.randn()
r = np.random.randn()
q = np.random.randn() + 1j*np.random.randn()
L_rand = np.array([[p, q], [np.conj(q), r]], dtype=complex)

#descomponer y reconstruir
a,b,c,d = decomponer(L_rand)
L_rec = reconstruir(a,b,c,d)

#resultados
print("Matriz aleatoria Hermitiana:\n", L_rand)
print(f"Coeficientes: a={a:.4f}, b={b:.4f}, c={c:.4f}, d={d:.4f}")
print("Reconstrucción:\n", L_rec)
print("¿Las matrices son iguales?:", np.allclose(L_rand, L_rec))

Matriz aleatoria Hermitiana:
 [[-0.42533682+0.j          0.58613265+0.74392087j]
 [ 0.58613265-0.74392087j -1.25966705+0.j        ]]
Coeficientes: a=0.5861, b=-0.7439, c=0.4172, d=-0.8425
Reconstrucción:
 [[-0.42533682+0.j          0.58613265+0.74392087j]
 [ 0.58613265-0.74392087j -1.25966705+0.j        ]]
¿Las matrices son iguales?: True


# 6

Haga un breve resumen en Markdown de las funciones y métodos más relevantes para algebra lineal usando Python. Emplee ejemplos.

Las funciones y métodos de álgebra lineal en Python, especialmente a través de NumPy, permiten realizar operaciones esenciales como productos punto (`np.dot`) y cruz (`np.cross`), transposición de matrices (`np.transpose`), cálculo de inversas (`np.linalg.inv`), determinantes (`np.linalg.det`) y trazas (`np.trace`), extracción o creación de diagonales (`np.diag`) y resolución de sistemas lineales (`np.linalg.solve`). Estas herramientas son fundamentales para multiplicación de matrices, análisis de transformaciones lineales y manejo de matrices diagonales. Además, la factorización LU optimiza la resolución de múltiples sistemas con la misma matriz, y los métodos iterativos como Jacobi o Gauss-Seidel resultan ser más eficientes, aunque su convergencia depende de las propiedades de la matriz.

```python
# 1. Productos punto y cruz
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Producto punto: suma de multiplicaciones elemento a elemento
punto = np.dot(a, b)
print("Producto punto:", punto)  # Resultado: 1*4 + 2*5 + 3*6 = 32

# Producto cruz: vector perpendicular a ambos
cruz = np.cross(a, b)
print("Producto cruz:", cruz)  # Resultado: [-3, 6, -3]

# 2. Transposición de matrices
M = np.array([[1, 2], [3, 4]])
print("\nMatriz original:\n", M)
print("Matriz transpuesta:\n", np.transpose(M))  # Cambia filas por columnas

# 3. Inversa de una matriz
A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)  # Calcula la inversa de A
print("\nInversa de A:\n", A_inv)

# 4. Determinante de una matriz
det_A = np.linalg.det(A)  # Determinante
print("\nDeterminante de A:", det_A)

# 5. Traza de una matriz
traza = np.trace(A)  # Suma de los elementos en la diagonal principal
print("Traza de A:", traza)

# 6. Creación y extracción de diagonales
# Crear matriz diagonal a partir de un vector
diag_mat = np.diag([1, 2, 3])
print("\nMatriz diagonal:\n", diag_mat)

# Extraer diagonal principal de una matriz
diagonal = np.diag(A)
print("Diagonal de A:", diagonal)

# 7. Resolución de sistemas lineales
# Sistema: 3x + y = 9  y  x + 2y = 8
A = np.array([[3, 1], [1, 2]])  # Matriz de coeficientes
b = np.array([9, 8]) # Vector de términos independientes

# Resolver usando numpy.linalg.solve
x = np.linalg.solve(A, b)
print("\nSolución del sistema (x, y):", x)
