In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: kevin velasquez gonzalez
*Métodos computacionales*

---

#1
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [1]:
import numpy as np

# Crear tres matrices aleatorias 3x3
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))
C = np.random.randint(1, 10, (3, 3))

print("Matriz A:\n", A)
print("Matriz B:\n", B)
print("Matriz C:\n", C)

# 1. AB != BA en general
print("\nAB:\n", np.dot(A, B))
print("BA:\n", np.dot(B, A))

# 2. (AB)C = A(BC)
print("\n(AB)C:\n", np.dot(np.dot(A, B), C))
print("A(BC):\n", np.dot(A, np.dot(B, C)))

# 3. A(B + C) = AB + AC
print("\nA(B + C):\n", np.dot(A, (B + C)))
print("AB + AC:\n", np.dot(A, B) + np.dot(A, C))

# 4. (A + B)C = AC + BC
print("\n(A + B)C:\n", np.dot((A + B), C))
print("AC + BC:\n", np.dot(A, C) + np.dot(B, C))

# 5. (AB)^T = B^T A^T
print("\n(AB)^T:\n", np.transpose(np.dot(A, B)))
print("B^T A^T:\n", np.dot(np.transpose(B), np.transpose(A)))

# 6. det(AB) = det(A) * det(B)
print("\ndet(AB):", np.linalg.det(np.dot(A, B)))
print("det(A)*det(B):", np.linalg.det(A) * np.linalg.det(B))

# 7. (A^T)^T = A
print("\n(A^T)^T:\n", np.transpose(np.transpose(A)))
print("A:\n", A)

# 8. (cA)^T = cA^T
c = 3
print(f"\n({c}A)^T:\n", np.transpose(c * A))
print(f"{c}A^T:\n", c * np.transpose(A))

# 9. (A + B)^T = A^T + B^T
print("\n(A + B)^T:\n", np.transpose(A + B))
print("A^T + B^T:\n", np.transpose(A) + np.transpose(B))

Matriz A:
 [[4 7 9]
 [9 3 9]
 [3 7 5]]
Matriz B:
 [[3 6 9]
 [3 6 3]
 [5 7 6]]
Matriz C:
 [[7 1 9]
 [2 2 2]
 [8 4 7]]

AB:
 [[ 78 129 111]
 [ 81 135 144]
 [ 55  95  78]]
BA:
 [[ 93 102 126]
 [ 75  60  96]
 [101  98 138]]

(AB)C:
 [[1692  780 1737]
 [1989  927 2007]
 [1199  557 1231]]
A(BC):
 [[1692  780 1737]
 [1989  927 2007]
 [1199  557 1231]]

A(B + C):
 [[192 183 224]
 [222 186 294]
 [130 132 154]]
AB + AC:
 [[192 183 224]
 [222 186 294]
 [130 132 154]]

(A + B)C:
 [[219 105 215]
 [198  78 210]
 [172  80 177]]
AC + BC:
 [[219 105 215]
 [198  78 210]
 [172  80 177]]

(AB)^T:
 [[ 78  81  55]
 [129 135  95]
 [111 144  78]]
B^T A^T:
 [[ 78  81  55]
 [129 135  95]
 [111 144  78]]

det(AB): -9072.000000000016
det(A)*det(B): -9071.99999999999

(A^T)^T:
 [[4 7 9]
 [9 3 9]
 [3 7 5]]
A:
 [[4 7 9]
 [9 3 9]
 [3 7 5]]

(3A)^T:
 [[12 27  9]
 [21  9 21]
 [27 27 15]]
3A^T:
 [[12 27  9]
 [21  9 21]
 [27 27 15]]

(A + B)^T:
 [[ 7 12  8]
 [13  9 14]
 [18 12 11]]
A^T + B^T:
 [[ 7 12  8]
 [13  9 14]
 [1

#2

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [4]:
def determinante(matriz):
  """
  divide la matriz en matrices más pequeñas, calcula sus determinantes y los combina siguiendo la fórmula de Laplace.
  """
  if len(matriz) == 1: # Si es 1x1, el determinante es el único elemento
        return matriz[0][0]
  if len(matriz) == 2:  # Si es 2x2, aplicar la fórmula directa
        return matriz[0][0] * matriz[1][1] - matriz[0][1] * matriz[1][0]

  det = 0
  for j in range(len(matriz)):
        submatriz = [fila[:j] + fila[j+1:] for fila in matriz[1:]] # Crear submatriz quitando la fila 0 y columna j
        det += ((-1) ** j) * matriz[0][j] * determinante(submatriz)
  return det

#Ejemplo
matriz = [
    [2, 3, 1],
    [4, 1, 5],
    [7, 2, 6]
]

print("Matriz:")
for fila in matriz:
    print(fila)

print("Determinante:", determinante(matriz))

Matriz:
[2, 3, 1]
[4, 1, 5]
[7, 2, 6]
Determinante: 26


#3 Método de Gauss - Seidel

Sea \$A\in\mathbb{R}^{n\times n}\$ no singular y sea \$b\in\mathbb{R}^n\$.
Descomponga \$A\$ como

$$
A \;=\; D \;+\; L \;+\; U,
$$

donde

* \$D\$ es la matriz diagonal de \$A\$,
* \$L\$ es la parte estrictamente triangular inferior,
* \$U\$ es la parte estrictamente triangular superior.

El algoritmo de Gauss - Seidel reorganiza el sistema \$Ax=b\$ como

$$
x \;=\; (D+L)^{-1}\bigl(b \;-\; Ux\bigr),
$$

y genera la sucesión

$$
x_i^{(k+1)}
= \frac{1}{a_{ii}}
\Bigl(b_i - \sum_{j<i} a_{ij}\,x_j^{(k+1)} - \sum_{j>i} a_{ij}\,x_j^{(k)}\Bigr),
\qquad i=1,\dots,n.
$$

Implemente una función `gauss_seidel(A, b, tol=1e-7, max_iter=100)` que:
   * Realice las iteraciones hasta que
     $\lVert x^{(k+1)}-x^{(k)}\rVert_\infty<\text{tol}$
     o se alcance `max_iter`;
   * devuelva el vector solución aproximado \$x\$, el número de iteraciones realizadas y la norma del último residuo.

Incluya una documentación clara.

Luego,

   * Genere una matriz aleatoria \$5\times5\$ (por ejemplo, con `np.random.rand`) y un vector \$b\$ aleatorio.
   * Resuelva \$Ax=b\$ con su función; calcule el error relativo frente a `numpy.linalg.solve`.
   * Estime igualmente el error respecto a la solución obtenida mediante \$x=A^{-1}b\$ (usando `numpy.linalg.inv`).
   * Presente las normas de los residuos y los errores relativos.

In [8]:
import numpy as np

def gauss_seidel(A, b, tol=1e-7, max_iter=100):
    n = len(b)
    x = np.zeros(n)

    for k in range(max_iter):
        x_new = np.copy(x)

        for i in range(n):
            suma1 = np.dot(A[i, :i], x_new[:i])
            suma2 = np.dot(A[i, i+1:], x[i+1:])
            x_new[i] = (b[i] - suma1 - suma2) / A[i, i]

        if np.linalg.norm(x_new - x, np.inf) < tol:
            return x_new, k+1, np.linalg.norm(b - A @ x_new)

        x = x_new

    return x, max_iter, np.linalg.norm(b - A @ x)

# Matriz y vector aleatorio
A = np.random.rand(5, 5)
b = np.random.rand(5)

#Gauss-Seidel
x_gs, iters, residuo = gauss_seidel(A, b)
print("Solución Gauss-Seidel:", x_gs)
print("Iteraciones:", iters)
print("Norma residuo:", residuo)

#Comparar con numpy
x_np = np.linalg.solve(A, b)
print("\nSolución numpy:", x_np)

#Errores
error_relativo = np.linalg.norm(x_gs - x_np) / np.linalg.norm(x_np)
print("Error relativo:", error_relativo)


Solución Gauss-Seidel: [-8.39845089e+119 -1.18906229e+119 -1.27484918e+121  2.33237205e+120
  2.49658604e+121]
Iteraciones: 100
Norma residuo: 3.0210581031439275e+121

Solución numpy: [-1.20736145  0.82064284 -1.25497328  2.35564009 -0.22892469]
Error relativo: 9.224398452714249e+120


#4 Método de potencias para el valor propio dominante

Sea \$A\in\mathbb{R}^{n\times n}\$ diagonalizable con valor propio dominante \$\lambda\_{\max}\$ (en magnitud) y vector propio asociado \$v\_{\max}\$.

El método de potencias genera, a partir de un vector inicial \$q^{(0)}\neq 0\$, la sucesión

$$
q^{(k+1)} \;=\; \frac{A\,q^{(k)}}{\lVert A\,q^{(k)}\rVert_2},
\qquad
\lambda^{(k+1)} \;=\; (q^{(k+1)})^{\!\top} A\, q^{(k+1)},
$$

que converge a \$v\_{\max}/\lVert v\_{\max}\rVert\_2\$ y a \$\lambda\_{\max}\$ respectivamente, bajo hipótesis estándar.

Implemente `power_method(A, tol=1e-7, max_iter=1000)` que:

   * Acepte matrices reales cuadradas,
   * Devuelva \$\lambda\_{\max}\$, el vector propio normalizado \$v\_{\max}\$, el número de iteraciones y la última variación relativa de \$\lambda\$,
   * detenga la iteración cuando
     $\bigl|\lambda^{(k+1)}-\lambda^{(k)}\bigr|<\text{tol}\,|\lambda^{(k+1)}|$
     o se alcance `max_iter`.

Luego,
   * Genere una matriz simétrica aleatoria \$6\times6\$ (por ejemplo, \$A = (M+M^\top)/2\$ con \$M\$ aleatoria).
   * Aplique su `power_method` y compare \$\lambda\_{\max}\$ y \$v\_{\max}\$ con los resultados de `numpy.linalg.eig`.

In [7]:
import numpy as np

def power_method(A, tol=1e-7, max_iter=1000):
    n = A.shape[0]
    q = np.random.rand(n)
    q = q / np.linalg.norm(q)
    lam = 0

    for i in range(max_iter):
        z = A @ q
        q_new = z / np.linalg.norm(z)
        lam_new = q_new @ (A @ q_new)

        if abs(lam_new - lam) < tol:
            return lam_new, q_new, i+1
        q = q_new
        lam = lam_new

    return lam, q, max_iter

# Matriz aleatoria 6x6
M = np.random.rand(6, 6)
A = (M + M.T) / 2

# Método potencias
lam_max, v_max, iters = power_method(A)

print("λ_max (método de potencias):", lam_max)
print("v_max (método de potencias):\n", v_max)
print("Iteraciones:", iters)

# Comparar con numpy
vals, vecs = np.linalg.eig(A)
idx = np.argmax(vals)
print("\nλ_max (numpy):", vals[idx])
print("v_max (numpy):\n", vecs[:, idx])


λ_max (método de potencias): 3.1991809968741833
v_max (método de potencias):
 [0.35978493 0.43264234 0.4998745  0.34110423 0.33718331 0.4510612 ]
Iteraciones: 5

λ_max (numpy): 3.199181000677134
v_max (numpy):
 [0.35979288 0.43263702 0.49989069 0.3411212  0.33717984 0.4510318 ]


#5

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [6]:
import numpy as np

# Matrices de Pauli y matriz identidad
sx = np.array([[0, 1], [1, 0]])
sy = np.array([[0, -1j], [1j, 0]])
sz = np.array([[1, 0], [0, -1]])
I  = np.array([[1, 0], [0, 1]])

# Coeficientes reales
a, b, c, d = 2, -1, 3, 4

# Combinación lineal
L = a*sx + b*sy + c*sz + d*I

print("Matriz L:\n", L)

# Verificar que L es hermitiana
print("L es hermitiana?:", np.allclose(L, L.conj().T))


Matriz L:
 [[7.+0.j 2.+1.j]
 [2.-1.j 1.+0.j]]
L es hermitiana?: True


# 6

Haga un breve resumen en Markdown de las funciones y métodos más relevantes para algebra lineal usando Python. Emplee ejemplos.

NumPy es perfecto para álgebra lineal:
crear matrices y vectores, calcular transpuesta, inversa y determinante, multiplicar matrices, resolver sistemas de ecuaciones, obtener valores y vectores propios, y calcular normas de vectores.

In [11]:
# Funciones y métodos de álgebra lineal en Python (NumPy)

## Crear matrices y vectores
import numpy as np
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

## Transpuesta
n=A.T

## Inversa
m=np.linalg.inv(A)

## Determinante
p=np.linalg.det(A)

## Multiplicación de matrices
q=np.dot(A, b)

## Resolver sistemas
x = np.linalg.solve(A, b)

## Valores y vectores propios
y=valores, vectores = np.linalg.eig(A)

## Norma de un vector
z=np.linalg.norm(b)

print(n,m,p,q,x,y,z)


[[1 3]
 [2 4]] [[-2.   1. ]
 [ 1.5 -0.5]] -2.0000000000000004 [17 39] [-4.   4.5] EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])) 7.810249675906654
