In [5]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

# Actividad 08: Algebra Lineal y Matrices

---
### Profesor: Juan Marcos Marín
### Nombre: ______
*Métodos computacionales*

---

#1
Escriba tres matrices aleatorias $A$, $B$ y $C$ de $3\times 3$, y demuestre las siguientes relaciones

- $ \mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A} $, en general.
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.
- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.



In [6]:
A = np.array([
    [5, 2, 7],
    [9, 1, 3],
    [6, 3, 8]
])

B = np.array([
    [3, 9, 7],
    [2, 1, 9],
    [4, 2, 7]
])

C = np.array([
    [2, 9, 10],
    [4, 5, 11],
    [3, 9, 2]
])

Multiplicacion_AB = A@B
Multiplicacion_BA = B@A

print('AB =')
print(Multiplicacion_AB)
print('\nBA =')
print(Multiplicacion_BA)


AB =
[[ 47  61 102]
 [ 41  88  93]
 [ 56  73 125]]

BA =
[[138  36 104]
 [ 73  32  89]
 [ 80  31  90]]


Como vemos, $BA \neq AB$


In [7]:
Multiplicacion_BC = B@C
Multiplicacion_AC = A@C
Suma_BC = B + C
Suma_AB_AC = Multiplicacion_AB + Multiplicacion_AC
Suma_AB = A + B
Suma_AC_BC = Multiplicacion_AC + Multiplicacion_BC

print('(AB)C =')
print(Multiplicacion_AB @ C)
print('\nA(BC)=')
print(A @ Multiplicacion_BC)

print('\nA(B + C)')
print(A @ Suma_BC)
print('\n AB + AC')
print(Multiplicacion_AB + Multiplicacion_AC)

print('\n(A + B)C')
print(Suma_AB @ C)
print('\nAC + BC')
print(Multiplicacion_AC + Multiplicacion_BC)

(AB)C =
[[ 644 1646 1345]
 [ 713 1646 1564]
 [ 779 1994 1613]]

A(BC)=
[[ 644 1646 1345]
 [ 713 1646 1564]
 [ 779 1994 1613]]

A(B + C)
[[ 86 179 188]
 [ 72 201 200]
 [104 214 234]]

 AB + AC
[[ 86 179 188]
 [ 72 201 200]
 [104 214 234]]

(A + B)C
[[102 253 229]
 [ 66 217 156]
 [ 85 250 185]]

AC + BC
[[102 253 229]
 [ 66 217 156]
 [ 85 250 185]]


Vemos que las siguientes propiedades se cumplen:
- $ (\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C}) $.
- $ \mathbf{A}(\mathbf{B} + \mathbf{C}) = \mathbf{A}\mathbf{B} + \mathbf{A}\mathbf{C} $.
- $ (\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C} $.

In [8]:
print('(AB)ᵀ')
print(Multiplicacion_AB.T)
print('BᵀAᵀ')
print(B.T @ A.T)

print(f'\ndet(AB) = {np.linalg.det(Multiplicacion_AB)}')
print(f'det(A)det(B) = {np.dot(np.linalg.det(A), np.linalg.det(B))}')

print('\n(Aᵀ)ᵀ')
print(A.T.T)
print('A')
print(A)

#Sea c = 5
c = 5
Multiplicacion_cA = np.dot(5, A)
print('\n(5A)ᵀ')
print(Multiplicacion_cA.T)
print('5Aᵀ')
print(np.dot(5, A.T))
print('\n(A + B)ᵀ')
print(Suma_AB.T)
print('Aᵀ + Bᵀ')
print(A.T + B.T)

(AB)ᵀ
[[ 47  41  56]
 [ 61  88  73]
 [102  93 125]]
BᵀAᵀ
[[ 47  41  56]
 [ 61  88  73]
 [102  93 125]]

det(AB) = 5609.999999999989
det(A)det(B) = 5610.000000000002

(Aᵀ)ᵀ
[[5 2 7]
 [9 1 3]
 [6 3 8]]
A
[[5 2 7]
 [9 1 3]
 [6 3 8]]

(5A)ᵀ
[[25 45 30]
 [10  5 15]
 [35 15 40]]
5Aᵀ
[[25 45 30]
 [10  5 15]
 [35 15 40]]

(A + B)ᵀ
[[ 8 11 10]
 [11  2  5]
 [14 12 15]]
Aᵀ + Bᵀ
[[ 8 11 10]
 [11  2  5]
 [14 12 15]]


Vemos como todas a excepción de la del determinante (posiblemente por problemas de redondeo) se cumplen:

- $ (\mathbf{A}\mathbf{B})^\top = \mathbf{B}^\top \mathbf{A}^\top $.
- $ \det(\mathbf{A}\mathbf{B}) = \det(\mathbf{A}) \det(\mathbf{B}) $.
- $ (\mathbf{A}^\top)^\top = \mathbf{A} $.
- $ (c\mathbf{A})^\top = c\mathbf{A}^\top $.
- $ (\mathbf{A} + \mathbf{B})^\top = \mathbf{A}^\top + \mathbf{B}^\top $.

#2

El **Teorema de Laplace** es un método para calcular el determinante de una matriz cuadrada, particularmente útil para matrices de orden mayor a 2. Este teorema se basa en la expansión del determinante por los elementos de una fila o una columna cualquiera.



$$
\det(A) = \sum_{j=1}^n (-1)^{1+j} a_{1j} M_{1j}
$$

donde:
- $a_{1j}$ es el elemento de la primera fila y columna $j$.
- $M_{1j}$ es el menor asociado al elemento $a_{1j}$, es decir, el determinante de la submatriz de $3 \times 3$ que se obtiene al eliminar la fila 1 y la columna $j$.
- $(-1)^{1+j}$ es el signo correspondiente al cofactor del elemento $a_{1j}$.

Podemos realizar una función recursiva para el cálculo del determinante, sabiendo que el valor del determinante de una matriz de orden uno es el único elemento de esa matriz, y el de una matriz de orden superior a uno es la suma de cada uno de los elementos de una fila o columna por los Adjuntos a ese elemento, como en la función recursiva se emplea la misma función definida el cálculo lo haremos por Menor complementario, un ejemplo desarrollado por la primera fila sería:

$$
   \det (A_{j,j}) =
   \left \{
   \begin{array}{llcl}
      si & j = 1 & \to & a_{1,1} \\
                                 \\
      si & j > 1 & \to & \displaystyle \sum_{k=1}^j \; (-1)^{(1+k)} \cdot a_{1,k} \cdot \det( \alpha_{1,k})
   \end{array}
   \right .
$$

Realice una función que encuentre el determinante de una matriz usando la recursividad aqui planteada, explique explicitamente su código

In [9]:
def determinante(A):
    """
    Calcula el determinante de una matriz cuadrada A usando recursión.
    :param A: np.array, matriz cuadrada
    :return: float, determinante de A
    """
    # Verificar si la matriz es 1x1
    if A.shape == (1, 1):
        return A[0, 0]

    # Verificar si la matriz es 2x2
    if A.shape == (2, 2):
        return A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0]

    # Expandir por cofactores (primera fila)
    det = 0
    for j in range(A.shape[1]):
        # Crear matriz menor al eliminar la primera fila y la j-ésima columna
        menor = np.delete(np.delete(A, 0, axis=0), j, axis=1)
        # Agregar el cofactor
        det += ((-1) ** j) * A[0, j] * determinante(menor)

    return det
A = np.array([
    [1, 3, 9],
    [2, 1, 7],
    [9, 0, 3]
])
det_A = determinante(A)
det_A

np.int64(93)

#3 Método de Gauss - Seidel

Sea \$A\in\mathbb{R}^{n\times n}\$ no singular y sea \$b\in\mathbb{R}^n\$.
Descomponga \$A\$ como

$$
A \;=\; D \;+\; L \;+\; U,
$$

donde

* \$D\$ es la matriz diagonal de \$A\$,
* \$L\$ es la parte estrictamente triangular inferior,
* \$U\$ es la parte estrictamente triangular superior.

El algoritmo de Gauss - Seidel reorganiza el sistema \$Ax=b\$ como

$$
x \;=\; (D+L)^{-1}\bigl(b \;-\; Ux\bigr),
$$

y genera la sucesión

$$
x_i^{(k+1)}
= \frac{1}{a_{ii}}
\Bigl(b_i - \sum_{j<i} a_{ij}\,x_j^{(k+1)} - \sum_{j>i} a_{ij}\,x_j^{(k)}\Bigr),
\qquad i=1,\dots,n.
$$

Implemente una función `gauss_seidel(A, b, tol=1e-7, max_iter=100)` que:
   * Realice las iteraciones hasta que
     $\lVert x^{(k+1)}-x^{(k)}\rVert_\infty<\text{tol}$
     o se alcance `max_iter`;
   * devuelva el vector solución aproximado \$x\$, el número de iteraciones realizadas y la norma del último residuo.

Incluya una documentación clara.

Luego,

   * Genere una matriz aleatoria \$5\times5\$ (por ejemplo, con `np.random.rand`) y un vector \$b\$ aleatorio.
   * Resuelva \$Ax=b\$ con su función; calcule el error relativo frente a `numpy.linalg.solve`.
   * Estime igualmente el error respecto a la solución obtenida mediante \$x=A^{-1}b\$ (usando `numpy.linalg.inv`).
   * Presente las normas de los residuos y los errores relativos.

In [13]:
def metodo_potencias(M, precision=1e-7, limite_iter=1000):
    '''
    Algoritmo de la potencia para hallar el mayor autovalor y su autovector
    '''
    M = np.array(M, dtype=float)
    tam = M.shape[0]

    v = np.random.rand(tam)
    v /= np.linalg.norm(v)

    val_anterior = 0

    for paso in range(1, limite_iter + 1):
        prod = M @ v
        v = prod / np.linalg.norm(prod)
        val_actual = v @ M @ v

        # Verificación de tolerancia
        cambio = abs(val_actual - val_anterior) / abs(val_actual)

        if cambio < precision:
            break

        val_anterior = val_actual

    return val_actual, v, paso, cambio

metodo_potencias(A)

(np.float64(6.357127491786701),
 array([0.40273691, 0.54156204, 0.37497515, 0.3046293 , 0.5577707 ]),
 22,
 np.float64(4.9668642109493214e-08))

#4 Método de potencias para el valor propio dominante

Sea \$A\in\mathbb{R}^{n\times n}\$ diagonalizable con valor propio dominante \$\lambda\_{\max}\$ (en magnitud) y vector propio asociado \$v\_{\max}\$.

El método de potencias genera, a partir de un vector inicial \$q^{(0)}\neq 0\$, la sucesión

$$
q^{(k+1)} \;=\; \frac{A\,q^{(k)}}{\lVert A\,q^{(k)}\rVert_2},
\qquad
\lambda^{(k+1)} \;=\; (q^{(k+1)})^{\!\top} A\, q^{(k+1)},
$$

que converge a \$v\_{\max}/\lVert v\_{\max}\rVert\_2\$ y a \$\lambda\_{\max}\$ respectivamente, bajo hipótesis estándar.

Implemente `power_method(A, tol=1e-7, max_iter=1000)` que:

   * Acepte matrices reales cuadradas,
   * Devuelva \$\lambda\_{\max}\$, el vector propio normalizado \$v\_{\max}\$, el número de iteraciones y la última variación relativa de \$\lambda\$,
   * detenga la iteración cuando
     $\bigl|\lambda^{(k+1)}-\lambda^{(k)}\bigr|<\text{tol}\,|\lambda^{(k+1)}|$
     o se alcance `max_iter`.

Luego,
   * Genere una matriz simétrica aleatoria \$6\times6\$ (por ejemplo, \$A = (M+M^\top)/2\$ con \$M\$ aleatoria).
   * Aplique su `power_method` y compare \$\lambda\_{\max}\$ y \$v\_{\max}\$ con los resultados de `numpy.linalg.eig`.

In [12]:
def gs_iterativo(M, c, eps=1e-7, max_pasos=100):
    '''
    Aproxima la solución del sistema Mx = c con el esquema de Gauss-Seidel.
    '''
    M = np.array(M, dtype=float)
    c = np.array(c, dtype=float).flatten()
    n = M.shape[0]

    aprox = np.zeros_like(c)
    nuevo = aprox.copy()

    for paso in range(max_pasos):
        for fila in range(n):
            antes = sum(M[fila, col] * nuevo[col] for col in range(fila))
            despues = sum(M[fila, col] * aprox[col] for col in range(fila + 1, n))
            nuevo[fila] = (c[fila] - antes - despues) / M[fila, fila]

        if np.linalg.norm(nuevo - aprox, ord=np.inf) < eps:
            break
        aprox = nuevo.copy()

    error = np.linalg.norm(c - M @ nuevo, ord=np.inf)
    return nuevo, paso + 1, error


(np.float64(6.35712660297747),
 array([0.40273696, 0.54156133, 0.37497405, 0.30462942, 0.55777203]),
 24,
 np.float64(6.868675795514814e-08))

#5

Verifique que cualquier matriz hermitiana de 2 × 2 $ L $ puede escribirse como una suma de cuatro términos:

$$ L = a\sigma_x + b\sigma_y + c\sigma_z + dI $$

donde $ a $, $ b $, $ c $ y $ d $ son números reales.

Las cuatro matrices de Pauli son:

$$ \sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad \sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix}, \quad \sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}, \quad I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} $$




In [14]:
sx = np.array([[0, 1], [1, 0]], dtype=complex)
sy = np.array([[0, -1j], [1j, 0]], dtype=complex)
sz = np.array([[1, 0], [0, -1]], dtype=complex)
ident = np.eye(2, dtype=complex)

# Valores aleatorios para la matriz
p1, p2 = np.random.rand(2)
q1, q2 = np.random.rand(2)

mat = np.array([[p1, q1 + 1j*q2],
                [q1 - 1j*q2, p2]], dtype=complex)

# Coeficientes de la expansión
coef_x = 0.5 * np.trace(mat @ sx).real
coef_y = 0.5 * np.trace(mat @ sy).real
coef_z = 0.5 * np.trace(mat @ sz).real
coef_id = 0.5 * np.trace(mat @ ident).real

# Reconstrucción
mat_recon = coef_x*sx + coef_y*sy + coef_z*sz + coef_id*ident

print('Matriz original:')
print(np.round(mat, 4))

print('Valores obtenidos:')
print(f'cx = {coef_x:.4f}, cy = {coef_y:.4f}, cz = {coef_z:.4f}, ci = {coef_id:.4f}')

print('Matriz reconstruida:')
print(np.round(mat_recon, 4))

error_abs = np.linalg.norm(mat - mat_recon)
print(f'Diferencia total: {error_abs:.2e}')


Matriz original:
[[0.3595+0.j     0.6976+0.0602j]
 [0.6976-0.0602j 0.437 +0.j    ]]
Valores obtenidos:
cx = 0.6976, cy = -0.0602, cz = -0.0388, ci = 0.3983
Matriz reconstruida:
[[0.3595+0.j     0.6976+0.0602j]
 [0.6976-0.0602j 0.437 +0.j    ]]
Diferencia total: 0.00e+00


# 6

Haga un breve resumen en Markdown de las funciones y métodos más relevantes para algebra lineal usando Python. Emplee ejemplos.

In [10]:
A = np.array([[2, 1], [5, 3]], dtype=float)
b = np.array([1, 2], dtype=float)

print("\n--- Matriz A ---")
print(A)
print("\n--- Vector b ---")
print(b)

print("\nProducto punto (np.dot):", np.dot(A, b))
print("Producto con @:", A @ b)

print("\nTranspuesta de A:\n", A.T)
print("Conjugado de A:\n", np.conjugate(A))
print("Hermitiana de A:\n", A.conj().T)

print("\nDeterminante de A:", np.linalg.det(A))

print("\nInversa de A:\n", np.linalg.inv(A))

x = np.linalg.solve(A, b)
print("\nSolución de Ax = b:", x)

valores, vectores = np.linalg.eig(A)
print("\nValores propios:", valores)
print("Vectores propios:\n", vectores)

print("\nNorma de A (Frobenius):", np.linalg.norm(A))
print("Norma L1 de b:", np.linalg.norm(b, ord=1))
print("Norma infinito de b:", np.linalg.norm(b, ord=np.inf))

Q, R = np.linalg.qr(A)
print("\nDescomposición QR:")
print("Q:\n", Q)
print("R:\n", R)

U, S, Vh = np.linalg.svd(A)
print("\nDescomposición SVD:")
print("U:\n", U)
print("S (valores singulares):", S)
print("Vh:\n", Vh)

A_pos_def = np.array([[4, 2], [2, 3]], dtype=float)
L = np.linalg.cholesky(A_pos_def)
print("\nDescomposición Cholesky de matriz definida positiva:")
print("L:\n", L)
